### ISSUE TITLE
Need a new icon / logo

### ISSUE THREAD

**Issue by trhodeos** [beardedspice/beardedspice#1]
We are terrible artists, and need a new icon / logo.

**Comment by austin-guevara** [comment]
Hey everyone,

I'd like to re-open this with my proposed design.

Here is the suggested logo, with the "material-esque" B.S.:

![App Logo](https://cloud.githubusercontent.com/assets/14018074/24417835/f2ad5312-13b7-11e7-9514-1a9c7ffe10b4.png)

Along with that, a matching set of menu bar icons! For now, we can use the "default" which features a knock-out version of the logo, but in future, we could use these as play/pause indicators, if that feature ever gets implemented.

![Menu Bar Icons](https://cloud.githubusercontent.com/assets/14018074/24417900/3097ab3c-13b8-11e7-9399-ddd55492f53e.png)

Please share thoughts on this! Thanks! 👍

**Comment by tmmcz** [comment]
@ austin-guevara i like the lettering but honestly initials could be for anything. the "beard" is still what gives this app it's… ahm… "spice".  you mentioned complexity in #270 so i gots to say the menubar icons are pretty bulky. also (just my own personal pref) i find diagonal icons (Spotlight, Hocus Focus) annoying but i'm OCD i guess

**Comment by austin-guevara** [comment]
@tmmcz 

Agreed on that. Not in love with the "BS" icon. I love that the beard motif is unique and recognizable. I just think there could be a more elegant app icon and a simpler icon for the menu bar. I would also love to see play/pause state integrated into that icon.
