### ISSUE TITLE
Pause/play button stops working after a while

### ISSUE THREAD

**Issue by radex** [beardedspice/beardedspice#108]
When I first connect a tab, media keys work perfectly fine. But after a while, iTunes hijacks them, and they stop working with BeardedSpice. If I try to reconnect, it still doesn't work. I have to quit iTunes, or quit and open BeardedSpice again for it to work again.

Am I the only one with this issue?

**Comment by Duros** [comment]
I can confirm this while using safari 8.0.2.

**Comment by acadet** [comment]
I have the same one, using Chrome 40.0.2214.111.
Any news about this?

**Comment by jayrhynas** [comment]
You can re-associate them with beardedspice by activating the app. Unfortunately just opening the menubar dropdown isn't enough, you have to open the preferences window.
iTunes shouldn't randomly hijack focus, but how it works is the media keys will be associated with the most recently activated media app, so if you switch to iTunes at all it will grab the media keys.
