### ISSUE TITLE
Xcode couldn't open BeardedSpiceUserDefaults.plist

### ISSUE THREAD

**Issue by achuprin** [beardedspice/beardedspice#120]
Hi. 
I can't open BeardedSpiceUserDefaults.plist file using Xcode Version 6.1.1 (6A2008a) on OS X 10.9.5.
I get "The data couldn’t be read because it isn’t in the correct format." error.

**Comment by swwd** [comment]
+1

Came here to report the same thing with same version of Xcode.

Commit 7b50c8bcdef75c81469d88f6a6709ff4a085f82c seems to contain the most recent readable version of the file.
