### ISSUE TITLE
Changelog and Version numbers in app.

### ISSUE THREAD

**Issue by foozee** [beardedspice/beardedspice#123]
Hi 

I've been using this cool tool for a while, today I decided to look if it has an update... unfortunately there doesn't seem to be a place where I could know about the currently installed version number, (it always reports version 1.0 --which clearly isn't true )
![screen shot 2015-02-22 at 12 25 49 pm](https://cloud.githubusercontent.com/assets/1040027/6318223/027c4616-ba8e-11e4-958b-22cb635be685.png)

also, it would be very helpful if there was a changelog where we can learn about updates done to which version(s) 

Thanks for your efforts guys :)

**Comment by Mikaz-fr** [comment]
Very much agree. That's something I miss also, really hard to check if we need to update it.

The next step would be an in-app updater :)

**Comment by trhodeos** [comment]
Yeah, we talked about the in-app updater a while back, but the app store costs $$, and I'm not quite sure what the status of Sparkle (http://sparkle-project.org/) is.. I had a branch adding sparkle a while back, but we didn't merge it in for one reason or another.. It was relatively simple to set up, just need an rss feed that sparkle can read from (hosted on github next to the binaries would be the obvious choice), and a private key that only the developers have access to.

**Comment by trhodeos** [comment]
I think adding the version number to the app is simple.. We just had no idea what we were doing w/ XCode :)

**Comment by Mikaz-fr** [comment]
That would be great.
But please provide also a way to get the version number from within the app.
It could be maybe a tab in the preference or an additional menu entry between "preferences" and "quit". The usual way is to have on top of the version, your names and a link to the webpage. Have all this in one place would be awesome :)

**Comment by Stillness-2** [comment]
#137, #139
