### ISSUE TITLE
Feature - Support iPhone Headphones media key

### ISSUE THREAD

**Issue by d3vnu11** [beardedspice/beardedspice#124]
Add option to also override a compatible headset pause function to also pause support radio sites.. My main problem is when listening to Pandora during work with iPhone headphones I constantly click the button to pause which just launches iTunes. :)

**Comment by klipp86** [comment]
I'm sorry I just started another "issue" with this same subject. This is something I would love to see in BeardedSpice as well, since I use my headphones all day at work! Please integrate headphone play/ pause button! Thank you!

**Comment by rguldener** [comment]
Same here, the lack of support for headphone button support is made worse by the launch of iTunes.
Would be great to have support for this in bearded spice!

**Comment by rguldener** [comment]
Looks like there are other tickets already out for this as well such as #9 and #33. General media key support for headphone buttons would be great and it looks like this should be relatively easy to do for 10.9 and 10.10?
