### ISSUE TITLE
[App Support] Deezer

### ISSUE THREAD

**Issue by golovlev** [beardedspice/beardedspice#127]
Hello! Please add support for Deezer. It's really surprising that it still doesn't supported, as Deezer is one of the biggest streaming services.

**Comment by kmplngj** [comment]
+1

**Comment by frdmn** [comment]
I think that's already implemented: 

https://github.com/beardedspice/beardedspice/blob/master/BeardedSpice/DeezerStrategy.m

(You need to compile from master branch though)

**Comment by golovlev** [comment]
Well... Why just don't include it in the release if it's implemented?

**Comment by frdmn** [comment]
I think the GitHub releases sinked into oblivion to be honest. The last release is from 23 Aug 2014 even though the project is more or less active in development (last commit in master is only 4 days old).

I always compile from source to get the latest changes / adjustments.

**Comment by Stillness-2** [comment]
17 pull requests without answer!!! :)

**Comment by trhodeos** [comment]
Sorry guys! @chedkid and I both moved to new jobs in new cities, so we have
been focusing on that. Also, I mostly use linux at work now, so I don't use
BS at all. That being said, I'll clean up some PRs this weekend and put out
a release after they have been merged, sound good?

**Comment by frdmn** [comment]
It does! Do you still review PR and maintain the project in future?

**Comment by trhodeos** [comment]
I think we will try to move maintenance/development to other people. @jayrhynas currently has push access, in addition to @josefalcon and me. If anyone is interested in maintaining/developing BS, let us know!

**Comment by Stillness-2** [comment]
I can try :)

**Comment by jayrhynas** [comment]
I'll continue contributing here and there but I can't take over project right now

**Comment by foozee** [comment]
Closing issue, deezer is implemented, favorite feature is implemented and everything cool I think a release will be due at 14th of April hopefully when we're done with this milestone!
