### ISSUE TITLE
Feature: If only one available provider/strategy, auto select it.

### ISSUE THREAD

**Issue by frdmn** [beardedspice/beardedspice#135]
Like, if I start the app and I only have one tab open (SoundCloud) I would like that the app automatically selects the tab, so I dont have to open the menu bar and select it manually.

**Comment by Stillness-2** [comment]
I think, this task may be not resolved. BeardedSpice is needed event when perform checking of providers. :)

**Comment by frdmn** [comment]
@Stillness-2 im no developer, but couldn't we check initially (at startup) and then every X seconds?

**Comment by Stillness-2** [comment]
We may, but checking "every X seconds" is bad style. :)

**Comment by frdmn** [comment]
Hmm, I was afraid you reply with something like that since it felt "hacky" as I started thinking about it. :D

However, In my opinion it would be a huge usability upgrade which then is probably more worth than "a bad style". 

Regarding the event stuff: Isn't there perhaps an event for opening a new tab?

**Comment by Stillness-2** [comment]
Better using document onLoad event. But I need some research, may be this is possible.
About "huge usability upgrade", check my pull request :) Also, you can download test build. :)

**Comment by frdmn** [comment]
@Stillness-2 Nice one!
