### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by stephan-nordnes-eriksen** [beardedspice/beardedspice#137]
### Please describe how to install this software.

I am a developer and I have still not figured it out.

**"Mac Media Keys for the Masses"** is not a good slogan for this project in the current state. How about releasing a `.dmg` or a `.app` to actually make this something for the masses?

Don't get me wrong. I love what you are trying to do with this, but it is too hard to install for, well, anyone who does not know how to work cocoapods.

**Comment by stephan-nordnes-eriksen** [comment]
I did you the favour by compiling the .app:

http://www.mediafire.com/download/25mb7hl6k84ote0/BeardedSpice.app.zip

**Comment by laughedelic** [comment]
ahm.. "_ 
If you just click the download link in readme, you'll get a `.tar.gz` archive, unpack it and you have an `.app`. What's the problem?

**Comment by stephan-nordnes-eriksen** [comment]
Well, I downloaded the .zip archive as my unzipper does not handle tar.gz very well. In there was the source files.

**Comment by Stillness-2** [comment]
Here at all is very slow :)
I prepared the pull requests 16 days ago, with good additions, in my view.
But nothing happens :)

**Comment by Stillness-2** [comment]
@stephan-nordnes-eriksen Now you can download zip file with application on beardedspice.com. This is version of the app (1.0) with auto update. 
Direct link for downloads: https://raw.github.com/beardedspice/beardedspice/distr/publish/releases/BeardedSpice-latest.zip
