### ISSUE TITLE
Find new maintainers.

### ISSUE THREAD

**Issue by trhodeos** [beardedspice/beardedspice#138]
@josefalcon and I have stopped keeping up with BS. I don't use OSX during work anymore, and don't need it. 

We would really like to find BS new owners and maintainers, as we have done a pretty crappy job recently :)

Leave us a message here if you would like to help.

**Comment by Stillness-2** [comment]
I can help with this :)))

**Comment by foozee** [comment]
I'm still learning objective-c, but I have some good background on software and the JS-side-of-things and am using the App on a daily basis and could help with the maintenance and housekeeping of the project (validating and accepting working pull requests)

**Comment by foozee** [comment]
Thanks for the invitation @trhodeos I hope we guys would have a quick meeting soon and start working on a project roadmap to see how we can move from here, what do you think @Stillness-2 ? 

My current timezone is UTC+2, and I generally have a flexible schedule so I don't want to be a party spoiler here :) I think anytime suitable for @Stillness-2 (UTC+3 if google didn't fail me :) ) will be also suitable for me. 

Let's make this happen.

Kind Regards,
Mahmoud

**Comment by foozee** [comment]
@Stillness-2 I appreciate ur energetic effort, but I think it will be better if we joined forces? much appreciate a response here please :)

**Comment by Stillness-2** [comment]
What we need to do in the near future in my opinion:
* https://github.com/beardedspice/beardedspice/milestones/1.0
* To release a "first" version
* Edit readme.md 

It is also we can add other strategies that in the pull requests

It is simple :)
Any suggestions? :)

Then (for 1.1 version):
* It is necessary to modify existing strategies to support new features
* Also to consider propose in #67 issue

**Comment by Stillness-2** [comment]
What about this issue? May be we close it. :)

**Comment by Stillness-2** [comment]
Also if you take the task in processing, then mark it (assign to). That's all :)

**Comment by foozee** [comment]
great then :) let's get things done :) --in fact I meant that we should have done exactly what u did (setting milestones :) ) so I agree 100% with u from here ;)

**Comment by foozee** [comment]
I don't think we should close this issue yet though, maybe someone else would be interested in helping :)

**Comment by fmborghino** [comment]
Happy to pitch in, altho' it looks like you guys have things under control already. Nice work.

**Comment by frdmn** [comment]
Awesome! Glad to see this active development in this project again :)

**Comment by foozee** [comment]
Thanks @frdmn and @fmborghino .. in fact we're now trying to merge most of the awesome PRs that have been floating around for a while and release version 1.0 then take it from there :) and I have to admit @Stillness-2  is doing a specially great job at that :+1:

**Comment by foozee** [comment]
@fmborghino are you interested in joining the project as an active mainter? we'd value any help for sure.

**Comment by matthewdias** [comment]
Could you please add me as a collaborator? I don't have much time to work on the project right now, but I plan to in the future, and in the mean time I'd like to clean up some of the issues.

**Comment by matthewdias** [comment]
still waiting on this ;-;

**Comment by matthewdias** [comment]
still waiting on this ;-; @Stillness-2 @fmborghino @trhodeos @foozee

**Comment by frdmn** [comment]
@matthewdias I don't see your name in the previous contributors list and also can't find a fork of `beardedspice` in your GitHub repositories. That being said, I doubt that the current maintainers hand over the push-permissions to this "productive" repository to anyone who just claims that he wants to maintain it. 

On a side note, you still can work on `beardedspice` right now. You can fork the repository and implement anything you want just like that. Once you decide it's ready for the masses, just send a PR and wait for the devs to review and merge it.

**Comment by matthewdias** [comment]
fair enough. I was simply hoping to get access to help organize the issues by tagging and closing dead ones for now, but I get that maintainers would rather see significant contribution before that. I'll disappear for awhile until I get around to working on it. @frdmn

**Comment by frdmn** [comment]
@matthewdias Ah, well I didn't even thought about an "issue maintainer" in my previous response to be honest. That would make sense, if @Stillness-2 (etc.) would like some help here of course. :+1:
