### ISSUE TITLE
Something must be solved with supporting for 10.7

### ISSUE THREAD

**Issue by Stillness-2** [beardedspice/beardedspice#140]
NSUserNotification not supported 10.7 and this release may crash on 10.7
We can do workaround using Growl or to reject from supporting 10.7

**Comment by dslysenko** [comment]
According to http://www.netmarketshare.com/operating-system-market-share.aspx?qprid=10&qpcustomd=0, OS X 10.7 has <0.5% of the market share.

**Comment by dslysenko** [comment]
On the other hand, it appears that as of a few months ago around 20% of OS X users were using 10.7 or lower ( http://www.intego.com/mac-security-blog/os-x-market-share-statistics-1-in-5-macs-still-unsupported/os-x-market-share-december-2014/ ). Just providing some stats that might help make a decision.
