### ISSUE TITLE
[App Support] Subsonic: Personal Media Streamer

### ISSUE THREAD

**Issue by CampinCarl** [beardedspice/beardedspice#145]
I would be interested in seeing [Subsonic](http://subsonic.org) added to the supported players. There's a public demo server where the JavaScript functions could be pulled from, located [here](http://demo.subsonic.org/).

Love the application so far, keep up the great work!

**Comment by foozee** [comment]
one thing we need to think about here however is, how should the app know the ip of the subsonic server, I'm thinking a configurable option maybe? 
I've checked out the demo and the website, will be downloading and trying it and will come up with something ;)

**Comment by CampinCarl** [comment]
Hmm, based on the example provided in the [Writing a Handler](https://github.com/beardedspice/beardedspice#writing-a-handler) section of the main page, it appears that the handler predicate needs to be a search string that matches the URL, correct? Are there other options available?

Since Subsonic is usually hosted by the user, as opposed to being a service with a static URL, each user's URL will be different. A configurable option would indeed solve this issue since the user could easily plug in the URL they would be using.

This actually fits well with Subsonic in my opinion since the application actually includes an option to provide a pseudo Dynamic DNS feature for users that don't want to mess with DDNS. Users can configure a http://CUSTOM.subsonic.org address right in the application options.

A configurable option would suit both DDNS users (my setup) and users that opt for the CUSTOM.subsonic.org address.

There is also a Subsonic API available, but I'm not sure if interfacing directly with the API is the intention of BeardedSpice's design.

Thoughts? And thank you for the reply!

**Comment by foozee** [comment]
well, as far as the predicate part .. you get a tab object, this opens a multitude of options (see [Tab.h](https://github.com/beardedspice/beardedspice/blob/master/BeardedSpice/Tab.h)), I guess, you can check title, url or run JS inside the tab ... personally I think that running some JS snippet (even if it's very small) in each open tab would be a bad practice performance-wise (personally I usually have 40+ tabs open at any given point in time :smile: ) 

as for interfacing with subsonic API, I believe, nope, this is kinda out of scope for BS :) and would take more maintenance than what we can afford down the road.

if you feel like writing a subsonic strategy to expedite the process I'd be happy to merge it for sure :) otherwise am sure we'll get to that issue and close it one day too (hopefully soon) :)  --we are working on app support issues without pull-request in a chronological order ;)

**Comment by CampinCarl** [comment]
Okay, thanks for the information. I'm definitely a beginner here but I'll try my hand at it.

**Comment by foozee** [comment]
I'm a beginner with BS too :) --am a new maintainer of the app-- but it's kinda easy to write a strategy for BS given the number examples we have. Would love to help you if u needed anything there, just comment here and I'll be here for u :)

Thanks for your efforts Michael.

**Comment by CampinCarl** [comment]
Okay, I've worked out the JavaScript functions to use (tested them using Chrome developer tools). I've got a strategy written that I think *should* work. What's the best way to go about testing it?

I'm new to GitHub and Git. I assume I should go ahead and pull down a copy to modify and compile to test it?

**Comment by foozee** [comment]
exactly that :) 

* you fork the repository
* follow [README](https://github.com/beardedspice/beardedspice#writing-a-handler)
* do your edits
* make sure u close beardedspice
* click Run from within xcode, it will build and run the project
* test it's working as desired
* push to your fork repo 
* create a pull request :) 

sorry if the steps are too detailed, don't mean to overwhelm u with details but meant to make it as detailed as possible :)

waiting your pull request :wink:

**Comment by CampinCarl** [comment]
No need to apologize, I'm a complete newbie to this. Trying it out now.

**Comment by foozee** [comment]
Excited u have ur first contribution on this project :) cheers

**Comment by CampinCarl** [comment]
Done! I submitted the pull request for review.

**Comment by foozee** [comment]
Thanks :) cheers

**Comment by tstackhouse** [comment]
No way to vote on this, but :+1:  This will be a great addition!

**Comment by Stillness-2** [comment]
#174
