### ISSUE TITLE
Crashes when Spotify is running

### ISSUE THREAD

**Issue by charlesfries** [beardedspice/beardedspice#152]
OS X 10.10.3, Spotify 1.0.4.90

**Comment by foozee** [comment]
@Stillness-2  any clues on this?

**Comment by Stillness-2** [comment]
No idea. We need BeardedSpice crash report from Console.app

**Comment by charlesfries** [comment]
My bad, should have supplied that. Will do tomorrow morning.

**Comment by woodnathan** [comment]
You can find several crash reports [here](https://www.dropbox.com/sh/ap00ox6ygtgaii9/AAC0q0h2WzcIv44mgAYlwNC6a?dl=0).

**Comment by Stillness-2** [comment]
Check latest release
