### ISSUE TITLE
Google Play Music Integration is now broken

### ISSUE THREAD

**Issue by Cameronjmayfield** [beardedspice/beardedspice#159]
After the redesign, keys no longer work.

Edit: Looks like they've enabled multimedia keys on their own.

**Comment by ernestorocha** [comment]
Thanks for the fix! But I can't compile from the source:
```shell
** BUILD SUCCEEDED **

Copying to staging directory.
cp: /Users/ernestorocha/Documents/beardedspice/build/Release/BeardedSpice.app: No such file or directory
```

Any idea ?

**Comment by Stillness-2** [comment]
@ernestorocha, you may try https://raw.github.com/beardedspice/beardedspice/distr/publish/releases/BeardedSpice-latest.zip

**Comment by foozee** [comment]
I assume you are running `release.sh` .. you don't really need to compile
source this way at all,
you can download the (latest release)[
https://github.com/beardedspice/beardedspice/blob/distr/publish/releases/BeardedSpice-latest.zip]
...

also if you have an existing version of BS installed, you can simply click
the menu app and choose "Check for Updates ... "

**Comment by ernestorocha** [comment]
Yeah. That's the thing, I didn't realize that I had a pretty old release. It didn't have that option on the menu.

Now it's working, thanks a lot!

**Comment by foozee** [comment]
yrw :) starting this version 1.0.6 , BS is being versioned, and it will
automatically notify you whenever an update is available :)
