### ISSUE TITLE
Loses focus anytime since the new release (1.0.8)

### ISSUE THREAD

**Issue by acadet** [beardedspice/beardedspice#163]
The app loses "focus" anytime since the new release. I need to click on it in the menu bar to make it work again. Otherwise, pressing the media keys is useless.

I thought this force focus feature was implemented a couple of versions ago. Did you remove it?

Thanks for your hard work guys!

**Comment by acadet** [comment]
Also, the application keeps crashing anytime I open another media app (such as Quicktime, VLC or iTunes).

**Comment by Stillness-2** [comment]
@acadet, can you check this build? https://www.dropbox.com/s/2ot068g4318v3fd/BeardedSpice-1.0.8-test.zip?dl=0

**Comment by acadet** [comment]
Any trouble I pointed out seems fixed now!
