### ISSUE TITLE
Google Music stopped working after changes

### ISSUE THREAD

**Issue by karoltarasiuk** [beardedspice/beardedspice#165]
I think with the new skin update plugin stopped working.

**Comment by karoltarasiuk** [comment]
I've noticed that selectors are still the same. It would mean that there's something smarter blocking the whole app.

**Comment by adziki** [comment]
Yeah, I noticed the same thing and submitted feedback to Google Play Music, so we'll see if they can shed any info.  But mark me as interested in getting this resolved ASAP.

**Comment by scott113341** [comment]
Make sure you have the latest version of BeardedSpice ([1.0.8](https://github.com/beardedspice/beardedspice/releases/download/v1.0.8/BeardedSpice-1.0.8.zip)).  That issue is already [fixed](https://github.com/beardedspice/beardedspice/pull/160).

**Comment by karoltarasiuk** [comment]
@scott113341 you rock mate - it's fixed indeed - thanks!
