### ISSUE TITLE
Does not seem to work with Logitech K750 keyboard

### ISSUE THREAD

**Issue by mlindgren80** [beardedspice/beardedspice#18]
Does this only work with the Apple Keyboard?  It works fine at work with the Apple Bluetooth keyboard, but I can't get any controls to work at home with the Logitech Keyboard.  I also have an old Microsoft Keyboard, with which I can use play/pause, but I can't switch tracks using Google Play.

Thanks!

**Comment by foozee** [comment]
@mlindgren80 can you please verify and tell us if this has been solved ? #118 is supposed to have solved this, now you'll be able to add custom shortcuts from your keyboard under the shortcuts tab in the preferences window.

please feel free to reopen this issue if our latest release doesn't solve your problem just ye!
