### ISSUE TITLE
Spotify Native Controller don't pause web controllers

### ISSUE THREAD

**Issue by danieljameswilliams** [beardedspice/beardedspice#180]
Hello, i love the new updates, but I discovered that when adding Spotify to the "Active Player Window" and playing a song, it doesn't turn of my web players (i.e. Soundcloud)

Thanks for this great app!

**Comment by Stillness-2** [comment]
Looks like a Soundcloud strategy problem. Can you repeat this issue with another web players?

**Comment by Stillness-2** [comment]
Check last release (1.1.1), or use "Check for Updates..." menu item in BeardedSpice app.
