### ISSUE TITLE
[Feature Request] Autopause when headphone is removed

### ISSUE THREAD

**Issue by ernestorocha** [beardedspice/beardedspice#186]
This scenario is pretty common nowadays. When you unplug your headphone generally you don't want your music to broadcast across the room.

So, it would be nice to have an autopause feature, thanks!

By the way, beardedspice is awesome!

**Comment by Stillness-2** [comment]
Interesting... :)

**Comment by FoxxMD** [comment]
:+1: would be nice! This is the way most music apps on android work -- if you unplug your headphones your music pauses.

**Comment by madeddie** [comment]
This app: https://github.com/steakknife/breakaway does exactly that for iTunes, we might be able to "borrow" some of their code. It has plugin infrastructure, so we might also add support for beardedspice in breakaway :)

**Comment by ernestorocha** [comment]
Nice! Thanks! :clap:

**Comment by FoxxMD** [comment]
thank you :+1:

**Comment by Mohendran** [comment]
Was this supposed to work with Bluetooth Headphones as well? Because it is not working for me.
