### ISSUE TITLE
Spotify web player url has changed

### ISSUE THREAD

**Issue by ahindle** [beardedspice/beardedspice#188]
The URL Beardedspice uses for Spotify's web player is "play.spotify.com" but Spotify redirects me to player.spotify.com. Could the second url be added, because Beardespice doesn't work anymore with Spotify's webplayer. Let me know if you need anymore information.
Thanks

**Comment by Stillness-2** [comment]
In my case Spotify stays on play.spotify.com. It is strange.
https://www.dropbox.com/s/q8sp5heaox8avwd/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-07-06%2015.44.59.png?dl=0

**Comment by ahindle** [comment]
I get redirected from https://play.spotify.com to https://player.spotify.com (I am in the UK)
