### ISSUE TITLE
[App Support] Subsonic

### ISSUE THREAD

**Issue by sardaukar** [beardedspice/beardedspice#191]
Subsonic (http://www.subsonic.org/pages/index.jsp) is a streaming server you can install at home, and has a webUI with a Flash player 

<img width="1370" alt="screen shot 2015-07-20 at 17 20 58" src="https://cloud.githubusercontent.com/assets/153407/8780859/b4ce1be8-2f03-11e5-91be-a7ae30beb897.png">

Is it possible to support it? I can give you access to my server's UI at home!

Cheers!

**Comment by Stillness-2** [comment]
Check last version please: https://raw.github.com/beardedspice/beardedspice/distr/publish/releases/BeardedSpice-latest.zip

**Comment by sardaukar** [comment]
Apologies!!
