### ISSUE TITLE
Can't tab through preferences items

### ISSUE THREAD

**Issue by adzenith** [beardedspice/beardedspice#214]
Open Preferences, and press the tab key. Expected result: focus moves to the next item. Actual result: alert sound plays.

**Comment by Stillness-2** [comment]
Well, finally I found someone who needs keyboard navigation! :) I'm happy! :)))
@adzenith, You are a rare man! :)

**Comment by adzenith** [comment]
Haha I do what I can! Thanks for adding it! Really nobody else uses keyboard navigation?? I'm all about the Full Keyboard Access.
