### ISSUE TITLE
TIDAL doesn't register as applicable tab

### ISSUE THREAD

**Issue by srsudar** [beardedspice/beardedspice#216]
When I'm listening to TIDAL BeardedSpice claims I don't have any applicable tabs open. It works for YouTube, so I'm convinced that in general BeardedSpice is working.

In the preferences supported media list I see an "A" with a circle around it next to TIDAL. Does this represent alpha support that isn't yet expected to work or something along those lines?

**Comment by Stillness-2** [comment]
Check for updates. (from BeardedSpice menu)

**Comment by srsudar** [comment]
When I tried this morning it said there were none, but now there is an update and it works. Thanks!
