### ISSUE TITLE
Add support for pcasts.in

### ISSUE THREAD

**Issue by josefalcon** [beardedspice/beardedspice#22]
From @jeffsmusings on twitter:

"Hey @chedkid, could you add the pcasts.in url to the BeardedSpice app? I want to control my @pocketcasts site links with the media keys."

"@chedkid @_trhodes_ 
Yes. Here’s how: http://bit.ly/1hNHsKQ  then http://bit.ly/1iMc6rH .
Usually used for sharing with others.
@pocketcasts"

**Comment by foozee** [comment]
@josefalcon 
umm the images are now deleted from dropbox, and [pcasts.in](http://pcasts.in) doesn't give me a site I can work with either :( however, seems like [play.pocketcasts.com](http://play.pocketcasts.com) is just working fine. closing this issue for now :)
