### ISSUE TITLE
App freezes when opening settings (unmounted network drive issue?)

### ISSUE THREAD

**Issue by Glennvd** [beardedspice/beardedspice#232]
When I try to open the settings screen from the menu bar the app freezes for ~30? seconds. Then I get a an OSX finder message about a network drive that was unable to mount (normal, I get this on startup as well when I'm not in that location). After that the dock icon appears, the app remains frozen for another 30 seconds and a second finder window pops up with the same network drive error. After this second popup I can finally open the settings window. Could it somehow be fixed that the app is not reliant on (offline) network shares?

**Comment by Stillness-2** [comment]
If you use network drive for storing of the iTunes media library, then maybe it is due to iTunes. Try uncheck iTunes Media Controller: https://www.dropbox.com/s/aa2khvbxbdfjhv2/Screenshot%202015-10-19%2021.37.24.png?dl=0

**Comment by Glennvd** [comment]
The network drive is for backups only, nothing that actually should affect beardedspice

**Comment by Stillness-2** [comment]
Check this debug build: https://www.dropbox.com/s/ubj1dzvqkwtneud/BeardedSpice.zip?dl=1
