### ISSUE TITLE
Does not appear to work with pinned tabs in el-capitan

### ISSUE THREAD

**Issue by jwdink** [beardedspice/beardedspice#240]
I hope it's OK to leave comments here without being a contributor! Just upgraded and noticed this bug.

**Comment by RSully** [comment]
Interesting, as @ascagnel mentioned success with pinned tabs [here](https://github.com/beardedspice/beardedspice/pull/223#issuecomment-145030811).

**Comment by ascagnel** [comment]
I had it work successfully when the pinned tab was the foreground tab.  I've seen issues with Plex Web when it's not the current tab, though.

**Comment by Stillness-2** [comment]
Pinned iabs works for me, after last commit 72816539289659f8e42963d44f184c3500889284 .

**Comment by ascagnel** [comment]
Pinned tabs work; however, pinned tabs are duplicated in the dropdown menu when you have multiple Safari windows open.

**Comment by Stillness-2** [comment]
@ascagnel check recent master branch

**Comment by ascagnel** [comment]
Rebuilt against master, no more duplicated listings.
