### ISSUE TITLE
BandCamp MediaStrategy not working

### ISSUE THREAD

**Issue by jonny-net** [beardedspice/beardedspice#244]
Hello, I've probably got a problem with BandCamp. Media keys don't work there, I suppose there have been some changes on the page since the release of MediaStrategy, can somebody please verify that?

I would really like to make it work, I just don't have the skills to make the changes myself.

Thanks! ;)

EDIT: Ok sorry to updating so early it don't work only in Chrome (tested on 46), Safari is working fine. It might be another problem. I'm running El Captain.

**Comment by Stillness-2** [comment]
They changed environment where applescript "execute" command is executed, in 46 version. May be this is bug or may be they planned to do it. Now our javascript code not see global objects, which was created by javascript from page. May be this is the start of the end of the Beardedspice. :)

**Comment by Stillness-2** [comment]
#257
