### ISSUE TITLE
Ability to auto-switch to app in focus

### ISSUE THREAD

**Issue by Plasma-000** [beardedspice/beardedspice#247]
There should be a checkbox which will make the app auto switch to controlling the window currently in focus without having to use the menu bar or shortcuts, and will keep switching every time you do. If the window in focus is not a valid input it should default back to the last selected one or maybe a chosen default.

**Comment by matthewdias** [comment]
Probably a better behavior would be to have it auto switch to whatever starts playing, and automatically pause the previous one.

**Comment by Stillness-2** [comment]
Check new concept of the control :)
https://www.dropbox.com/s/pzwdg1lqg1o9w5e/BeardedSpice_.zip?dl=1
