### ISSUE TITLE
spotify

### ISSUE THREAD

**Issue by pinata08** [beardedspice/beardedspice#248]
I don't know what the problem is but i can't use the hot keys for spotify web player, i read somewhere that it has something to do with it used be play.spotify.com and now its player.spotify.com??? i don't know but pls fix !! ((((:

**Comment by Stillness-2** [comment]
@pinata08, check this build: https://www.dropbox.com/s/ig77frkzu584el4/BeardedSpiceSpotifyFix.zip?dl=1
Also you can to use Spotify App. Beardedspice supports Spotify app.

**Comment by pinata08** [comment]
It still doesn’t work :/ i think you have to buy the app and i don’t wanna do that haha but thanks anyways!

**Comment by Stillness-2** [comment]
"i think you have to buy the app" - I don't understand. Spotify app is free, Beardedspice is free. What you mean?

**Comment by pinata08** [comment]
The last time I checked the spotify app was 4.99...

**Comment by Stillness-2** [comment]
May be we speak about different things. :) https://www.spotify.com/int/download/mac/

**Comment by pinata08** [comment]
Hehe you made me feel real stupid but thank you so much for your help!!!!:))

**Comment by Stillness-2** [comment]
:)
