### ISSUE TITLE
Parse Issue in iTunes.h

### ISSUE THREAD

**Issue by borismattijssen** [beardedspice/beardedspice#251]
Hi Davey,

When I try to build the project in xcode I get a lot of parse issues in the iTunes.h file.
The full error is:
`/beardedspice/BeardedSpice/Tabs/iTunes.h:151:40: Expected ')'`
The corresponding line is:
`- (SBElementArray<iTunesAirPlayDevice *> *) AirPlayDevices;`

I'm very new to xcode, objective-c and the build system.

Anyone knows what's going on?

Cheers,
Boris

**Comment by Stillness-2** [comment]
Xcode version must be 7 or above.

**Comment by borismattijssen** [comment]
Thanks!
