### ISSUE TITLE
No applicable tabs open after upgrade to 10.11

### ISSUE THREAD

**Issue by pavel-sakun** [beardedspice/beardedspice#252]
Opened tabs with youtube.com and vk.com in both chrome and safari and none of them are picked up by the app. Before upgrading to 10.11 it worked flawlessly.

**Comment by Stillness-2** [comment]
What version Beardedspice do you use?

**Comment by pavel-sakun** [comment]
@Stillness-2 1.2, "Check for updates" tells me it's the latest available.

**Comment by Stillness-2** [comment]
Очень странно тогда... Я правильно понял, что бородатый не видит табы с урлом типа *youtube.com/watch* ?

**Comment by pavel-sakun** [comment]
Да, на робочей машинке не видит, на домашней всё отлично. Если он пишет диагностическую информацию куда-то - с удовольствием поделюсь; возможно не я один с такой проблемой.

**Comment by Stillness-2** [comment]
Он пишет мало инфы, к сожалению. Пишет NSLog - ом, то есть выход виден в Console.app примерно так: https://www.dropbox.com/s/cp0l2d5g27lwe0e/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-10-14%2000.59.48.png?dl=0

По идее можно понажимать, и посмотреть, что выползет. И конечно присылайте. :)

**Comment by pavel-sakun** [comment]
Завтра погляжу, что скажет console и сюда отпишусь.

**Comment by pavel-sakun** [comment]
Как-то вот так:
10/14/15 15:28:23.888 BeardedSpice[39202]: Reset Mikeys
10/14/15 15:28:23.897 BeardedSpice[39202]: Error Domain=NSMachErrorDomain Code=-536870203 "(iokit/common) exclusive access and device already open" UserInfo={reportingLine=219, reportingMethod=-[DDHidDevice openWithOptions:], reportingFile=/Users/still/Documents/dev/DDHidLib/lib/DDHidDevice.m, origin=(*mDeviceInterface)->open(mDeviceInterface, options)}
10/14/15 15:28:34.151 Safari[39203]: tcp_connection_tls_session_error_callback_imp 2 __tcp_connection_tls_session_callback_write_block_invoke.434 error 22
10/14/15 15:28:37.183 Safari[39203]: SecTaskLoadEntitlements failed error=22
10/14/15 15:28:37.183 Safari[39203]: SecTaskLoadEntitlements failed error=22
10/14/15 15:28:37.183 Safari[39203]: SecTaskLoadEntitlements failed error=22
10/14/15 15:28:41.618 Safari[39203]: Failed to save record: <CKError 0x7fa8c83b8630: "Internal Error" (1/5001); "Fetched zone had no protection data: <CKRecordZone: 0x7fa441fef470; zoneID=History:__defaultOwner__, capabilities=(Atomic,Sync)>">
10/14/15 15:28:42.811 Safari[39203]: Caching encoded userInfo to use until we are marked dirty again (UAUserActivity.m #1567)
10/14/15 15:28:42.811 Safari[39203]: Using cached encoded userInfo to build ActivityInfo (UAUserActivity.m #2082)
10/14/15 15:29:01.587 BeardedSpice[39202]: Refreshing tabs...
10/14/15 15:29:01.590 BeardedSpice[39202]: App com.google.Chrome is running <NSRunningApplication: 0x7fab03546bf0 (com.google.Chrome - 28043)>
10/14/15 15:29:01.603 BeardedSpice[39202]: App com.apple.Safari is running <NSRunningApplication: 0x7fab058091e0 (com.apple.Safari - 39203)>
10/14/15 15:29:01.875 Safari[39203]: An exception was thrown during execution of an NSScriptCommand...
10/14/15 15:29:01.876 Safari[39203]: [<CompletionWindow 0x7fa8c72d5570> valueForUndefinedKey:]: this class is not key value coding-compliant for the key orderedTabViewItems.
10/14/15 15:29:01.877 Safari[39203]: An exception was thrown during execution of an NSScriptCommand...
10/14/15 15:29:01.877 Safari[39203]: [<RoundedWindow 0x7fa8ca365370> valueForUndefinedKey:]: this class is not key value coding-compliant for the key orderedTabViewItems.
10/14/15 15:29:01.877 BeardedSpice[39202]: App com.google.Chrome is running <NSRunningApplication: 0x7fab03735ca0 (com.google.Chrome - 28043)>
10/14/15 15:29:01.882 BeardedSpice[39202]: App com.apple.Safari is running <NSRunningApplication: 0x7fab05836200 (com.apple.Safari - 39203)>
10/14/15 15:29:01.912 BeardedSpice[39202]: Reset Media Keys.
10/14/15 15:29:01.914 BeardedSpice[39202]: Reset Media Keys.
10/14/15 15:29:12.365 BeardedSpice[39202]: Refreshing tabs...
10/14/15 15:29:12.366 BeardedSpice[39202]: App com.google.Chrome is running <NSRunningApplication: 0x7fab035c07b0 (com.google.Chrome - 28043)>
10/14/15 15:29:12.371 BeardedSpice[39202]: App com.apple.Safari is running <NSRunningApplication: 0x7fab035c9ce0 (com.apple.Safari - 39203)>
10/14/15 15:29:12.419 Safari[39203]: An exception was thrown during execution of an NSScriptCommand...
10/14/15 15:29:12.419 Safari[39203]: [<CompletionWindow 0x7fa8c72d5570> valueForUndefinedKey:]: this class is not key value coding-compliant for the key orderedTabViewItems.
10/14/15 15:29:12.420 Safari[39203]: An exception was thrown during execution of an NSScriptCommand...
10/14/15 15:29:12.420 Safari[39203]: [<RoundedWindow 0x7fa8ca365370> valueForUndefinedKey:]: this class is not key value coding-compliant for the key orderedTabViewItems.
10/14/15 15:29:12.421 BeardedSpice[39202]: App com.google.Chrome is running <NSRunningApplication: 0x7fab035b7860 (com.google.Chrome - 28043)>
10/14/15 15:29:12.425 BeardedSpice[39202]: App com.apple.Safari is running <NSRunningApplication: 0x7fab03589130 (com.apple.Safari - 39203)>
10/14/15 15:29:12.458 BeardedSpice[39202]: Reset Media Keys.
10/14/15 15:29:12.459 BeardedSpice[39202]: Reset Media Keys.

**Comment by Stillness-2** [comment]
А это ... случайно это не в Google Chome?

**Comment by Stillness-2** [comment]
Проблемы с Chrome еще объяснимы если у Вас на работе например уже 46 версия хрома (#244)
Про сафари - не понимаю пока.

**Comment by pavel-sakun** [comment]
Хром был Version 45.0.2454.101 (64-bit), теперь 46.

**Comment by Stillness-2** [comment]
#260
