### ISSUE TITLE
[Chrome] the app isn't working anymore with Chrome

### ISSUE THREAD

**Issue by ggrelet** [beardedspice/beardedspice#255]
Hi!
I love this app, I can't go without it
But for some reasons I can't explain, it's not working anymore with Chrome (and of course, YouTube, Deezer, SoundCloud etc...)

But it still works with Safari :/

I'm using OS X El Capitan and Chrome 46 (last update)

Thanks you in advance for your help and concern

EDIT : well, it seems to be working with SoundCloud...

**Comment by Stillness-2** [comment]
:( at this time I don't know what to do. #244

**Comment by ggrelet** [comment]
Well, such a pity!

Anyway keep up the good work!!
