### ISSUE TITLE
Frequent crashes on 10.11 (also happened on 10.10)

### ISSUE THREAD

**Issue by jzw95** [beardedspice/beardedspice#256]
I often go to use BeardedSpice and notice it is no longer in my menubar and it has crashed. This happened in 10.10 and continues with the latest release in 10.11. Not being a developer, I'm not sure what the cause is, hence the vague title, but [here] (https://dl.dropboxusercontent.com/u/285686/BeardedSpice_2015-10-15-120527.crash) is the latest crash report here in case it is of use in finding an issue.

**Comment by jzw95** [comment]
And [another one] (https://dl.dropboxusercontent.com/u/285686/BeardedSpice_2015-10-15-122059.crash) just now when I pressed the control on my headphones to resume playing a SoundCloud webpage.

**Comment by eugenet8k** [comment]
Getting the same kind of crushed on Yosemite 10.10.5:

10/26/15 6:05:55.890 PM BeardedSpice[16544]: Error Domain=NSMachErrorDomain Code=-536870206 "The operation couldn’t be completed. (Mach error -536870206 - (iokit/common) invalid argument)" UserInfo=0x6000000eaa80 {reportingLine=224, reportingMethod=-[DDHidDevice close], reportingFile=/Users/still/Documents/dev/DDHidLib/lib/DDHidDevice.m, origin=(*mDeviceInterface)->close(mDeviceInterface)}

**Comment by andrewslotin** [comment]
+1

Here is a [gist with console output](https://gist.github.com/andrewslotin/f6f4b6c68fd07d793b24)

**Comment by justim** [comment]
I've had this issue as well (#253), but I've been running `master` for a couple of days now and so far I didn't run into this problem again.

**Comment by Stillness-2** [comment]
#260
