### ISSUE TITLE
BeardedSpice not working on Chrome 46

### ISSUE THREAD

**Issue by bruisersmith** [beardedspice/beardedspice#257]
Active Chrome tab is checked in BS menubar - pressing play/pause unchecks it. Unable to downgrade to previously working versions of BS. Keyboard shortcuts of 'spacebar' = pause, 'n' = next, & 'p' = previous work for some reason.

**Comment by Stillness-2** [comment]
https://github.com/beardedspice/beardedspice/releases

**Comment by bruisersmith** [comment]
^^^^Not sure what you meant there, but this is what is showing up in Console on BS 1.2:

10/16/15 8:30:54.139 AM BeardedSpice[1758]: Refreshing tabs...
10/16/15 8:29:16.121 AM BeardedSpice[1758]: AppleEvents: Send port for process has no send right, port=( port:6255/0x186f rcv:1,send:0,d:0 limit:5) (findOrCreate()/AEMachUtils.cp #526) com.apple.main-thread
(THIS LINE IS REPEATED ABOUT 40 TIMES)
10/16/15 8:30:54.157 AM BeardedSpice[1758]: Reset Media Keys.
10/16/15 8:30:54.157 AM BeardedSpice[1758]: AppleEvents: Send port for process has no send right, port=( port:6255/0x186f rcv:1,send:0,d:0 limit:5) (findOrCreate()/AEMachUtils.cp #526) com.apple.main-thread
10/16/15 8:30:54.158 AM BeardedSpice[1758]: AppleEvents: Send port for process has no send right, port=( port:6255/0x186f rcv:1,send:0,d:0 limit:5) (findOrCreate()/AEMachUtils.cp #526) com.apple.main-thread
10/16/15 8:30:54.158 AM BeardedSpice[1758]: Play/pause pressed.

**Comment by bruisersmith** [comment]
Ok - did a bit more testing. Hype Machine works on Safari, and Soundcloud works on Chrome. May just be an issue only with Hype Machine on Chrome. 

BTW - I love BeardedSpice SO MUCH, and have been using it since about 0.9. It's killing me that it's not working in my particular browser/music sit combination, but it's all good and I know you guys work hard on it. Is there a donation link anywhere to support development?

**Comment by Stillness-2** [comment]
I mean that you can to get any beardedspice release by link: https://github.com/beardedspice/beardedspice/releases .
What version of the Chrome are you use? If you use 46 or above, read this  issues #244, #255.

**Comment by bruisersmith** [comment]
Yeah you're right - I'm on Chrome 46 as well (which would explain why downgrading didn't work). Sigh. 

Thanks for the Releases link - I had tried to downgrade to 1.1, 1.1.1, and 1.1.2 and was trying to find out if it was a Library/Preferences issue.

**Comment by flocsy** [comment]
I have the same problem. I almost reported that since I've upgraded to BS 1.2 it stopped working, but then I saw this issue. Though I still think it's related to BS 1.2, because I don't remember upgrading Chrome in the past days, but BS was upgraded.

**Comment by Stillness-2** [comment]
@flocsy, you may download previous version of the BeardedSpice from this link: https://github.com/beardedspice/beardedspice/releases :)

**Comment by tanzanyaliokkes** [comment]
I have the same problem when playing Youtube videos. The current video playing on Chrome is shown, however play/stop buttons does not work. I can use Safari just fine.

OS: OSX 10.10.2
BS: 1.2
Chrome: Version 46.0.2490.71 (64-bit)

**Comment by eexit** [comment]
Same issue: can't play/pause/next/prev on Hypem:

OSX: Version 10.10.5
Chrome: Version 46.0.2490.71 (64-bit)
BS: Version 46.0.2490.71 (64-bit)

Works with Safari. Hypem site shortcuts work tho... Maybe it's a mapping issue only related to Hypem/Chrome/BS.

**Comment by teototaro** [comment]
Same issue, can't play/pause/next/prev but the current video playing on Chrome is shown

Chrome: 46.0.2490.71 (64-bit)
OSX: 10.11
BS: 1.2 (12)

**Comment by idrozd** [comment]
Don't know if related – but latest BS with El Capitan with long uptime starts causing very disturbing problems:
Keyboard stops responding at all, gradually, BS icon in menu bar when hovered shows loader and respods to click with huge delay, 

Media keys react with great delay as well.

I also have installed better touch tools and Amethyst, maybe this have something to do with this.

After force quit BS, everything returns to normal, after system restart it works ok for few hours (?).

**Comment by joantune** [comment]
The same happens with me and Youtube. 
The console shows something very similar to what @bruisersmith posted

**Comment by tstackhouse** [comment]
Seeing this issue with Chrome 46/10.10.5 and Subsonic. Seeing similar message in the console as others have reported.  Sounds like an issue that could/should be raised with Chrome?

**Comment by Stillness-2** [comment]
People, this is common problem for all supported sites. Please, read comments in this #244 and this #255 issues. I offer to write here if you have solution. :)

**Comment by tstackhouse** [comment]
@Stillness-2 Did some quick research, seems it may have been a security change in Chromium, and is not an isolated issue.  That said, comment #12 offers a potential workaround here: https://code.google.com/p/chromium/issues/detail?id=543437

Relavant chromium commit is https://codereview.chromium.org/1268513002

**Comment by Stillness-2** [comment]
Test this build: 
https://www.dropbox.com/s/ubj1dzvqkwtneud/BeardedSpice.zip?dl=1

**Comment by bruisersmith** [comment]
Totally working for me at least on Hype Machine. You're amazing - thanks for the quick turnaround!

**Comment by kradam** [comment]
Working on YT, too. Thx!

**Comment by teototaro** [comment]
It works but, when the chrome window is minimized and is playing a youtube playlist, if I change the track (next or prev) or play/pause it, the browser window returns to expanded

**Comment by kradam** [comment]
I confirm this behaviour. Even when I press pause the windows is expanded. I used to minimize Chrome tab with YT player, so I have to go back to Safari untill fixed.

**Comment by Stillness-2** [comment]
:)

**Comment by Stillness-2** [comment]
Test this version:
https://www.dropbox.com/s/34xhwt67s8ii85c/NewBeardedSpice.zip?dl=1

**Comment by kradam** [comment]
This works OK, no expanding. Thx!
