### ISSUE TITLE
Can't find applicable tabs since version 1.2

### ISSUE THREAD

**Issue by semaperepelitsa** [beardedspice/beardedspice#260]
I have an issue after upgrading to the latest Beardspice (1.2). It sees no music apps/tabs, not even iTunes. I first noticed it in my pull request: https://github.com/beardedspice/beardedspice/pull/243. Now I see it in the release as well. The previous version (1.1.2) works fine. Here is my log:

```
22.10.15 13:28:00,106 BeardedSpice[24990]: Reset Mikeys
22.10.15 13:28:00,134 BeardedSpice[24990]: -[__NSCFString ddhid_unsignedIntForString:]: unrecognized selector sent to instance 0x7fa458f5f230
22.10.15 13:28:00,134 BeardedSpice[24990]: -[__NSCFString ddhid_unsignedIntForString:]: unrecognized selector sent to instance 0x7fa458f5f230
22.10.15 13:28:01,694 BeardedSpice[24990]: Refreshing tabs...
22.10.15 13:28:01,695 BeardedSpice[24990]: App com.google.Chrome is running <NSRunningApplication: 0x7fa458f114a0 (com.google.Chrome - 15383)>
22.10.15 13:28:01,705 BeardedSpice[24990]: App com.apple.Safari is running <NSRunningApplication: 0x7fa45a88dc20 (com.apple.Safari - 310)>
22.10.15 13:28:02,163 BeardedSpice[24990]: App com.google.Chrome is running <NSRunningApplication: 0x7fa458dd77c0 (com.google.Chrome - 15383)>
22.10.15 13:28:02,165 BeardedSpice[24990]: App com.apple.Safari is running <NSRunningApplication: 0x7fa458dd8380 (com.apple.Safari - 310)>
22.10.15 13:28:02,177 BeardedSpice[24990]: Reset Media Keys.
22.10.15 13:28:02,177 BeardedSpice[24990]: Reset Media Keys.
22.10.15 13:28:03,888 BeardedSpice[24990]: Refreshing tabs...
22.10.15 13:28:03,889 BeardedSpice[24990]: App com.google.Chrome is running <NSRunningApplication: 0x7fa45aa00790 (com.google.Chrome - 15383)>
22.10.15 13:28:03,891 BeardedSpice[24990]: App com.apple.Safari is running <NSRunningApplication: 0x7fa458cf1340 (com.apple.Safari - 310)>
22.10.15 13:28:03,938 BeardedSpice[24990]: App com.google.Chrome is running <NSRunningApplication: 0x7fa458fc19f0 (com.google.Chrome - 15383)>
22.10.15 13:28:03,940 BeardedSpice[24990]: App com.apple.Safari is running <NSRunningApplication: 0x7fa45a849010 (com.apple.Safari - 310)>
22.10.15 13:28:03,949 BeardedSpice[24990]: Reset Media Keys.
22.10.15 13:28:03,949 BeardedSpice[24990]: Reset Media Keys.
22.10.15 13:28:05,091 BeardedSpice[24990]: Bartender: Loaded BartenderHelperTwoTwo
22.10.15 13:28:05,972 BeardedSpice[24990]: Refreshing tabs...
22.10.15 13:28:05,973 BeardedSpice[24990]: App com.google.Chrome is running <NSRunningApplication: 0x7fa458fbe6d0 (com.google.Chrome - 15383)>
22.10.15 13:28:05,976 BeardedSpice[24990]: App com.apple.Safari is running <NSRunningApplication: 0x7fa458de2d60 (com.apple.Safari - 310)>
22.10.15 13:28:06,022 BeardedSpice[24990]: App com.google.Chrome is running <NSRunningApplication: 0x7fa458fbe880 (com.google.Chrome - 15383)>
22.10.15 13:28:06,024 BeardedSpice[24990]: App com.apple.Safari is running <NSRunningApplication: 0x7fa45a819800 (com.apple.Safari - 310)>
22.10.15 13:28:06,033 BeardedSpice[24990]: Reset Media Keys.
22.10.15 13:28:06,033 BeardedSpice[24990]: Reset Media Keys.
```

I'm on OS X 10.11.

**Comment by Stillness-2** [comment]
I think this happens because of:
22.10.15 13:28:00,134 BeardedSpice[24990]: -[__NSCFString ddhid_unsignedIntForString:]: unrecognized selector sent to instance 0x7fa458f5f230
22.10.15 13:28:00,134 BeardedSpice[24990]: -[__NSCFString ddhid_unsignedIntForString:]: unrecognized selector sent to instance 0x7fa458f5f230

Have you a HID devices, which plugged in Mac?

**Comment by semaperepelitsa** [comment]
Yes! Turns out to be a problem with my external mouse. Once I disconnect it and relaunch the app, everything is fine. The previous app version does not have this issue. Do you need some more info to fix this? Here is the device info from System Report:

```
Sensei Raw Gaming Mouse:

  Product ID:	0x1369
  Vendor ID:	0x1038
  Version:	1.14
  Speed:	Up to 12 Mb/sec
  Manufacturer:	SteelSeries
  Location ID:	0x14100000 / 23
  Current Available (mA):	1000
  Current Required (mA):	200
  Extra Operating Current (mA):	0
```

**Comment by Stillness-2** [comment]
Предыдущая версия вообще не содержала блока работы с hid устройствами, по этому и не было таких проблем. Как время будет подумаю над этой темой. :)

**Comment by yangzihe** [comment]
Is there a solution that doesn't require unplugging HID devices when opening the app?

**Comment by Stillness-2** [comment]
I found the app in DDHID library, which gives chance to collect info from HID device.
https://www.dropbox.com/s/g5gnjdi652zs233/HIDBrowser.zip?dl=1
Launch this, select your HID in the list of the devices. And export device properties through menu (File -> Export device properties)

**Comment by bcole808** [comment]
I have the same problem. These steps resolve the issue for me:

1. Quit Bearded Spice
2. un-plug my external USB keyboard and mouse
3. Launch Bearded Spice
4. Re-connect my USB devices

**Comment by Stillness-2** [comment]
@bcole808 @yangzihe @semaperepelitsa  Give me please your devices properties :)

**Comment by bcole808** [comment]
the HIDBrowser app you linked to crashes when I try to launch it. Is there another way I can get the device info?

**Comment by Stillness-2** [comment]
Try close BeardedSpice before launching HIDBrowser

**Comment by bcole808** [comment]
I restarted my computer. HIDBrowser is able to launch before I connect my USB devices, however after they have been connected at some point then HIDBrowser crashes on launch =(

These are the devices I am using:

http://www.amazon.com/gp/product/B00GU8W5AE
http://www.amazon.com/gp/product/B00JM61264

**Comment by Stillness-2** [comment]
check this debug build:
https://www.dropbox.com/s/ubj1dzvqkwtneud/BeardedSpice.zip?dl=1
Please send me a console output after app starting

**Comment by Jorl17** [comment]
Hi.

I have the same problem. Unplugging the mouse also helps it for me

Sadly, the debug build you just linked does not fix the issue for me. 1.1.2 also worked fine for me. This is a big show-stopper for me. If there's anything I can do to help, be sure to tell me!

**Comment by Stillness-2** [comment]
@Jorl17 I need in console log from you

**Comment by bcole808** [comment]
I tested the debug build you provided, here are my log files:

Log 1: (broken behavior) https://www.dropbox.com/s/m23hss50fkqvi4j/log_1.log?dl=0

Steps performed for log 1:

1. External keyboard and mouse are both connected
2. Launch Bearded Spice debug build
3. Open pandora tab in chrome
4. See that no active player is selected in bearded spice

Log 2: (working) https://www.dropbox.com/s/8rxmxd8wet7qe2e/log_2.log?dl=0

Steps performed for log 2:

1. No devices connected
2. Launch Bearded Spice debug build
3. Open pandora tab in chrome
4. See that everything works as expected, and the app can see pandora

**Comment by Stillness-2** [comment]
Try this new build when HID devices are connected:
https://www.dropbox.com/s/co6w1y3072bijoq/BeardedSpiceNew.zip?dl=1
And send me log.

**Comment by bcole808** [comment]
New build appears to work and fix the issue with two HID devices connected during app launch. 

Log: https://www.dropbox.com/s/lkr9bf6jl49y8t9/log_3.log?dl=0

**Comment by Stillness-2** [comment]
@bcole808 Are you have Apple headphones with mic? Can you check, that buttons on remote control work appropriately, when other HID devices connected?

**Comment by bcole808** [comment]
I tested with apple headphones (with the mic and volume controls). Everything seems to work:

1. Connect HID keyboard and mouse
2. Connect apple earbuds
3. Launch bearded spice (second debug build)
4. Open pandora
5. See that keyboard media keys are working correctly
6. Press middle button on headphones once - pandora is paused correctly
7. resume music then double press the middle button on headphones - next track plays on pandora correctly

**Comment by Stillness-2** [comment]
Give me a log please :)

**Comment by bcole808** [comment]
Here is the log from the most recent test with the apple headphones:

https://www.dropbox.com/s/3t3xnrb01e77j7o/log_4.log?dl=0

**Comment by Stillness-2** [comment]
Thanks :)
