### ISSUE TITLE
Ability to handle Webkit's "pinned" tabs.

### ISSUE THREAD

**Issue by JackoPlane** [beardedspice/beardedspice#266]
BeardedSpice doesn't appear to work at all if you have *any* pinned tabs

**Comment by Stillness-2** [comment]
If you say about Safari, i do not believe. :)

**Comment by Stillness-2** [comment]
Please, more details

**Comment by JackoPlane** [comment]
The `executeJavascript:` function fails when Safari/Webkit have pinned tabs, hence `tab.tag` always returns nil. Removing pinned tabs makes BeardedSpice detect playing audio again

**Comment by Stillness-2** [comment]
OS X version: ?
Safari version: ?
BeardedSpice version (current master or release version): ?
pinned site (url): ?

**Comment by JackoPlane** [comment]
OS X version: El Capitan 10.11.1 (15B42) 
Safari version: 9.0.1
BeardedSpice version (current master or release version): `master` forked with my changes for webkit  nightly support
pinned site (url): any url supported, soundcloud, youtube etc..

**Comment by Stillness-2** [comment]
Are you checked on the release version Safari, not on nightly build?

**Comment by JackoPlane** [comment]
Yes

**Comment by Stillness-2** [comment]
check on this build:
https://www.dropbox.com/s/co6w1y3072bijoq/BeardedSpiceNew.zip?dl=1

**Comment by JackoPlane** [comment]
That appears to work.

**Comment by Stillness-2** [comment]
Very strange. I think, that problem in the your build. I did not change sources, which provide this functionality.

**Comment by JackoPlane** [comment]
If you look at the diff of my build, nothing changed as part of the WebKit nightly support

**Comment by Stillness-2** [comment]
NSMutableSet *SafariTabKeys;

**Comment by Stillness-2** [comment]
```
       //checking, that tab wasn't included in status menu.
        //We need it because Safari "pinned" tabs duplicated on each window. (Safari 9)
        
        NSString *key = tab.key;
        if (![key isEqualToString:tab.key]) {
            //key was not assigned, we think this is fake pinned tab.
            return;
        }
        
        if (!SafariTabKeys) {
            SafariTabKeys = [NSMutableSet set];
        }
        if (key) {
            if ([SafariTabKeys containsObject:key]) {
                
                return;
            }
            [SafariTabKeys addObject:key];
        }
        //-------------------------------------------
```
