### ISSUE TITLE
Embedded YouTube videos aren't detected

### ISSUE THREAD

**Issue by 1-61803** [beardedspice/beardedspice#268]
For example
http://terrillthompson.com/tests/youtube.html
https://www.edx.org/course/philosophy-minds-machines-mitx-24-09x

**Comment by Stillness-2** [comment]
BeardedSpice can not do this

**Comment by 1-61803** [comment]
I'm curious. Is it so because it works based on the browser's url and not on whatever is streaming?

**Comment by 1-61803** [comment]
I'm curious. Is it so because it works based on the browser's url and not on whatever is streaming?

**Comment by Stillness-2** [comment]
yes
