### ISSUE TITLE
YoutubeStrategy broken on Chrome

### ISSUE THREAD

**Issue by godric7** [beardedspice/beardedspice#281]
Hi,

First, thanks you guys for that great app!

So BeardedSpice's YoutubeStrategy play/pause functionality stopped working a couple months ago,
I though it could be a El Capitan-update bug that would soon be patched. No patch came and I finally had enough free time to investigate the issue on my own:

Trying to play/pause a Youtube video in Chrome yields this error in the console
```
Uncaught TypeError: n.getPlayerState is not a function
```

It turns out Chrome's Applescript `do javascript` feature is now isolated from the page's javascript context, meaning that it does have access to the same DOM, but not to any javascript variables from the page's own scripts.
**Note**: Chromium and Chrome Canary are also affected, everything works fine in Safari.

I have no idea wether it's a new security policy from Chromium or a bug, but it might affect others strategies I don't use, I know Soundcloud works as it uses the html5 player native methods.

The Youtube Javascript API that's currently used has been [deprecated](https://developers.google.com/youtube/js_api_reference?hl=en) by Google anyway and has no replacement, I'll make a PR for a YoutubeStrategy that uses the native html5 controls later today.

**Comment by Stillness-2** [comment]
#257
