### ISSUE TITLE
[App Support] Amazon Music Germany/Austria

### ISSUE THREAD

**Issue by tuxfre** [beardedspice/beardedspice#286]
Dear beardedspice team,

I believe that a minor modification to AmazonMusicStrategy.m could allow you to control also the german/austrian cloud player.

Currently, the url you're looking for is *amazon.com/gp/dmusic/cloudplayer/* and the german/austrian is almost the same *amazon.de/gp/dmusic/cloudplayer/*. Judging from my quick inspection, the interface should be the same.

Not being a Cocoa dev I'm not equipped with the tools and knowledge to do this myself ... otherwise I'd have loved to contribute more.

Thanks for the great work!

**Comment by fmborghino** [comment]
tuxfre, I didn't find a good way to test the cloud player with a country domain (amazon keeps redirecting to my "home" amazon.com) - however I am fairly confident this will address your request - if not, I'll fix it :)
