### ISSUE TITLE
YouTube not working

### ISSUE THREAD

**Issue by CupOfTea696** [beardedspice/beardedspice#289]
Media controls for YouTube aren't working anymore for me.

OS X Yosemite, Google Chrome Version 47.0.2526.73 (64-bit)

**Comment by RichardBray** [comment]
Having the same issue.

**Comment by fmborghino** [comment]
Odd, works for me. Same Chrome (47.0.2526.73 (64-bit)), OS X El Cap (probably not the issue).

Curious, what's an example URL? I tested real quick against https://www.youtube.com/watch?v=IxuEtL7gxoM for example.

**Comment by CupOfTea696** [comment]
I just tried that url, still not working for me.

**Comment by RichardBray** [comment]
Nope didn't work for me either. Vimeo doesn't work either

Chrome 47.0.2526.73 (64-bit), El Cap 10.11.1

**Comment by Stillness-2** [comment]
What version of the BeardedScipe do you use?

**Comment by RichardBray** [comment]
@Stillness-2  1.2.1

**Comment by Stillness-2** [comment]
Chrome > 46 is supported from 1.2.2 version of the BeardedSpice

**Comment by RichardBray** [comment]
Can't find v1.2.2,  has it been released?

**Comment by Stillness-2** [comment]
no

**Comment by fmborghino** [comment]
That explains it, I build from source.

**Comment by CupOfTea696** [comment]
But it was working with SoundCloud for me, even though I was on Chrome > 46

**Comment by Stillness-2** [comment]
#257
