### ISSUE TITLE
Hide dock item

### ISSUE THREAD

**Issue by frdmn** [beardedspice/beardedspice#292]
Usually when there is an option for a menu bar icon, I don't need the Dock icon at all.

Any plans to hide that?

**Comment by Stillness-2** [comment]
Standard UI must hide when last BeardedSpice window is closed. 
http://www.youtube.com/watch?v=hTMEsMp7MsQ

**Comment by frdmn** [comment]
@Stillness-2 Totally right! I already wondered since I thought this was already implemented. Couldn't find the option in the preferences, thats why I raised an new issue.

Thanks for quick reply and demonstration :+1:
