### ISSUE TITLE
Overcast playback control not working

### ISSUE THREAD

**Issue by loganrockmore** [beardedspice/beardedspice#293]
Overcast playback control has recently stopped working for me. The tab within Google Chrome shows up in the BeardedSpice menu, but selecting it will not check it as the active playback source and so no media key functionality ends up working. I'm using BeardedSpice v1.2.2 on OS X El Capitan v10.11.1.

**Comment by nelox** [comment]
I can confirm the same issue using:
* Beardedspice 1.2.2
* Chrome 47.0.2526.80 (64-bit)
* OS X Yosemite 10.10.5 (14F1505)

**Comment by fmborghino** [comment]
@Stillness-2 I think maybe whatever broke Chrome 46 has been reverted. I was able to get this working with Chrome 47 by limiting that workaround to only v 46. Just throwing this out there for those that understand that fix better. Tentative change:

```
diff --git a/BeardedSpice/Tabs/ChromeTabAdapter.m b/BeardedSpice/Tabs/ChromeTabAdapter.m
index 6fb03aa..1b11973 100644
--- a/BeardedSpice/Tabs/ChromeTabAdapter.m
+++ b/BeardedSpice/Tabs/ChromeTabAdapter.m
@@ -29,7 +29,7 @@
     out.applescriptIsolatedVersion = NO;
     NSInteger version = [[(ChromeApplication *)application.sbApplication version] integerValue];
     NSArray *googleBundleIds = @[APPID_CANARY, APPID_CHROME, APPID_CHROMIUM];
-    if (version > 45 && [googleBundleIds containsObject:application.bundleIdentifier]){
+    if (version == 46 && [googleBundleIds containsObject:application.bundleIdentifier]){
         out.applescriptIsolatedVersion = YES;
     }
```

**Comment by Stillness-2** [comment]
@fmborghino No, this is another problem :) 
On my environment all works fine:
BS 1.2.2 (14)
GH 47.0.2526.80 (64-bit)
OSX 10.11.1 (15B42)

**Comment by fmborghino** [comment]
Ah ok! Meantime I updated the missing API bits in the strategy #295 ... not going to merge that just yet in case there's some impact on this issue.
