### ISSUE TITLE
domain expired

### ISSUE THREAD

**Issue by FernandoMiguel** [beardedspice/beardedspice#300]
beardedspice.com
Registrar Registration Expiration Date: 2015-12-16T17:06:54.00Z

**Comment by scotu** [comment]
Came here to say the same thing

**Comment by Stillness-2** [comment]
Unfortunately, i don't own this domain. Others keep silent :)

**Comment by EdenSG** [comment]
Can you just use Github Pages?

**Comment by akgerber** [comment]
Would it make sense to remove the domain link from the project description then?
![image](https://cloud.githubusercontent.com/assets/201313/12586669/3348631a-c41f-11e5-8e2b-af587483540b.png)

**Comment by Stillness-2** [comment]
Ok. Site moved to http://beardedspice.github.io temporarily.
