### ISSUE TITLE
BeardedSpice 1.2.x crashes in 10.8.5

### ISSUE THREAD

**Issue by 1-61803** [beardedspice/beardedspice#301]
AFAIK it happens when iTunes (11.4) is playing a track and I pause it. I attach the crash report.
[BeardedSpice_2015-12-18-221642.txt](https://github.com/beardedspice/beardedspice/files/67224/BeardedSpice_2015-12-18-221642.txt)

**Comment by Stillness-2** [comment]
Please update iTunes to latest version, or download it from http://www.apple.com/itunes/download/

**Comment by 1-61803** [comment]
I won't upgrade to iTunes 12. Is it fixed in 1.2.3?

**Comment by Stillness-2** [comment]
>Is it fixed in 1.2.3?

I think, yes.

Requirements for iTunes

<img width="314" alt="strange" src="https://cloud.githubusercontent.com/assets/12689/11918266/c566e732-a73a-11e5-9ac9-cf764641e797.png">

**Comment by 1-61803** [comment]
1.2.3 doesn't crash, but doesn't work as expected either.

I play a song in YouTube, then pause. I open iTunes, play and pause a track. I change focus back to YouTube with the menu bar item and try to play that song again, no dice. I see the notification but it doesn't actually play. Here's the log.

	20.12.15 3:23:53.928 PM BeardedSpice[9560]: Refreshing tabs...
	20.12.15 3:23:53.930 PM BeardedSpice[9560]: App com.apple.Safari is running <NSRunningApplication: 0x7f9d8ac647d0 (com.apple.Safari - 33290)>
	20.12.15 3:23:53.949 PM BeardedSpice[9560]: App com.apple.iTunes is running <NSRunningApplication: 0x7f9d8ae5c260 (com.apple.iTunes - 12290)>
	20.12.15 3:23:53.985 PM Safari[33290]: An exception was thrown during execution of an NSScriptCommand...
	20.12.15 3:23:53.985 PM Safari[33290]: [<NSWindow 0x7fa8af518d70> valueForUndefinedKey:]: this class is not key value coding-compliant for the key orderedTabViewItems.
	20.12.15 3:23:53.986 PM Safari[33290]: An exception was thrown during execution of an NSScriptCommand...
	20.12.15 3:23:53.986 PM Safari[33290]: [<NSWindow 0x7fa8afe9d0f0> valueForUndefinedKey:]: this class is not key value coding-compliant for the key orderedTabViewItems.
	20.12.15 3:23:53.988 PM BeardedSpice[9560]: Reset Media Keys.
	20.12.15 3:23:55.796 PM BeardedSpice[9560]: Active tab set to <SafariTabAdapter: 0x7f9d8ac510f0>
	20.12.15 3:23:57.730 PM BeardedSpice[9560]: Refreshing tabs...
	20.12.15 3:23:57.731 PM BeardedSpice[9560]: App com.apple.Safari is running <NSRunningApplication: 0x7f9d8aad17a0 (com.apple.Safari - 33290)>
	20.12.15 3:23:57.750 PM BeardedSpice[9560]: App com.apple.iTunes is running <NSRunningApplication: 0x7f9d8b9627a0 (com.apple.iTunes - 12290)>
	20.12.15 3:23:57.792 PM Safari[33290]: An exception was thrown during execution of an NSScriptCommand...
	20.12.15 3:23:57.792 PM Safari[33290]: [<NSWindow 0x7fa8af518d70> valueForUndefinedKey:]: this class is not key value coding-compliant for the key orderedTabViewItems.
	20.12.15 3:23:57.793 PM Safari[33290]: An exception was thrown during execution of an NSScriptCommand...
	20.12.15 3:23:57.793 PM Safari[33290]: [<NSWindow 0x7fa8afe9d0f0> valueForUndefinedKey:]: this class is not key value coding-compliant for the key orderedTabViewItems.
	20.12.15 3:23:57.795 PM BeardedSpice[9560]: Reset Media Keys.
	20.12.15 3:23:57.797 PM BeardedSpice[9560]: Play/pause pressed.
	20.12.15 3:23:57.799 PM BeardedSpice[9560]: Show Notification: <Track: 0x7f9d8ae5c170>
