### ISSUE TITLE
Play/Pause Headphone Control not working in El Capitan, BeardedSpice 1.2.3

### ISSUE THREAD

**Issue by mliq** [beardedspice/beardedspice#306]
Thanks so much for this great app. It works great with Spotify and the MacBook Pro keyboard controls. 

My issue is that I am using Sony Sony XBA-C10IP earphones / earbuds, which have a 3 button control similar to Apple earbuds. The volume buttons work, but play/pause does not. It does work fine on an iPhone.

**Comment by Stillness-2** [comment]
Please use this debug version https://www.dropbox.com/s/ubj1dzvqkwtneud/BeardedSpice.zip?dl=1
Open the Console.app
Open BeardedSpice debug version
Press the buttons on remote control
And send me output of the BeardedSpice, which appear in Console.app

**Comment by lianju** [comment]
07.01.16 17:25:36,304 BeardedSpice[2816]: Apple Mikey keypress detected: 137
07.01.16 17:25:36,304 BeardedSpice[2816]: Refreshing tabs...
07.01.16 17:25:36,307 BeardedSpice[2816]: App com.apple.Safari is running <NSRunningApplication: 0x7fd0da40c8f0 (com.apple.Safari - 413)>
07.01.16 17:25:36,321 BeardedSpice[2816]: App com.apple.iTunes is running <NSRunningApplication: 0x7fd0df0084f0 (com.apple.iTunes - 2823)>
07.01.16 17:25:36,792 BeardedSpice[2816]: Active tab set to <SafariTabAdapter: 0x7fd0da4275a0>
07.01.16 17:25:36,792 BeardedSpice[2816]: Reset Media Keys.

**Comment by buffaloseven** [comment]
I have a similar problem running the latest release of BeardedSpice & using both iPhone earbuds as well as my Klipsch S4i earbuds.  It seems to "double" the input resulting in a brief pause and then resuming the media.

**Comment by Stillness-2** [comment]
Please check this debug build: https://www.dropbox.com/s/ubj1dzvqkwtneud/BeardedSpice.zip?dl=1

**Comment by Stillness-2** [comment]
somebody respond :)

**Comment by buffaloseven** [comment]
Just got a chance to give it a test; the debug build seems to have fixed the problem.  I'll post back if it crops up again after giving it a bit more time and use :-)

**Comment by iamcodemaker** [comment]
Similar to #9

**Comment by kriskhaira** [comment]
I'm having this issue with BeardedSpice 2.2.3, Jabra Active Elite 65t and YouTube Music.
