### ISSUE TITLE
Unresponsiveness after some time without interaction on Spotify Client

### ISSUE THREAD

**Issue by isn0gud** [beardedspice/beardedspice#308]
BeardedSpice gets unresponsive after some time without interaction. When I just let some music play for some time the media keys get unresponsive, that means they don't work or it takes some time till BeardedSpice wakes up. It is the same with the menu bar icon and the menu, after some time it takes ~10 sec till the menu opens (loading/beachball mouse cursor). After waking BeardedSpice with a click on the menu icon it works again.

BeardedSpice v1.2.3
osx: El Capitan

Please let me know how I can provide some more debug information.

**Comment by 1ps0** [comment]
How many tabs do you have open? I tend to have over 20 open at any given time. I put in a optimization for this a while ago, I may need to revisit it.

**Comment by isn0gud** [comment]
None which are shown in BeardedSpice or in Chrome and 2 in Firefox, for BeardedSpice just the Spotify Client shows as open.

**Comment by isn0gud** [comment]
I activated 'Use Apple Remote for control playback' in the preferences which seems to solve the problem.
