### ISSUE TITLE
Not working with Spotify Web Player

### ISSUE THREAD

**Issue by stuebz88** [beardedspice/beardedspice#312]
I'm not sure if I'm doing something wrong, but I can't get Beardedspice to work with the Spotify Web Player when it seems to work fine with other sites such as Youtube. I'm using the latest version of El Capitan (OS X) and have tried with both Safari and Chrome. When I hit Cmd+F11, the window pops up that is supposed to show the current track but it just says "No track info available". I'm not able to pause, skip forward, or skip back.

**Comment by DevJackSmith** [comment]
same here, can't play/pause, and get no track info available. but Cmd+F6 works for showing the player window/tab

**Comment by stuebz88** [comment]
Someone posted an alternate version of Beardedspice on Issue #248 and there is a branch that fixes the issue (pull request #200) but I can't figure out how to download it.

**Comment by DevJackSmith** [comment]
Any chance a dev can take a look at this please? maybe give us a temp build while we are waiting to see if this is fixed in the next release or not? Please?

**Comment by Stillness-2** [comment]
http://beardedspice.github.io
Please check this release: https://raw.github.com/beardedspice/beardedspice/distr/publish/releases/BeardedSpice-latest.zip

**Comment by DevJackSmith** [comment]
checked, doesn't work. Same results as in my comment above: https://github.com/beardedspice/beardedspice/issues/312#issuecomment-170702060

OS X El Capitan 10.11.3
Chrome 48.0.2564.109 (64-bit)

**Comment by Coder-256** [comment]
@DevJackSmith @stuebz88 It might help if you post any new messages that appear in the Web Developer console once you press the play/pause, skip, and rewind buttons. You can see the console on most browsers by pressing command + option + i and switching to the console tab.

**Comment by DevJackSmith** [comment]
@Coder-256 here is what I get:
The first 4 errors and a warning show up when I just load the spotify webplayer page.
The next 2 errors show up when I push command+F6.
The next 2 errors show up when I push command+F11.
The next 2 errors show up when I press play:
"Uncaught TypeError: Cannot read property 'contentWindow' of undefined"
and "Uncaught SyntaxError: Unexpected end of input".
command+F8 produces no errors.
![screen shot 2016-02-15 at 7 33 25 am](https://cloud.githubusercontent.com/assets/8228441/13051434/7f738bf6-d3b6-11e5-9a44-043619fd3392.png)

**Comment by DevJackSmith** [comment]
I think this is solved in new https://raw.github.com/beardedspice/beardedspice/distr/publish/releases/BeardedSpice-latest.zip
Just tried today, play pause works 👍

**Comment by AAverin** [comment]
I'm on latest release now, and Spotify Web Player support is very buggy.
It works only when window is already active.
If it's inactive there is a delay of few seconds.
Also, if I play and stop via BeardedSpice, Spotify Web gets buggy – audio is playing, but buttons and track preview in the top-right corner are broken somehow and unresponsive. If you start and stop playback after that it seems to fix the issue.
And track info is never working with Spotify Web

**Comment by stuebz88** [comment]
This has been working for me for some time. One of the new releases since when I first posted this fixed it. Sorry for not checking back.

**Comment by xuopled** [comment]
Hi, I get the same error with `BeardedSpice 2.2.3` and `Google Chrome Version 62.0.3202.62 (Official Build) (64-bit)` on `MacOs Sierra 10.12.6`. Should I open a new issue ?

**Comment by 1ps0** [comment]
Does it work with `BeardedSpice 2.2.2`? Because thats probably the current workaround.

**Comment by xuopled** [comment]
Yes it work with 2.2.2 ! I use brew to install `BeardedSpice`. Is it possible for you to add the version `2.2.2` to `homebrew/versions` ?

Thank you very much

**Comment by 1ps0** [comment]
@xuopled I'll see what I can do. TBH I've never tried adding the app to homebrew before. This should be interesting.

**Comment by xuopled** [comment]
Thank you very much 🤓

**Comment by xuopled** [comment]
@1ps0 I dan't find the beardedspice brew. Did you give up add it ?

**Comment by 1ps0** [comment]
Nope just time constraints. So much to do and I have maybe 1% of free time to work on stuff here.

**Comment by xuopled** [comment]
Ok no problem. You have to add it to [brew-cask](https://caskroom.github.io/) Because beardedspice is an application. See [here](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md)
To add both 2.2.2 and 2.2.3, you need to see [this](https://docs.brew.sh/Versions.html)

Good luck with this. Thank you very much for your help

**Comment by nzcoops** [comment]
Mac 10.14.6
Chrome Version 78.0.3904.108 (Official Build) (64-bit)
BS 2.2.3

BS will pick up youtube in a tab, but not open.spotify or google play music. Any solutions? Possibly an extension I have causing issues? I tried in incognito but no luck there either.
