### ISSUE TITLE
Pandora Play/Pause/Skip only works when tab in foreground

### ISSUE THREAD

**Issue by rudmer90** [beardedspice/beardedspice#323]
I've only noticed this bug recently, after the update to version 1.2.3:  when BS is controlling a Pandora tab (Google Chrome on Yosemite), my media hotkeys only work when the tab is in the foreground.  If I hit play/pause/skip on a tab that isn't selected, that action completes only after I click on the tab.

**Comment by Stillness-2** [comment]
Please, check on youtube, for example. Does problem occur on it?

**Comment by chrishough** [comment]
I have the same problem, and it's only Pandora.  The Play/Pause now tries to fade out and it never actually stops it.

**Comment by rudmer90** [comment]
Pandora is pretty much all I use, but I tested it on Youtube and the bug does not reproduce.  Everything works just fine with Youtube.  Seems to be a Pandora-specific issue.

**Comment by RyanDurbin** [comment]
I can see the same fade out/in issue on Pandora until I click on the Pandora tab

**Comment by samueldana** [comment]
I have the same issue (Google Chrome/Safari on Yosemite). 

I believe Pandora recently updated its web player to do the "fade on pause" thing. It was previously instant.

When the Pandora tab is in the foreground, it fades quickly. In the background, it takes my system about 30 seconds to fully pause.

**Comment by chrishough** [comment]
It also happens if you are using spaces and on a different osx space..  Is there a way to fix this?

**Comment by rudmer90** [comment]
Hmmmm, this bug has disappeared for me.  Perhaps Pandora fixed a bug that they previously introduced?

**Comment by chrishough** [comment]
Yep, after updating chrome today it looks like it disappeared on its own for me too.

**Comment by samueldana** [comment]
The issue is gone for me as well.

Pandora is no longer fading on pause, so the issue is likely resolved unless they bring it back.
