### ISSUE TITLE
Feature Request: Support for bluetooth headsets

### ISSUE THREAD

**Issue by trhodeos** [beardedspice/beardedspice#33]
Add support to control play/pause/forward/back with bluetooth headsets (see: issue #9).

**Comment by m-baumgartner** [comment]
Yes to this! If someone's getting into this, don't forget Parrot Zik BT headset ;).

**Comment by semiosis** [comment]
I just installed BTHSControl and now my bluetooth headset controls work!  This is awesome!

https://github.com/JamesFator/BTHSControl

**Comment by rguldener** [comment]
According to the BTHSControl it should now (OS X 10.10 and up) be possible to integrate this without any interceptor. Any plans to include this into bearded spice?

**Comment by phcorp** [comment]
👍

**Comment by wmertens** [comment]
Just commenting to point out that the BTHSControl project doesn't work on Sierra: https://github.com/JamesFator/BTHSControl/issues/12

**Comment by 1ps0** [comment]
Gonna link this ticket to #9 and close out this one. Please continue your discussions there.

**Comment by gil** [comment]
Try this alternative to BTHSControl. The beta version is working here for Sierra -> https://github.com/jguice/mac-bt-headset-fix#beta-version
