### ISSUE TITLE
Headphone button launches iTunes

### ISSUE THREAD

**Issue by kassim** [beardedspice/beardedspice#330]
So the headphone button works as intended (play/pause of current audio source) but it also launches iTunes. The keyboard media play/pause button works fine (play/pause without launching iTunes).

Headphone model AKG K451 - I wouldn't assume its a model-specific issue though.

**Comment by Coder-256** [comment]
I have heard of other people having this problem, too. I have never had it myself, but I know what might work. Try this command: `launchctl unload -w /System/Library/LaunchAgents/com.apple.rcd.plist`

It will disable the Remote Control Daemon. The only side effect should be that Apple TV (_not_ Siri) remotes will no longer work. Post back with results.

**Comment by kassim** [comment]
That disables the headphone button altogether

**Comment by Coder-256** [comment]
I'm glad it worked. For any future readers, another possible solution if the command doesn't work is to run it again with `load` instead of `unload` and install https://github.com/jguice/mac-bt-headset-fix.

**Comment by Coder-256** [comment]
@kassim You should close the issue if it works now.

**Comment by kassim** [comment]
just noting a side effect I discovered of the first fix was that it meant bluetooth controls stopped working for iTunes (such as my Fugoo speaker controls)
