### ISSUE TITLE
App Hangs on Launch

### ISSUE THREAD

**Issue by matthewdias** [beardedspice/beardedspice#331]
I recently updated the app after not having launched it in awhile. It worked fine for a few minutes. Later, after opening it again, the app now always hangs on launch, and bugs out the keyboard so that many apps can't accept text input until I force quit BeardedSpice.

**Comment by sengeezer** [comment]
I just did a fresh install and I'm facing the same issue.

**Comment by matthewdias** [comment]
A restart seemed to fix the issue for me.

**Comment by clayzermk1** [comment]
Seeing this as well from time to time.
A restart will fix it temporarily, but after some time (days?) it seems to reappear.
I tend to put my laptop to sleep often and rarely reboot.
Reinstalling the application seems to make no difference. It will just hang on launch.

OS X 10.9.5 (13F1603)
beardedspice 1.2.3

**Comment by jl982** [comment]
Not sure if this is related, but the app would also hang for me immediately on launch, often taking keyboard input with it. The problem seemed to go away after I commented out the code in the `accepts` method in `PlexWebStrategy.m`, and made it always return `NO`.

**Comment by jl982** [comment]
Not sure if this is related, but the app would also hang for me immediately on launch, often taking keyboard input with it. The problem seemed to go away after I commented out the code in the `accepts` method in `PlexWebStrategy.m`, and made it always return `NO`.

**Comment by clayzermk1** [comment]
> often taking keyboard input with it
Same here.

Thanks for the workaround, I'll see if I can make a build for myself as well.

**Comment by clayzermk1** [comment]
Quit beardedspice using Activity Monitor.
Slept computer.
Woke computer.
Updated Chrome to 48.0.2564.109 (was 48 before as well). Update required a Chrome restart.
Launched beardedspice. Waited ~30sec and watched in Activity Monitor. Working for the moment.

My guess is the Chrome restart helped.

**Comment by mutantcornholio** [comment]
If you shut down you browser, beardedspice starts normally. But is hangs exactly same way when you start your browser

**Comment by Stillness-2** [comment]
Does problem occur when you use Google Chrome only?

**Comment by mutantcornholio** [comment]
It's a different chromium-based browser.
I can't say for sure if this problem is browser-specific until the time I will locate exact site or extension that causes it. 
I've managed to make Beardedspice work for now. Next time it will hang, I'll do more research.

**Comment by clayzermk1** [comment]
@Stillness-2 I am only using Google Chrome.

Chrome extensions:
Adblock Plus 1.10.1
Advanced REST client 4.12.2-stable.0
ColorZilla 0.5.6
Google Docs 0.9
Google Docs Offline 1.1
Google Hangouts 2015.1204.418.1
HTTPS Everywhere 2015.12.16
JSONView 0.0.32.2
LastPass: Free Password Manager 4.0.7
Smile Always 0.90

@mutantcornholio any commonalities?

**Comment by Stillness-2** [comment]
Check this debug build% https://www.dropbox.com/s/ubj1dzvqkwtneud/BeardedSpice.zip?dl=1

**Comment by Stillness-2** [comment]
somebody respond :)

**Comment by mutantcornholio** [comment]
Seems like this new build got it fixed.

**Comment by mutantcornholio** [comment]
OR NOT :D 
It just hanged again. I have no idea, what caused it, but unlike older builds, restarting beardedspice helped. 
So it could be some other problem.

I had an idea in mind. I have a lot of tabs opened and some of them still might be not loaded, because I haven't clicked on them since last browser restart. I think that each time I managed to reproduce the problem, I had some of those. 

I can't remember if the bug was consistently reproducing with old build, but it's not reproducing with new one. Sooo, I'm still not sure about this.

**Comment by Stillness-2** [comment]
@mutantcornholio When you downloaded debug build? 
I changed it 11 hours ago. :)

**Comment by mutantcornholio** [comment]
I've downloaded it when you've posted the comment with it in the first place. (seems like 17 days ago)

**Comment by Stillness-2** [comment]
nononono :) download it again :)

**Comment by mutantcornholio** [comment]
Done.
Seem to work, like older build did too.
