### ISSUE TITLE
Focus the currently playing tab when clicking on notification

### ISSUE THREAD

**Issue by oNaiPs** [beardedspice/beardedspice#342]
It would be great to focus the playing tab when we click in the notifications that are showing up.

**Comment by Stillness-2** [comment]
nonono

**Comment by Stillness-2** [comment]
you may use shortcut for this

**Comment by oNaiPs** [comment]
I understand, but usually clicking on a notification or on "show" is the default behavior in most of music apps. I guess it would make sense to have it. As a matter of fact, the default action to clear the notification is to swipe it to the right rather than clicking it.

**Comment by AnthonyWhitakerJr** [comment]
Just noticed this issue matches #531. Fix uploaded in #533.
