### ISSUE TITLE
We need to separate keyboard shortcuts, apple remote control and so on into XPC service.

### ISSUE THREAD

**Issue by Stillness-2** [beardedspice/beardedspice#354]
Because IOKit, for example, can lead to crash of the app.

**Comment by Stillness-2** [comment]
For testing:
[BeardedSpice.zip](https://github.com/beardedspice/beardedspice/files/170466/BeardedSpice.zip)

@foozee @fmborghino @Coder-256 Unfortunately now we need serious testing :) 

@1ps0 Didn't want to disappoint you, but in this commit (6a23679) many changes, that may affect on your PR.

**Comment by fmborghino** [comment]
So far so good. Any areas you think need more focus testing? I'm just running it on my (few) usual sites.

**Comment by fmborghino** [comment]
@Stillness-2 So far the regular media keys work for me (play, next). But the custom keys (show track info, favorite, next, etc) don't work at all. For example I use show track info a lot (alt-shift-cmd-T) - doesn't work at the moment.

Also, and I think this is not related: The checkmark in the menu is really flicker-ey - it comes and goes a lot. It used to be pretty solid. I think this is an unrelated regression, but I'm not sure, I mention it here just in case. If you think it's unrelated, I'll make an issue so we can look into it later.

Let me know what info I can provide to help here, else I'll just keep using the current master build and look for issues. I'll try the Apple Remote later today too.

**Comment by Stillness-2** [comment]
is this window appears when you launch BeardedSpice?
https://www.dropbox.com/s/85bmx5w6dyoe2d2/Screenshot%202016-03-15%2012.43.02.png?dl=0

What about this screen https://www.dropbox.com/s/knufp6s9yg5e386/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202016-03-15%2012.35.04.png?dl=0
Have the BeardedSpice  check mark or not?

**Comment by Stillness-2** [comment]
Also if you launch BeardedSpice from Xcode, you must tick off in "Accessibility" panel for Xcode

**Comment by fmborghino** [comment]
Yep I have both BS and Xcode in Security+Privacy > Privacy > Accessibility list, and both checked. The prompts came up for each one just fine (running from your test build, and from code directly). If I go back to the 'latest' release build it works ok. If I use the build here or build from master, the keys don't work for me. Can I trace something to debug this?

**Comment by Stillness-2** [comment]
@fmborghino  I created branch for testing - xpcservice_test.

**Comment by fmborghino** [comment]
@Stillness-2 well, it's all working for me now. I have no idea what was up. I had other funky things happening which culminated in a reboot. Now it's good. :+1:
