### ISSUE TITLE
[App Support] Downcast

### ISSUE THREAD

**Issue by filnko** [beardedspice/beardedspice#355]
That would be really nice! Sadly there's no information on how to create a MediaStategy for native apps.

**Comment by Coder-256** [comment]
[Now there is!](https://github.com/beardedspice/beardedspice/wiki/Native-App-Developers'-Guide)

**Comment by fmborghino** [comment]
@Coder-256 this is really nice! Thanks.

I don't know much about scripting support, but it seems not all apps include this. One example player is SomaFM.app.

Is it worth adding a 3.1 item saying that if you see something like the following, you are out of luck? ...

```
$ sdef /Applications/SomaFM.app/ | sdp -fh --basename SomaFM
sdef: couldn't get sdef for /Applications/SomaFM.app/ (error -192)
sdp: stdin - zero length data
```

Not sure this is worth adding to the wiki, perhaps it's too obvious. Just an observation.

Thanks again. I think I'll see about adding VLC as an exercise!

**Comment by Coder-256** [comment]
Yeah, you could add that. If that is the output, then that application is not scriptable. See this: <https://developer.apple.com/library/mac/documentation/AppleScript/Conceptual/AppleScriptX/Concepts/scriptable_apps.html>

**Comment by fmborghino** [comment]
Done. Thanks for the pointers.

**Comment by Coder-256** [comment]
@filnko Could you run the following commands and post the output of the commands and the resulting file (Downcast.h) from your Downloads folder (if it exists)?:

```
cd ~/Downloads
sdef /Applications/Downcast.app | sdp -fh --basename Downcast
```

I would do it myself, but I do not have Downcast and do not want to buy it.

**Comment by filnko** [comment]
sdef: couldn't get sdef for /Applications/Downcast.app (error -192)

**Comment by Travmatth** [comment]
I emailed Downcast today and mentioned this issue, if they reply I will update.

**Comment by gcox** [comment]
I'll be looking into adding support for this in [Downcast](http://downcast.fm) soon. Thanks for making me aware of it, @Travmatth.

**Comment by 1ps0** [comment]
This will be live next release. Until then feel free to build locally.
