### ISSUE TITLE
Tidal Mac

### ISSUE THREAD

**Issue by hayespotter** [beardedspice/beardedspice#367]
Any plans for Tidal app integration? May whip out my amateur obj-c skills for this one if not.

**Comment by lukka5** [comment]
It seems that Tidal app has already media keys integrations. But they don't work when I have BeardedSpice opened. :(

**Comment by RyanBreaker** [comment]
I was wondering why I couldn't get my media keys to work in the app, Bearded Spice blocks them for it. Yeah support should be added for this app as well so it doesn't block it like it does.

**Comment by Stillness-2** [comment]
About Tidal app. We can't integrate this app, because app don't have of the applescript interface at this moment.

**Comment by Stillness-2** [comment]
Check this build https://www.dropbox.com/s/ubj1dzvqkwtneud/BeardedSpice.zip?dl=1 please.

**Comment by lukka5** [comment]
Seems to work if Tidal app is opened after BeardedSpice or if you press pause and then play on Tidal app once BeardedSpice has opened.

**Comment by Stillness-2** [comment]
This is maximum what i can do for now. This changes will be in next release.

**Comment by lukka5** [comment]
No, it's great! Thank you! 😄

**Comment by neonbaer** [comment]
Hey there,

will there be a full support for the Tidal App at one point?
