### ISSUE TITLE
Yandex Radio is not switching to next track

### ISSUE THREAD

**Issue by MerliX** [beardedspice/beardedspice#369]
"Play/Pause" key works, but "Next" key does nothing

**Comment by Stillness-2** [comment]
You may update BeardedSpice or check latest release https://raw.github.com/beardedspice/beardedspice/distr/publish/releases/BeardedSpice-latest.zip
May be it is fixes the problem

**Comment by MerliX** [comment]
Everything is working for me now, thanks!
