### ISSUE TITLE
Not working on 10.9.5 Mavericks with ver.1.2.4

### ISSUE THREAD

**Issue by Johannes-Esseling** [beardedspice/beardedspice#371]
Hey guys,

I just updated to the newest version of the application (1.2.4), and now my global shortcuts I set and the Default Mac Media Keys don't work anymore. I mostly use Beardedspice with SoundCloud and the VOX Media Player. 
I have a shortcut for play/pause on CTRL + Space. I don't think that's the reason it doesn't work anymore, since the MAC Media Keys don't work either, but who knows.

I am using a MacBook Pro with Mavericks (10.9.5) installed. 

Greetings Mick Jogger

**Comment by alastor0325** [comment]
Same, I can't use Beardedspice to control Spotify on osx 10.9.5.

**Comment by Coder-256** [comment]
@Johannes-Esseling @alastor0325

Quit BeardedSpice, open `/Applications/Utilities/Console.app`, then relaunch. Post the output. Execute some shortcuts and post the output after that.

**Comment by alastor0325** [comment]
I uploaded the log [1] here, thanks!

[1] https://goo.gl/NjBjun

**Comment by Stillness-2** [comment]
Черт побери... :(

**Comment by Coder-256** [comment]
That doesn't look good... @Stillness-2 Do you have debug symbols?

**Comment by Stillness-2** [comment]
@alastor0325 Check this build:

**Comment by Stillness-2** [comment]
@Johannes-Esseling Look at previous comment. :)

**Comment by Johannes-Esseling** [comment]
@Stillness-2  Sorry for the late reply. I checked out the build you posted: Now everything works properly again. 

While on topic: I use Beardedspice pretty much every time I'm using my Mac, so when features break, I naturally switch to an older version. 
The problem with that is that is that you can't disable auto-updating so once you quit BeardedSpice the new version will be updated.
I could imagine that not everyone needs to have the bleeding-edge version of the app so I would appreciate a small checkbox that would allow to disable the Auto-Update.
