### ISSUE TITLE
Udemy pushed new ui

### ISSUE THREAD

**Issue by donsalari** [beardedspice/beardedspice#372]
With udemy's recently updates, beardedspice is unable to control the video.

**Comment by danielehrlich** [comment]
To get around this (on Mac OSX), you can install the [BetterTouchTool](https://www.boastr.net/). It used to be free, but now it's like $5 (45 day free trial). I created a keyboard shortcut that when I press it in whatever app I'm focused on, it opens up Google Chrome and hits the "space" key, thus pausing or playing Udemy (and it returns the focus back to my original app). Only thing is you have to be on the Udemy Tab in Chrome (although there are more complicated ways around this).

Open up BTT, go to "keyboard", and then make a new shortcut. Look for `Trigger Predefined Action>>>Controlling Other Applications>>>Send Shortcut to Specific App`. From there select Google Chrome and then record your shortcut to call the space key and you should be good.

**Comment by 1ps0** [comment]
Looks to be fixed.
