### ISSUE TITLE
new.vk.com – new UI of VK strategy

### ISSUE THREAD

**Issue by idrozd** [beardedspice/beardedspice#374]
Doesn't work with it, yep

![image](https://cloud.githubusercontent.com/assets/870478/14283646/ccdadd78-fb4c-11e5-9af9-39c38966413d.png)

**Comment by rzhikharevich** [comment]
Some research on how to implement the required functionality to support the new interface.

`function isPlaying() {
   var play = document.getElementsByClassName('audio_page_player_ctrl audio_page_player_play');
   return play.length > 0 && play[0].classList.contains('audio_playing');
}

function toggle() {
   var play = document.getElementsByClassName('audio_page_player_ctrl audio_page_player_play');
   AudioPage(play).togglePlayerPlay(play)
}`

**Comment by G07cha** [comment]
New VK design is already live, so now controls for VK isn't working at all 😞

**Comment by alucarders** [comment]
Here's my ```newVk.bsstrategy```
I did leave name with ```new``` word on purpose because it may conflict with old ```Vk.bsstrategy``` file and possibly leads to non-working import/export in the app.
[newVk.bsstrategy.zip](https://github.com/beardedspice/beardedspice/files/469237/newVk.bsstrategy.zip)

**Comment by Stillness-2** [comment]
@alucarders Не надо было делать нью :) так как это может наоборот привести к не работе стратегии :) Так две стратегии будут иметь 
```
  accepts: {
    method: "predicateOnTab",
    format:"%K LIKE[c] '*vk.com*'",
    args: ["URL"]
```
И не понятно какая из них будет цепляться.
Вам нужно просто сделать 
```
  version: 2,
  displayName: "VK",
```
:)

**Comment by alucarders** [comment]
@Stillness-2 я изначально не собирался случайно перехватывать чужие стратегии :) Поэтому пока адрес был ```new.vk.com``` всё так и было.
Вот исправленная версия:
[Vk.bsstrategy.zip](https://github.com/beardedspice/beardedspice/files/469271/Vk.bsstrategy.zip)

**Comment by G07cha** [comment]
Проверил на OS X El Capitan(10.11.6) в Google Chrome 52.0.2743.116, работает отлично с новым дизайном.

**Comment by Stillness-2** [comment]
@G07cha Удаляете кастомную стратегию из настройки. Должна прилететь обнова если нажать на "Check for Compatibility Updates".

**Comment by G07cha** [comment]
@Stillness-2, подтвеждаю, новая стратегия доступна в приложении и работает нормально с сетапом указаным выше.
