### ISSUE TITLE
Icon doesn't show up on dark mode

### ISSUE THREAD

**Issue by chezluc** [beardedspice/beardedspice#380]
![screen shot 2016-04-09 at 8 40 38 am](https://cloud.githubusercontent.com/assets/15020730/14404564/c3c78fee-fe2e-11e5-9d4b-c202f5d11329.png)
![screen shot 2016-04-09 at 8 40 35 am](https://cloud.githubusercontent.com/assets/15020730/14404565/c3d6ddc8-fe2e-11e5-81ce-779be2655b0f.png)

**Comment by chezluc** [comment]
Thanks!!!

**Comment by Stillness-2** [comment]
https://www.dropbox.com/s/f9ksca7f8tvnty3/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202016-04-09%2020.47.53.png?dl=0
What version BeardedSpice and OS X do you use?

**Comment by chezluc** [comment]
Mac OSX: 10.11.4
BS 1.2.5

**Comment by redwarp** [comment]
Same here,

Mac OS Sierra 10.12.1
BS 2.1.0

**Comment by chezluc** [comment]
It seems to be working now for me.
<img width="246" alt="screen shot 2016-11-30 at 3 43 15 pm" src="https://cloud.githubusercontent.com/assets/15020730/20776162/c4b4f2a4-b713-11e6-921e-92b24e4832ba.png">
