### ISSUE TITLE
[App Support] ListenOnRepeat

### ISSUE THREAD

**Issue by nkantar** [beardedspice/beardedspice#395]
Support for [ListenOnRepeat](http://listenonrepeat.com/) would be super duper cool.

I might give it a whirl if I have time, but I also have zero Obj-C background, so we'll see.

**Comment by 1ps0** [comment]
Check the js-conversion branch. Just need to write the js and stash it in a js file :)

**Comment by Kureb** [comment]
Sorry I referenced the wrong issue in my commit's message. It should have been 385 and not 395.

Anyway, I will soon make a pull request for that one too. Sorry for the inconvenience.

**Comment by 1ps0** [comment]
Pro tip, you can `git commit --amend` to update the commit message or add something you missed to the HEAD commit. Otherwise you'd have to `rebase --interactive` it, which is messy if you're not used to it, but still very powerful to learn.

**Comment by nkantar** [comment]
This has been added some time ago, apparently. 😁
