### ISSUE TITLE
[Browser Request] Support for Opera

### ISSUE THREAD

**Issue by plasmoctopus** [beardedspice/beardedspice#396]
Would it be possible to also support Opera? Are there big difference for implementation to Chrome, since Opera ist basically Chrome with a different UI?

**Comment by Coder-256** [comment]
This is a duplicate of #96, 300 issues back! I'm surprised nobody has implemented this yet. I'll look into it...

**Comment by plasmoctopus** [comment]
Oh wow. I’m sorry the search didn’t turn anything up (probably my fault).
Thank you!

**Comment by 1ps0** [comment]
Closing this as dupe. It's been referenced in #96 just incase :)
