### ISSUE TITLE
Vivaldi support

### ISSUE THREAD

**Issue by rucativava** [beardedspice/beardedspice#398]
As far as I know, Vivaldi is based in Chrome. Is it possible to implement support to this browser?

**Comment by 1ps0** [comment]
It's still very early release and is constantly being updated. I'm currently playing with it as well so we'll see. If the state of Chrome Extension compatibility is any indicator it has a pretty high chance of being one of the easier apps to add. 

Anyone else switching to Vivaldi as primary browser should +1

**Comment by bruisersmith** [comment]
+1 - playing with Vivaldi but having Beardedspice on it would be fantastic

**Comment by Coder-256** [comment]
See #96.

**Comment by Porco-Rosso** [comment]
Are you aware that Vivaldi uses chromium in the background? 
I would imagine that this wouldn't be difficult to implement

Here are some applescript examples:
http://piyocast.com/as/archives/category/application_control/vivaldi/
https://github.com/spamwax/alfred-pinboard/blob/master/get-current-url.applescript

**Comment by 1ps0** [comment]
This has been added and will be out shortly.
