### ISSUE TITLE
Google Chrome Slowness

### ISSUE THREAD

**Issue by chrishough** [beardedspice/beardedspice#399]
I have noticed in the latest version of Chrome and the Beardedspice application considerable slowness in  moving to the next track in Pandora, and starting / stopping.  Thoughts?

**Comment by 1ps0** [comment]
I've noticed this as well and have been looking to address it. Thankfully my latest branch of changes seem to address it (40+ tabs open and instant play/pause response). We'll see as I start wrapping up, I'll update as it gets closer to release.

**Comment by chrishough** [comment]
Awesome, I was wondering if it was just me.  Thank you for all of your hard work on this. Once the update goes live I will switch back to using it.

**Comment by 1ps0** [comment]
So far it's faster than before, but still has a significant (~3s) delay for me. My scenario has over 50 tabs open across 5 windows, and the delay scales linearly with that. It'll be one of the focuses of my next push. :)

**Comment by chrishough** [comment]
Same here, I regularly have many browsers open across multiple spaces.  I bet this is common.

**Comment by danielbayley** [comment]
Same thing with Safari…

**Comment by Stillness-2** [comment]
@chrishough what version of the BeardedSpice? Or was it build from master branch?

**Comment by chrishough** [comment]
I am using version `2.1.0`

**Comment by lexblagus** [comment]
+1 for fixing this issue
