### ISSUE TITLE
Stopped working with OSX 10.11.5

### ISSUE THREAD

**Issue by christianhans** [beardedspice/beardedspice#401]
Hi,

The recent OSX 10.11.5 upgrade completely broke Beardedspice for me. Using it with Safari Version 9.1.1. Both YouTube and Google Play Music don't react to media keys anymore.

Best
Christian

**Comment by Coder-256** [comment]
Strange, I have the same problem, it must just be Safari v9.1.1. I can't immediately figure out why.

**Comment by MatthiasJ** [comment]
Same here. Not working with OSX 10.11.5 neither with chrome nor with safari.

**Comment by wlossw** [comment]
same issue here. although chrome seems to be working... I suspect it's a safari issue...

**Comment by slhsen** [comment]
Not working with OSX 10.10.5 & Safari Version 9.1.1 (10601.6.17). Seems to be working with Chrome.

**Comment by Stillness-2** [comment]
see #402
