### ISSUE TITLE
Stopped working after Safari 9.1.1 (10601.6.17) update

### ISSUE THREAD

**Issue by aik099** [beardedspice/beardedspice#402]
Stopped working after Safari 9.1.1 (10601.6.17) update. Works in Chrome.

**Comment by Stillness-2** [comment]
<img width="682" alt="opa" src="https://cloud.githubusercontent.com/assets/12689/15456636/3eac6872-2087-11e6-891b-234d2c4323de.png">

**Comment by wlossw** [comment]
thanks works like a charm.

**Comment by christianhans** [comment]
Thank you.

**Comment by aik099** [comment]
Thank you.

**Comment by matthewcullum** [comment]
Awesome! Working.

**Comment by 1ps0** [comment]
Locking this thread. Future references should be to the [FAQ section](https://github.com/beardedspice/beardedspice/wiki) of the wiki.
