### ISSUE TITLE
Plex Home Theater Support

### ISSUE THREAD

**Issue by dbk067** [beardedspice/beardedspice#407]
Plex has a native OS X client called Plex Home Theater (https://plex.tv/downloads). It would great if you could add support for that as well.

**Comment by RSully** [comment]
FWIW, I believe Plex Home Theater is considered deprecated in favor of the currently beta Plex Media Player.

**Comment by dbk067** [comment]
Thanks for the heads up. I'm grabbing a copy of PMP now. I'd say PHT isn't yet deprecated since PMP is in (semi-private) beta. If the devs here want to focus on PMP instead though, that's understandable. I'd be happy with support for either.

**Comment by yatesco** [comment]
+1 from me for Plex Media Player.

**Comment by afhole** [comment]
Any movement on this? Would be great to see support for Plex Media Player

**Comment by squizzeak** [comment]
Upvote!

**Comment by digerata** [comment]
👍

**Comment by brzzdev** [comment]
I'd love to see Plex support
