### ISSUE TITLE
Problems with Deezer strategy

### ISSUE THREAD

**Issue by kdemidov** [beardedspice/beardedspice#414]
Hello Guys, I'm trying to update the Deezer strategy (fix broken an action, add new one), but I get the following JS errors in a browser when I click Cmd+F10 (i.e. Toggle Favorite):

![image](https://cloud.githubusercontent.com/assets/5989742/15499760/a0b964e8-21c7-11e6-9bed-26e3923e4bd6.png)

The same issue appears for YouTube:

![image](https://cloud.githubusercontent.com/assets/5989742/15499983/85d1870e-21c8-11e6-8ec0-4a102b7d4643.png)

Do you have any ideas why it happens? Is it a known issue?

**Comment by 1ps0** [comment]
Check #402 see if that's related. Youtube currently works fine for me on 1.2.5 on Chrome.

**Comment by kdemidov** [comment]
Thanks but unfortunately it didn't help. I tested with the downloaded app and compiled it myself from the source code and have the same results (with both YouTube and Deezer, I didn't check other strategies). I tried in Chrome v51 without any extensions, in the normal and incognito modes. Also I have the same results in the Safari v9.1.

By "Youtube currently works fine" you meant that "Toggle Favorite" works for you without any JS errors in the console? I get the same errors described above for this action. Everything else (Play/Pause, Next, Previous, Show Track) works for me.

**Comment by Stillness-2** [comment]
@kdemidov wait some time, we will update master branch, coming soon. Deezer strategy fixed in this update.

**Comment by kdemidov** [comment]
Thanks for letting me know! Looking forward to the update.

**Comment by Stillness-2** [comment]
`master` ветка обновлена.

**Comment by Stillness-2** [comment]
Проверьте пожалуйста как оно там :)

**Comment by kdemidov** [comment]
Всё отлично работает! 👍  Спасибо большое!
