### ISSUE TITLE
[JSConversion] BSStrategy.version and versions.plist are redundant

### ISSUE THREAD

**Issue by Coder-256** [beardedspice/beardedspice#416]
Yeah.

**Comment by 1ps0** [comment]
#383 is the ongoing discussion for this branch. Current requirements has versions.plist as not being deployed/saved with the binary, instead used as an index reference for updated strategies. BSStrategy.version is used locally to scan for most recently update version between what will be 3 different source folders: included, downloaded, and user-made.

**Comment by 1ps0** [comment]
@Coder-256 Closing this issue. Please direct further commentary on in-development features to the above referenced issue. Thanks :)
