### ISSUE TITLE
OSX 10.11.5 Update Broke v 1.2.5

### ISSUE THREAD

**Issue by enjoyfebruary** [beardedspice/beardedspice#418]
Since updating to OSX 10.11.5, BeardedSpice is no longer working. Tried removing with AppCleaner and reinstalling with the same result.

**Comment by Stillness-2** [comment]
#402

**Comment by nikitavoloboev** [comment]
I have the same issue. Bearded spice stopped working and can no longer find an open safari tab with a video.
