### ISSUE TITLE
Bearded Spice no longer working with SoundCloud via Safari.

### ISSUE THREAD

**Issue by trabera** [beardedspice/beardedspice#422]
Did something recently happen? I am no longer able to control SoundCloud audio from the website while browsing in Safari.

**Comment by 1ps0** [comment]
Check #402. It's a common issue with safari now.

**Comment by Stillness-2** [comment]
I think we need add section in readme with notes about supporting of the Safari in new era :)

**Comment by 1ps0** [comment]
@Stillness-2  I added a wiki article under a new FAQ section. Only reason I didn't link it in the README is because thats one more commit i'd have to resolve at merge time. Feel free though :)

**Comment by trabera** [comment]
Thank you. Link above to #402 solved the problem.

**Comment by nickPassey** [comment]
YES! This saved the day
