### ISSUE TITLE
Custom media strategy not working 

### ISSUE THREAD

**Issue by alvinnguyen** [beardedspice/beardedspice#424]
Hi,

I've tried to add a custom domain support but it doesn't seem to work.

The commit is here 
https://github.com/alvinnguyen/beardedspice/commit/d65f06c4ab1a45e75395d9bcf0efbd79f742a5ff

I've clear the build before re-built but it doesn't seem to recognise the tab that has the site running.

It doesn't show the added option in the Preference list as well.

Sample URL: http://mp3.zing.vn/album/Nhac-Hot-Viet-Thang-6-2016-Various-Artists/ZWZCU7C6.html

Any pointers?

**Comment by Coder-256** [comment]
You should be working with the js-conversion branch, but I think the real problem is that you forgot to add your strategy to the registry and the strategy file group (in Xcode). Both of these steps are automatically done in js-conversion, though.

**Comment by 1ps0** [comment]
In the js-conversion branch, the system will now scan for new strategies saved in `BeardedSpice/MediaStrategies` folder. So just the `BeardedSpiceUserDefaults.plist` and `versions.plist`files. No Objective-C code changes should be needed for most website strategies now.

**Comment by alvinnguyen** [comment]
Thanks guys, with the updated README.md it's now clear :)
