### ISSUE TITLE
beardedspice stopped recognising applicable tabs

### ISSUE THREAD

**Issue by Maslor** [beardedspice/beardedspice#427]
<img width="214" alt="screen shot 2016-06-13 at 16 24 54" src="https://cloud.githubusercontent.com/assets/9674408/16012913/63b06d14-3183-11e6-8c80-75be3eea51e7.png">

Since I last updated my OSX El Capitan (to version 10.11.5) beardedspice stopped recognising applicable tabs on safari (Version 9.1.1 (11601.6.17)). 
Beardedspice still works on Chrome, though.

**Comment by 1ps0** [comment]
Please read the wiki article under FAQ that directly refers to this issue.

**Comment by Maslor** [comment]
Thanks!
