### ISSUE TITLE
Add support for poolside.fm

### ISSUE THREAD

**Issue by alanhussey** [beardedspice/beardedspice#428]
http://www.poolside.fm/

Note that there is also a "mobile" version at http://www.poolside.fm/mobile/ – not sure if you can target subpages separately on a domain. On the mobile page, `playPause()` and `skipTrack()` are globals, so it should be simple enough to support the mobile page. Haven't looked into the homepage yet.

**Comment by Coder-256** [comment]
On mobile there are also many other things you can do like `tracks[currentTrackPos]`, but since BeardedSpice only works on Mac for now, I will start working on the regular version...

**Comment by Coder-256** [comment]
@1ps0 This should be closed now.
