### ISSUE TITLE
No track (null) in "open players" in menu bar when supported application is "not responding"

### ISSUE THREAD

**Issue by scottwarren** [beardedspice/beardedspice#430]
When iTunes is "not responding" the menu bar has the following in it:

![image](https://cloud.githubusercontent.com/assets/2718494/16068577/42ab007e-330a-11e6-8c7e-1706b0a2f1b7.png)

Once iTunes is closed (forcefully or otherwise) then BeardedSpice is all good :+1:

**Comment by scottwarren** [comment]
Tracked potentially where this could be fixed (please note my complete lack of understanding of OS X development/C/C++) is here:

https://github.com/beardedspice/beardedspice/blob/master/BeardedSpice/AppDelegate.m#L786

**Comment by Stillness-2** [comment]
@scottwarren BeardedSpice version?

**Comment by scottwarren** [comment]
Oops, sorry: version `1.2.5 (17)`

**Comment by scottwarren** [comment]
Thanks!
