### ISSUE TITLE
Add option to Launch at Login

### ISSUE THREAD

**Issue by jwfuller** [beardedspice/beardedspice#44]
Would be great to make this auto launch, I often forget that it isn't launched and press media keys, launching iTunes

**Comment by foozee** [comment]
@Stillness-2 could u kindly reference which commit closes this? ( @josefalcon 's suggestion shows how a user can do this manually, but I think it's more user-friendly to have an in-app checkbox to allow the app to do that on it's own) what do u think?

**Comment by Stillness-2** [comment]
I think it is unnecessary function. If you like this idea, you must reopen this issue. :)

**Comment by foozee** [comment]
I think it's a cool addition, but yes I agree it's sort of a lower-priority addition, but let's keep that open as a possible enhancement :)

**Comment by Stillness-2** [comment]
Ok :)

**Comment by simonwex** [comment]
:+1:
