### ISSUE TITLE
General responsiveness

### ISSUE THREAD

**Issue by danielbayley** [beardedspice/beardedspice#442]
There is a good few seconds delay between a media key being pressed and the corresponding action.

Although I currently have many tabs spread across several Safari windows and iTunes also running, I wonder if there might be a way to speed things up? Maybe some kind of cache or something?

**Comment by 1ps0** [comment]
Check #399. It's a very well known issue and something I'm aiming to have fixed in the very near future. 

A lot of the timing has to do with inefficiencies that the system has built up over it's development. It's taking more work than I had originally anticipated.

**Comment by Stillness-2** [comment]
@danielbayley what version of the BeardedSpice? Or was it build from master branch?

**Comment by danielbayley** [comment]
@Stillness-2
`brew cask install bearded spice`
1.2.5

**Comment by danielbayley** [comment]
> It's taking more work than I had originally anticipated.

Nothing ever does… 😄

**Comment by danielbayley** [comment]
Couldn't it just let key events pass through unimpeded if iTunes is playing?

This can be determined **instantly** with _JavaScript for Automation_ (and even _AppleScript_ which generally runs at a **snail’s pace**, but is lighting compared to the current behaviour…)
~~~ js
iTunes = Application('iTunes')
if (iTunes.playerState() == 'playing') { … }
~~~

**Comment by danielbayley** [comment]
I just came across [_Nightmare JS_](https://github.com/segmentio/nightmare) and thought it might be relevant…

**Comment by dbkaplun** [comment]
> @danielbayley commented on Sep 7, 2016:
>
> *I just came across Nightmare JS and thought it might be relevant…*

See also [GoogleChrome/puppeteer](https://github.com/GoogleChrome/puppeteer/)
