### ISSUE TITLE
Not working w/ Amazon Music

### ISSUE THREAD

**Issue by dinkyrdj** [beardedspice/beardedspice#444]
First, I was so happy to find this app! Well done! 

I just tried to use BeardedSpice (1.2.5) with Amazon Music (music.amazon.com) today and it doesn't pick up on Amazon Music. In the same web browser (Safari 9.1.1) I tried Pandora and YouTube and BeardedSpice picked them up immediately and worked just fine. Am I missing something when using it with Amazon Music? I've allowed Java scripts for Apple Events.

Thanks, Ryan

**Comment by 1ps0** [comment]
Hey Ryan! Thanks for the feedback :)

Amazon has been fixed in the upcoming update. Feel free to compile your own copy from the current repo code.
