### ISSUE TITLE
Support for Safari Technology Preview

### ISSUE THREAD

**Issue by kradalby** [beardedspice/beardedspice#445]
Hi

I'm currently using Safari Technology Preview, but it does not seem like beardedspice can detect and  work together with it, would that be possible to implement? The browser _should_ be very very similar to the stock Safari that ships with OSX.

I'm using version 1.2.5

**Comment by 1ps0** [comment]
There's an open PR for this exact thing. See issue #368 and PR #413. I don't know about plans to integrate it just yet, but you can on a personal branch in the mean time.
