### ISSUE TITLE
Safari not visible as a source of playback

### ISSUE THREAD

**Issue by bendingtime** [beardedspice/beardedspice#448]
Hi,
For some weird reason I have lost control over the safari as a music source.
Chrome works just fine but Safari not at all.

Please advise.

![_soundcloud_screenshot_](https://cloud.githubusercontent.com/assets/13184122/16874034/2b89ed8e-4a97-11e6-9013-94333542a8ac.png)
<img width="246" alt="_osx_info" src="https://cloud.githubusercontent.com/assets/13184122/16874035/2b8ce340-4a97-11e6-90ba-42572cf29bd0.png">

**Comment by Stillness-2** [comment]
https://github.com/beardedspice/beardedspice/wiki/Wont-Work-issue-after-Safari-Update-(9.1.1-and-later)
