### ISSUE TITLE
2.0.0 breaks external mouse movement

### ISSUE THREAD

**Issue by rudmer90** [beardedspice/beardedspice#452]
This is a weird one.  Any time I run BeardedSpice 2.0.0, my external mouse (Logitech M510) stops working properly.  I can still click with it, so I know it's not the battery or receiver, but any and all mouse movement is ignored.  Movement via built-in trackpad works just fine, as do keypresses from the keyboard that uses the same receiver as the mouse.  Once the mouse stops working, restarting the OS (and not running BeardedSpice) is the only way to get full mouse functionality back.

Running a MacBook Pro (Retina, 15-inch, Mid 2014) on OSX 10.10.5

**Comment by rudmer90** [comment]
Update: turns out it wasn't the update. I uninstalled 2.0.0 and deleted ~/Library/Application Support/BeardedSpice and installed 1.2.5.  It had the same issue.  Re-pairing the mouse to the receiver using Logitech's Unifying Software appears to have fixed the problem.

**Comment by 1ps0** [comment]
Thanks for keeping us informed.
