### ISSUE TITLE
Menu Bar Icon too dark? (OS X El Capitan 10.11.6)

### ISSUE THREAD

**Issue by bolandross** [beardedspice/beardedspice#459]
Hey, I just started using BeardedSpice and noticed that its menu icon is a lot darker than other popular menu bar icons that can be found (system and custom ones). 

Check it out:
![bildschirmfoto 2016-08-01 um 10 57 57](https://cloud.githubusercontent.com/assets/5481702/17288866/523e24de-57d7-11e6-8201-892b28b6ad4f.png)

I understand that this is an aesthetical issue, but found it to bother me enough to come here ;D

Addition: Also, the horizontal spacing seems to be to small, is there a convention by Apple?

Best regards,
boland

**Comment by 1ps0** [comment]
You're totally welcome to fire up some photoshop clones and adjust the darkness level. :) 
Send us a PR!

**Comment by Stillness-2** [comment]
#464
