### ISSUE TITLE
Add support for Firefox

### ISSUE THREAD

**Issue by jwfuller** [beardedspice/beardedspice#46]
Love it in chrome, would like to recommend it to a friend who is a firefox user

**Comment by vanniktech** [comment]
Any updates on this? As this issue is quite old.

**Comment by norswap** [comment]
Use this Firefox addon: https://addons.mozilla.org/en-US/firefox/addon/media-keys/
(Does work when the Firefox window is not focused or minimized.)

**Comment by lvde21** [comment]
Does not work if one is opted into or using Electrolysis (https://wiki.mozilla.org/Electrolysis)

**Comment by 1ps0** [comment]
The strategies we add and maintain aren't strictly locked to Chrome, or even Mac. If someone can make or find a firefox addon that uses our js strategies, we might be able to sidestep the entire incompatibility issue.

**Comment by amjd** [comment]
Can Firefox support be added if you look at how the addon @norswap mentioned is working?
The Github repo for that project is here: https://github.com/carlin-q-scott/browser-media-keys

**Comment by 1ps0** [comment]
They take an entirely different approach from us, and I dont see a clear way to tie it into our system. I'll take a deeper look when I have more time though, unless you want to take a swing at it yourself :)

**Comment by harryi3t** [comment]
Would really like this
Is there any workaround for this? I mean by using some plugin that can inject some script.

**Comment by flayks** [comment]
+1

**Comment by Stillness-2** [comment]
We have approach for that in v 3, but have no time. :(
https://github.com/beardedspice/beardedspice/tree/bs3
https://github.com/beardedspice/beardedspice/milestone/19

**Comment by vmfhrmfoaj** [comment]
You might already know, recently Firefox have renewed the extension system.
It is called WebExtention.
It is similar to Chrome’s extension systems, so you can share a lot of the code between Firefox extension and Chrome extension.

**Comment by decadent** [comment]
Firefox extensions can communicate with native programs via [the native messaging api](https://wiki.mozilla.org/WebExtensions/Native_Messaging) (shared with Chromium). Afaik it's the only way to do that in FF. You would need an intermediary program which the browser would run, and which then would be called from Beardedspice itself with some IPC mechanism.

**Comment by ELLIOTTCABLE** [comment]
This is the single thing I miss most, after switching to Firefox, recently.

How high-priority is this? I'm a fairly proficient hand at JS; though I've never authored an extension before … should I expect any sort of involvement from the BS team, or more of a write, fire, and forget PR? (=

**Comment by bensleveritt** [comment]
@ELLIOTTCABLE Just do it. Ask for forgiveness after

**Comment by retke** [comment]
I would love this!

**Comment by MichaelSp** [comment]
![DO IT](https://i.vimeocdn.com/video/538310008.jpg)

**Comment by trhodeos** [comment]
FWIW @josefalcon and I created a javascript-only version of BS a while ago (https://github.com/trhodeos/bs-extension), meant to be run as a browser extension instead of a standalone app. It looks like Firefox supports media keys shortcuts for extensions, this could be an easy way to get firefox support. See https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands for more info.

**Comment by skywinder** [comment]
@trhodeos thanks for update. Is it still actual solution for now?

**Comment by amjd** [comment]
Looks like Firefox is going to add native support for this in v76 (as Chrome did last year). It's already landed in the nightly version.
https://www.ghacks.net/2020/03/23/firefox-will-soon-support-hardware-media-controls/

**Comment by treeshateorcs** [comment]
![image](https://user-images.githubusercontent.com/60894565/110235118-7d7ddd80-7f3f-11eb-8004-7b0b597ced2c.png)
