### ISSUE TITLE
[App Support]

### ISSUE THREAD

**Issue by Duskcyclist** [beardedspice/beardedspice#461]
Hi BeardedSpice support,

BeardedSpice is such a must-have app, however, the last few months it stopped working for me in Safari. It works in Chrome, but not Safari. I've tried it on two machines as well. One is running 10.10.5 & the other 10.11.6. Any ideas why BeardedSpice isn't even seeing anything playing in Safari? You can see in the attached screenshot, I'm playing a song through Spotify via the web, but Bearded Spice only sees iTunes. 

![screen shot 2016-08-01 at 3 57 55 pm](https://cloud.githubusercontent.com/assets/20780273/17306995/e141a2ea-5800-11e6-8723-32ac229c1fe7.png)
Thanks for your help!

**Comment by 1ps0** [comment]
It sounds like you're hitting the Safari javascript blocker which was added in 9.1.1. Check the [Wiki article](https://github.com/beardedspice/beardedspice/wiki/Wont-Work-issue-after-Safari-Update-(9.1.1-and-later)).

**Comment by Duskcyclist** [comment]
That did it! Thank you Alex!

**Comment by 1ps0** [comment]
Glad it worked :)
