### ISSUE TITLE
External mouse stops moving when opening Bearded Spice

### ISSUE THREAD

**Issue by Stuk** [beardedspice/beardedspice#463]
This is really weird, but when I open Bearded Spice my external mouse stops moving the mouse cursor. Left click and right click still work, but movement doesn't. The trackpad continues to work absolutely fine. I have to unplug and plug back in the receiver for the external mouse movement to start working again.

The mouse is a Logitech Performance MX, and I'm using the Logitech Control Center software.
I'm on OSX 10.10.5

Any thoughts?

**Comment by 1ps0** [comment]
Open as in launch the app or open the menu?

What version of BS are you running?

**Comment by Stuk** [comment]
Opening the app. Once my mouse is back working the menu works fine.

I'm on 2.0.0 (checking for updates says I'm up to date)

**Comment by 1ps0** [comment]
Can you follow the full set of steps to reproduce and paste any interesting console (via the OSX Console.app) output that happens during the loss of movement?

**Comment by Stillness-2** [comment]
#452

**Comment by Stuk** [comment]
Sure, I'll grab the log tomorrow

**Comment by Stuk** [comment]
I feel like I've seen this a number of times, but I can't reproduce it now! Closing until I can repro and get you a log.
