### ISSUE TITLE
X_BeardedSpice_Chrome_ApplescriptHack in Google Calendar

### ISSUE THREAD

**Issue by mliq** [beardedspice/beardedspice#467]
My work uses Google Calendar for business to schedule meeting rooms. 

When I have Bearded Spice loaded, it inserts itself into the calendar as the top of the room hierarchy. 

I am not sure if this is causing any real problems for me but it is concerning.

<img width="769" alt="screenshot 2016-08-08 09 23 36" src="https://cloud.githubusercontent.com/assets/7573605/17482994/d3b35030-5d49-11e6-9c61-6c49d11333d8.png">

**Comment by 1ps0** [comment]
What's the core URL? The only google strategy I can find is for `play.google.com/music`in [GoogleMusic](https://github.com/beardedspice/beardedspice/blob/master/BeardedSpice/MediaStrategies/GoogleMusic.js).

**Comment by mliq** [comment]
BS version is 2.0.0.
The core url is: https://calendar.google.com/calendar/render

It also occurs for Guests if they are in a group (in addition to Rooms):
<img width="300" alt="screen shot 2016-08-11 at 8 39 09 am" src="https://cloud.githubusercontent.com/assets/7573605/17590396/445b4a66-5f9f-11e6-9efe-f5ec303b05ec.png">

**Comment by 1ps0** [comment]
That helps a lot and gives me a pretty good idea of what's going wrong. I'll let you know if I need more information. Thanks.

**Comment by 1ps0** [comment]
@mliq We just pushed a hotfix for an unrelated issue, but it very well could affect this one. Are you still seeing it? If so, does 2.1.2 fix the issue.

**Comment by 1ps0** [comment]
@mliq closing this as fixed, unless we have confirmed replication elsewhere
