### ISSUE TITLE
[App Support] Add a handler for Overcast.fm (pretty please)

### ISSUE THREAD

**Issue by redhae** [beardedspice/beardedspice#471]
😚

**Comment by 1ps0** [comment]
There is one. Is it not working?

What version of the app are you using?

**Comment by redhae** [comment]
hey, thanks for replying. 
i see it in the list now (version  2.0.0 (18) ) but it doesn't see to work for me (playing an overcast episode in a chrome canary build)

**Comment by 1ps0** [comment]
The canary build might be why. Does it not work in the main release branch?

**Comment by redhae** [comment]
doesn't work there either

**Comment by Stillness-2** [comment]
#360
