### ISSUE TITLE
Beardedspice seems to break macbook media control keys for Amazon Music desktop app

### ISSUE THREAD

**Issue by joehenry087** [beardedspice/beardedspice#476]
Macbook media shortcut keyboard keys work when beardedspice is closed, but upon opening beardedspice the keys no longer work for Amazon Music desktop app.

**Comment by Stillness-2** [comment]
Check this build https://www.dropbox.com/s/ubj1dzvqkwtneud/BeardedSpice.zip?dl=1 please.
