### ISSUE TITLE
Crash when click on menu-bar icon

### ISSUE THREAD

**Issue by crash-47** [beardedspice/beardedspice#482]
Hi,
When I click on the menu-bar icon to set preferences, the app crash. Latest version that work for me is 2.0.0.
_Computer_ is Mac Pro early 2009 OS X _10.10.5_

[BeardedSpice_2016-09-15-143715_macpropao.txt](https://github.com/beardedspice/beardedspice/files/474631/BeardedSpice_2016-09-15-143715_macpropao.txt)
[BeardedSpice_2016-09-15-143445_macpropao.txt](https://github.com/beardedspice/beardedspice/files/474632/BeardedSpice_2016-09-15-143445_macpropao.txt)

Best regards

**Comment by 1ps0** [comment]
How many tabs do you typically have open in either/both browsers?

**Comment by crash-47** [comment]
approximately 20 tabs. But not really with video.

**Comment by Ustice** [comment]
Same error with all browsers completely closed. 

macOS Sierra 10.12.1 (16B2555)

**Comment by 1ps0** [comment]
What version of the app are you using?

**Comment by 1ps0** [comment]
What version of the app are you using?

**Comment by Ustice** [comment]
Version 2.1.0 (19)

I also have an update:

This issue was resolved by rebooting. I'm not sure if this would be an app bug, or something going on with my system at the time.

**Comment by 1ps0** [comment]
At least it was a relatively easy fix. Looking into this for the next release.

**Comment by AnthonyWhitakerJr** [comment]
Unable to reproduce; is this still an issue?

**Comment by 1ps0** [comment]
Closing this as fixed for the time being. Near term plans include implementing a form of limited crash reporting.
