### ISSUE TITLE
[App Support] No Applicable Tabs

### ISSUE THREAD

**Issue by AaronLMGoodwin** [beardedspice/beardedspice#485]
Hello, at some point BeardedSpice stopped detecting media tabs. I've tried completely removing the app and its other files and re-installing, and I experience the same issue. Any ideas? Any additional information I can send?

**Comment by 1ps0** [comment]
Starting when?

When you say media tabs, are you talking about all websites?

Removing the other files shouldn't make a difference, but you  might also make sure you've removed the files in `YOUR_HOME/Library/Application Support/CustomStrategies and Strategies`

**Comment by erikroznbeker** [comment]
Hello! Same error "No applicable tabs open" when trying to controll Youtube on Safari (OS: El Capitan). On Chrome works ok. BeardedSpice v.2.1.0

**Comment by cgrinds** [comment]
@erikroznbeker did you try [this?](https://github.com/beardedspice/beardedspice/wiki/Wont-Work-issue-after-Safari-Update-(9.1.1-and-later))

**Comment by AaronLMGoodwin** [comment]
@1ps0 Yes, I mean all websites with media players. For example, it [does not detect YouTube](http://l.gdwn.co/Zems) or [Overcast](http://l.gdwn.co/1hXYQ). 

I checked both user and system level application support folders and found neither /CustomStrategies, nor /Strategies. 

I was running OS X 10.11.5. I'm now running MacOS 10.12 and experiencing the same issue.

Any other ideas?

**Comment by 1ps0** [comment]
Did you check what @cgrinds linked? Safari 9.1.1 puts a block on script injections which is what BeardedSpice does. It's a simple toggle. 

If you're using Chrome, it would be a different matter entirely though.

**Comment by AaronLMGoodwin** [comment]
@1ps0 @cgrinds Somehow I missed that reply. That was totally the issue, thanks!

**Comment by erikroznbeker** [comment]
> cgrinds commented
> @erikroznbeker did you try this?

Thanks!
