### ISSUE TITLE
Not working with Sierra

### ISSUE THREAD

**Issue by MaxHasADHD** [beardedspice/beardedspice#489]
Just installed on macOS Sierra, YouTube and PocketCast seem not to be working (only 2 I tried it with). It has accessibility access. Says "No Applicable Tabs Open"

**Comment by 1ps0** [comment]
Check to see if [this resolves your issue.](https://github.com/beardedspice/beardedspice/wiki/Wont-Work-issue-after-Safari-Update-(9.1.1-and-later))

**Comment by MaxHasADHD** [comment]
That worked, thank you!
