### ISSUE TITLE
No applicable tabs open

### ISSUE THREAD

**Issue by vkuznetsov** [beardedspice/beardedspice#498]
El Capitan 10.11.6 (15G1004)
Safari 10.0 (11602.1.50.0.10)

Не распознаёт вкладки вообще (попробовал Yandex.Music, VK, Youtube, Soundcloud).

<img width="1440" alt="screenshot 2016-10-15 12 54 29" src="https://cloud.githubusercontent.com/assets/1082812/19408472/67331c88-92d7-11e6-9703-6f43fa440e83.png">

**Comment by Stillness-2** [comment]
https://github.com/beardedspice/beardedspice/wiki/Wont-Work-issue-after-Safari-Update-(9.1.1-and-later) Это делали?

**Comment by vkuznetsov** [comment]
Спасибо! Это помогло.
