### ISSUE TITLE
Update Yandex.Music and Yandex.Radio strategy

### ISSUE THREAD

**Issue by veged** [beardedspice/beardedspice#501]
It's doesn't work now at all :-(

**Comment by 1ps0** [comment]
Since I'm not in the countries allowed I can't test this properly. +1 for same problem.

**Comment by rodweb** [comment]
Works in Safari, but doesn't work in Yandex.Browser.

**Comment by 1ps0** [comment]
We don't currently have support for the Yandex Browser. :(

**Comment by rodweb** [comment]
> It is an extensible application that works with Chrome (Canary, Yandex, Chromium) and Safari, and can control any tab with an applicable media player.

Taken from the website 😄

**Comment by 1ps0** [comment]
Lol derp. I'll take a closer look, thought I think that statement is a little naive :\

**Comment by veged** [comment]
actually, it doesn't work for me even in Safari (with last versions of core and compatibility updates) :-(

**Comment by 1ps0** [comment]
@veged Can you make sure that it still has Accessibility access? 

> System Preferences -> Security & Privacy -> Accessibility -> BeardedSpice.app (should be checked)

Also check out the [ever-annoying Safari JS fix](https://github.com/beardedspice/beardedspice/wiki/Wont-Work-issue-after-Safari-Update-(9.1.1-and-later))

**Comment by veged** [comment]
it has Accessibility access

start work after https://github.com/beardedspice/beardedspice/wiki/Wont-Work-issue-after-Safari-Update-(9.1.1-and-later) !

**Comment by 1ps0** [comment]
Going to close this as resolved. 

@rodweb I think we have enough people trying to use Yandex.Browser as well that we're going to move discussion about it to #560.
