### ISSUE TITLE
Safari playback doesn't work in macOS 10.12.1

### ISSUE THREAD

**Issue by jdsimcoe** [beardedspice/beardedspice#502]
I'm on macOS `10.12.1` with Safari `Version 10.0.1 (12602.2.14.0.7)`. Trying to used BeardedSpice to control music playing in a SoundCloud tab with SoundCloud enabled in Preferences. BeardedSpiced menubar says `No applicable tabs open`.

**Comment by pavel-sakun** [comment]
Same for youtube, vk and safari in general. No sites are handled by бородач, though they are working fine in chrome. Let me know how I could provide with debug info.

**Comment by 1ps0** [comment]
Please see [this article from the Wiki](https://github.com/beardedspice/beardedspice/wiki/Wont-Work-issue-after-Safari-Update-(9.1.1-and-later)). Let us know if it doesn't resolve your issue :)

**Comment by bjansen** [comment]
That fixed the problem for me, after restarting BeardedSpice. It also works with PiP!

**Comment by 1ps0** [comment]
That's a good suggestion. I'll see what we can do. 

I'm gonna close this now :)

**Comment by jdsimcoe** [comment]
Thanks @1ps0 that fix worked for me too!
