### ISSUE TITLE
2.1.0 not working with Safari under macOS 10.12.1

### ISSUE THREAD

**Issue by patrickrushton** [beardedspice/beardedspice#504]
Not working with Safari on my machine. Tried Mixcloud, Youtube and Spotify Web Player. 

Menubar just says "No applicable tabs open"

Tried disabling all Safari extensions. And I have allowed access under Accessibility in System Preferences.

Any ideas?

**Comment by 1ps0** [comment]
Please see [this article from the Wiki](https://github.com/beardedspice/beardedspice/wiki/Wont-Work-issue-after-Safari-Update-(9.1.1-and-later)).

**Comment by horak** [comment]
I think this can be closed. @patrickrushton, did that solve your problem?

**Comment by patrickrushton** [comment]
Yes, solved. Thank you.
