### ISSUE TITLE
Native support for Mac Desktop Amazon Music App

### ISSUE THREAD

**Issue by myrison** [beardedspice/beardedspice#507]
Awesome app and thank you for supporting it!

Would it be possible to add native support for the desktop Mac Amazon Music app?
https://www.amazon.com/Amazon-Digital-Services-LLC-Music/dp/B00GRFIIHO

Thanks!

**Comment by 1ps0** [comment]
@myrison From what I can tell this won't be possible. The Amazon Music app doesn't seem to implement any kind of ScriptingBridge we can latch onto. I'll reopen this ticket if we can find another way around it, but for now it's an Amazon decision thats blocking us.

**Comment by JohnClay** [comment]
It looks like the app is at least partially scriptable.

https://gist.github.com/muhqu/7d77b69cc61aa39b65ccdc22ab14b37f

**Comment by mattrayner** [comment]
Is this still considered blocked? I'd be VERY interested in this

**Comment by insanoid** [comment]
Added support here - https://github.com/beardedspice/beardedspice/pull/910
