### ISSUE TITLE
"No Track" bug in title return for iTunesTabAdapter

### ISSUE THREAD

**Issue by mmedal** [beardedspice/beardedspice#509]
I've noticed on my Macs (all latest iTunes on MacOS's 10.10, 10.11, and 10.12), BeardedSpice's pulldown menu always shows "No Track (iTunes)" regardless of whether iTunes is playing music or not.

<img width="328" alt="screen shot 2016-11-08 at 2 26 49 pm" src="https://cloud.githubusercontent.com/assets/1574365/20120406/8936a7e4-a5c1-11e6-9b4c-539bcb6ebc5b.png">

For some reason, it appears that the explicit `get` in [iTunesTabAdapter.m on L#47](https://github.com/beardedspice/beardedspice/blob/master/BeardedSpice/Tabs/iTunesTabAdapter.m#L47) never returns the `currentTrack` instance. I am no expert in Apple's Scripting Bridge API, but it appears that if we simply use the "phantom" `currentTrack` property and _then_ send a request for the track details, it works just fine! i.e. use `iTunesTrack *currentTrack = [iTunes currentTrack];` instead.

See [pull request #508](https://github.com/beardedspice/beardedspice/pull/508) for my simple fix.

**Comment by 1ps0** [comment]
Merged and slated for release with `2.1.1`
