### ISSUE TITLE
Doesn't work in Safari

### ISSUE THREAD

**Issue by BeatTheFreak** [beardedspice/beardedspice#518]
First let me say great app, but it seems to only work in chrome and not safari. Is this supposed to happen?

I am using macOS Sierra (10.12.1) with MacBook Pro Touchbar.

Thanks!

**Comment by Stillness-2** [comment]
https://github.com/beardedspice/beardedspice/wiki/Wont-Work-issue-after-Safari-Update-(9.1.1-and-later)

**Comment by BeatTheFreak** [comment]
> Stillness-2 commented 9 hours ago
https://github.com/beardedspice/beardedspice/wiki/Wont-Work-issue-after-Safari-Update-(9.1.1-and-later)

Thanks! Works perfectly!
