### ISSUE TITLE
Update or Replace Track Info in Notification Center

### ISSUE THREAD

**Issue by AnthonyWhitakerJr** [beardedspice/beardedspice#520]
Currently, when track info is displayed a new notification is sent to the Notification Center. This can lead to a build up of several notifications. Instead, when a new notification is sent, the old notification should be updated with the new track info OR removed & replaced with a new notification.

**Comment by 1ps0** [comment]
I've noticed this too. I saw you forked the repo, is this a current work item for you?

**Comment by AnthonyWhitakerJr** [comment]
I am poking through the code when time allows. I should be able to fix this within a week or so. No objections if someone can patch it sooner.
