### ISSUE TITLE
Option to Show Notification when Track Info Changes

### ISSUE THREAD

**Issue by AnthonyWhitakerJr** [beardedspice/beardedspice#521]
Add a listener to track info that will fire a new notification when track info changes.

**Comment by bretmartin** [comment]
Same as #144?

**Comment by 1ps0** [comment]
Yep, good catch.

**Comment by AnthonyWhitakerJr** [comment]
Nice catch on #144. From the looks of that issue tho, it is focusing on modifying the strategies while this issue suggests modifying BS itself. The strategies would be unlikely to need change.
