### ISSUE TITLE
Why no play on 10.12.2

### ISSUE THREAD

**Issue by airpoint** [beardedspice/beardedspice#524]
Since upgrading to 10.12.2 Beta, I can't get the BeardedSpice to work at all. Was trying with SoundCloud/Youtube in Chrome/Safari—no luck. (I got the allow Apple events for js activated in Safari).

Can't even assign the play/pause buttons at all in prefs, it just ignores the play/pause key press completely: 
![bspice](https://cloud.githubusercontent.com/assets/4161138/20981549/168744c6-bcad-11e6-849f-479d1ce8c8c0.png)

**Comment by 1ps0** [comment]
Betas are implicitly not supported, since we'd essentially be playing catchup with the developers and not their release cycle. 

#525 had a similar issue that was resolved by reinstalling. Can you see if that affects your problem at all?

**Comment by airpoint** [comment]
> #525 had a similar issue that was resolved by reinstalling. Can you see if that affects your problem at all?

Wow, a complete uninstall (via AppCleaner) and then a clean install has fixed the problem. All good. How about that!

Thanks for the great app. Keep up the good work!

Cheers
