### ISSUE TITLE
osx 10.12.1 keyboard short cuts not working at all

### ISSUE THREAD

**Issue by chrishough** [beardedspice/beardedspice#525]
<img width="538" alt="screen shot 2016-12-07 at 4 28 39 pm" src="https://cloud.githubusercontent.com/assets/744056/20992638/3e4893ec-bc9a-11e6-86cd-597383420b5d.png">

No matter what I assign these too, they are not working... thoughts?

**Comment by chrishough** [comment]
*Update* This is related to chrome and no, this did not fix it https://github.com/beardedspice/beardedspice/wiki/Wont-Work-issue-after-Safari-Update-(9.1.1-and-later)

**Comment by chrishough** [comment]
After a reinstall it now works correctly, however there is still a very long day between changes.

**Comment by 1ps0** [comment]
FYI we're aware of the delay in certain cases. How many windows and tabs do you have open? The time scales up according to that number with a cap of ten seconds.

**Comment by chrishough** [comment]
On average I would say 10 windows, most with 3 - 5 tabs, a few with 6-10 tabs.
