### ISSUE TITLE
Guidelines for Using Bearded Spice

### ISSUE THREAD

**Issue by RiddhiKShah** [beardedspice/beardedspice#528]
Hello, I have been trying to get Bearded Spice to work with Safari but it just won't detect any tabs. Any tips or advice on how I can get it to work?

Thanks.

**Comment by 1ps0** [comment]
Take a look at [this wiki article](https://github.com/beardedspice/beardedspice/wiki/Wont-Work-issue-after-Safari-Update-(9.1.1-and-later)).

**Comment by 1ps0** [comment]
Marking as resolved. Please make a new ticket if the wiki article, or reinstalling doesn't resolve your issue. As much detail as possible please :)
