### ISSUE TITLE
BeardedSpice 2.1.1 causes Google Music to stop playing 

### ISSUE THREAD

**Issue by anorth2** [beardedspice/beardedspice#529]
Chrome 54.0.2840.98 (64-bit)
BeardedSpice 2.1.1

Music will stop playing and music controls in window don't respond. Google Music does respond after killing BeardedSpice, refreshing tab. If beardedspice is open and I attempt to refresh page, google music reports playback error.

**Comment by Siege617** [comment]
I was experiencing this with 2.1.1 as well. I deleted it, and downloaded 2.0, and had the same issue.

Based on this very brief test, maybe google changed the way they handle things, as opposed to beardedspice making a change that broke things?

**Comment by igchy** [comment]
i've tried 2.1.0 (which was working fine for me) yesterday, got the same results. i noticed google play music extension updated on 12/13:
> Version: 1.346.0
> Updated: December 13, 2016
> Size: 14.25MiB
chrome crashed few time on me yesterday, what browser do you guys use?
i'm trying 2.1.1 with new chrome profile now.

**Comment by Siege617** [comment]
The version of chrome I have is 55.0.2883.87

**Comment by 1ps0** [comment]
From what I'm seeing, the strategy code itself still works, but Google is somehow now protecting it. Looking at potential solutions.

**Comment by jongamble** [comment]
I am receiving the same error messages as @1ps0 in the developer console.

**Comment by igchy** [comment]
so, what can we do fix this, except of waiting for google? is it a good idea to try google support forum, like https://productforums.google.com/forum/#!forum/play ?

**Comment by 1ps0** [comment]
Its looking like it might be related to how we do js injection.

**Comment by 1ps0** [comment]
Yep that seems to have been the problem. Going to try to get 2.1.2 out tonight.

**Comment by 1ps0** [comment]
Can I get a verify? I had to entirely restart BS to make it work right. Then all was well.

**Comment by igchy** [comment]
just tried, works for me, thanks a lot for the fix.
