### ISSUE TITLE
Release notes broken

### ISSUE THREAD

**Issue by Stillness-2** [beardedspice/beardedspice#537]
https://www.dropbox.com/s/s8bx7hx7ucb798r/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202016-12-15%2010.22.01.png?dl=0

**Comment by 1ps0** [comment]
Still?

**Comment by Stillness-2** [comment]
Yes :) Simply I can't solve this problem right now. :) I need to work...

**Comment by 1ps0** [comment]
No worries, I'm on it.

**Comment by 1ps0** [comment]
Attempted fix with #539 didnt work. Thoughts?

**Comment by pdutourgeerling** [comment]
Sorry, #539 also didn't fix it. I will try to look at it again when I have some time.

**Comment by 1ps0** [comment]
You and me both.

**Comment by pdutourgeerling** [comment]
I think I see it, Sparkle was updated in b847d62 and since Sparkle 1.14.0 javascript is disabled by default and you have to opt-in to enable it.

**Comment by 1ps0** [comment]
Good catch. Guess we get a 2.1.3. I'll work on that tonight.

**Comment by pdutourgeerling** [comment]
Sounds good! Sorry for the PR

**Comment by 1ps0** [comment]
It was an honest attempt. If you look at the commit history I tried something slightly similar last night :)

**Comment by 1ps0** [comment]
@pdutourgeerling Tests show in the green. Only thing is, 2.1.1 and 2.1.2 won't ever download patch notes. Go figure.
