### ISSUE TITLE
Add app to supported list - MarshallOfSound Desktop GooglePlayer

### ISSUE THREAD

**Issue by jirivorel** [beardedspice/beardedspice#538]
Hi,
first of all, thank you for your great tool. Are you able add support for desktop app Google-Play-Music-Desktop-Player? Link on Github: [https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-](url)

Thank you very much.

Jirka

**Comment by jirivorel** [comment]
Oh ... something is wrong with link. Look here [https://www.googleplaymusicdesktopplayer.com/](url) :-)

**Comment by 1ps0** [comment]
Updated the title to reflect that its *not* a dupe of #285.

I'm not quite there yet, but I'm aiming in the relatively near term to batch up and add as many as I can. There's potential to make OSX app compatibility closer to the simplicity we now have with web. Stay tuned, but also feel free to poke around adding this yourself.

Cheers!

**Comment by 1ps0** [comment]
However this is a dupe of #499.
