### ISSUE TITLE
"No access to control of the keyboard"

### ISSUE THREAD

**Issue by agemmell** [beardedspice/beardedspice#543]
BeardedSpice v2.1.3 (23)
OSX 10.11.6 (El Capitan)
Chrome Version 55.0.2883.95 (64-bit)

Just discovered this app!  Installed it and the menubar dropdown says "No access to control of the keyboard".  I googled this but am at a complete loss for what I'm meant to do to get it work?

**Comment by 1ps0** [comment]
Welcome!

That particular message is a new one to me. Can you check your Accessibility permissions for the app? It'd be under:

> System Preferences -> Security & Privacy -> Accessibility -> BeardedSpice.app (on the right). 

The box should be checked.

**Comment by agemmell** [comment]
@1ps0 BOOM!  I had to manually add BeardedSpice to the list but that did it!

Thank you!
