### ISSUE TITLE
Incorrect information in update window

### ISSUE THREAD

**Issue by hisaac** [beardedspice/beardedspice#559]
When I updated today from 2.1.1 to 2.1.3, this is what appeared in the update dialog:

<img width="797" alt="screen shot 2017-01-07 at 9 31 55 am" src="https://cloud.githubusercontent.com/assets/923876/21742872/44c8ff64-d4bd-11e6-9dba-1662359dafc1.png">

**Comment by 1ps0** [comment]
Hey! Sorry about that. It'll happen for any upgrade from 2.1.1 or 2.1.2. The whole fiasco is documented in the original ticket at #537.

**Comment by hisaac** [comment]
Good to know! Sorry for the dupe, I searched the issues and couldn't find another one.

**Comment by 1ps0** [comment]
No worries. I wish we had a pin feature for issues. We end up hiding the useful ones just because they get fixed...
