### ISSUE TITLE
Please add Plex support

### ISSUE THREAD

**Issue by smilemantts** [beardedspice/beardedspice#56]
app support

**Comment by foozee** [comment]
am working on this :)

**Comment by christatedavies** [comment]
Awesome. Did look at possibly implementing it myself, then realised I know nothing about obj-C.

**Comment by matrixagent** [comment]
Being able to use the media keys to control the Plex web player would be incredible, can't wait for milestone 1.2!

**Comment by tarikd** [comment]
:+1:

**Comment by dewey** [comment]
Really excited for this feature!

**Comment by Stillness-2** [comment]
Funny. :) Plex Web sends the requests when you click, on next button for example:

http://www.google-analytics.com/collect?v=1&_v=j15&a=1361745755&t=event&_s=37&dl=http%3A%2F%2F127.0.0.1%2Fweb%2Findex.html&ul=ru-ru&de=UTF-8&dt=%E2%96%B6%20Etherwood%20-%20Disposition%20(feat.%20Rocky%20Nti)&sd=24-bit&sr=1440x900&vp=1324x793&je=1&fl=19.0%20r0&ec=Playback&ea=track&el=com.plexapp.plugins.library&ev=3&an=Plex%20Web&av=2.4.18&_u=eACAAE~&cid=675078499.1443483881&tid=UA-6111912-18&cd1=Plex%20Web&cd2=mn2vbaqh8j&cd3=Safari&cd4=9.0&cd5=OSX&cd6=2.4.18&z=250846309

**Comment by Stillness-2** [comment]
Think about it people! :))) Why you need it! :)))

**Comment by dbk067** [comment]
I'm not sure if I should open a new issue for this, but the Plex Home Theater native application does not seem to be supported. That would also be a nice addition.

**Comment by 1ps0** [comment]
Yep make a new issue for it. Label it app support if you can.

**Comment by dbk067** [comment]
Done, #407 - I don't seem to have permissions to add a label though.
