### ISSUE TITLE
Add support for Opera Neon

### ISSUE THREAD

**Issue by szhu** [beardedspice/beardedspice#565]
[Opera Neon](https://www.opera.com/computer/neon) is Chromium-based. Will supporting it be easy? An interesting thing to note is that Neon has a media player feature in the sidebar that does something similar, so it's not clear whether it would be easier to support it as a browser or as a desktop music app.

Similar to: #7 #368

**Comment by 1ps0** [comment]
We've had a couple requests for Chromium-based apps and browsers recently. The homepage says it would work, but the trend seems to be not. Identifying unique differences and valuable components would help with an adaptation. I'll add it to the list ;)

**Comment by szhu** [comment]
Hello, I'll be closing this issue, since Opera Neon doesn't seem to have been updated beyond its initial release, and I don't use it anymore. I'll be happy to reopen this if anyone still has this request.
