### ISSUE TITLE
Play/pause not working on 2.1.3

### ISSUE THREAD

**Issue by kylechadha** [beardedspice/beardedspice#571]
Player controls stopped working after an update about a week ago. Tried to update again today (now on 2.1.3), and the controls still do not work.

If I have the beardedspice preferences window active, player controls start working again. 45 seconds after I close the window, they stop working again.
<img width="424" alt="screen shot 2017-01-19 at 1 22 07 pm" src="https://cloud.githubusercontent.com/assets/6132480/22119638/5ac0a6dc-de4a-11e6-90a4-b7a6f9f8f6f3.png">

Clicking on the tray icon shows "no application tabs open" for a few seconds before showing my application tabs, with the active window correctly selected. Even after the application tabs correctly display, the player controls do not work.
<img width="364" alt="screen shot 2017-01-19 at 1 23 22 pm" src="https://cloud.githubusercontent.com/assets/6132480/22119679/77fa287c-de4a-11e6-8c24-4aca150cff6f.png">

<img width="355" alt="screen shot 2017-01-19 at 1 21 37 pm" src="https://cloud.githubusercontent.com/assets/6132480/22119656/65e19062-de4a-11e6-985e-7472f1f1956a.png">

Happens across websites (DI.FM, soundcloud, etc).

Mac version El Capitan 10.11.6

**Comment by 1ps0** [comment]
Which browser, and how many tabs do you have open?

**Comment by kylechadha** [comment]
Chrome Version 55.0.2883.95 (64-bit)

I have perhaps 20 tabs open, with 3 eligible for bearded spice

**Comment by 1ps0** [comment]
This might be silly to say, but when was the last time you restarted all the things (browser, BS, OSX, etc) ...?
It's also possible that you have another app fighting BS for listening access to the various system notifications.

**Comment by kylechadha** [comment]
Umm... could've sworn I restarted a couple days ago, but just did it now and it seems to be working. Whooops... embarrassed :sweat_smile:

**Comment by 1ps0** [comment]
haha happens to the best of us. It's the best kind of outcome. Too easy these days to forget the always-on mac needs to be reset every so often.
Cheers!
