### ISSUE TITLE
Add support for NPR One

### ISSUE THREAD

**Issue by adiron** [beardedspice/beardedspice#574]
Hello there!

I like bearded spice, first of all. Thanks for making a wonderful piece of software.

Aside for that, I use NPR One quite a lot on the desktop, and I think it would be really great if bearded spice supported it.

Player URL: http://one.npr.org

**Comment by 1ps0** [comment]
I'm honestly surprised it hasn't been added already :tada:

**Comment by 1ps0** [comment]
... and that was a surprisingly easy player to dissect. If you do Compatibility Updates you should be able to pull down the new strategy (ad37cc0) :)

**Comment by adiron** [comment]
Jesus, that was fast. Thanks a lot!

**Comment by 1ps0** [comment]
It comes down to how easy a site makes it to access core functions/data. In many cases simply finding an `audio` tag is enough for 40% completion. One of my bigger TODO items is to have a heuristic driven system for sites that aren't explicitly part of the plugin.
