### ISSUE TITLE
Need an app icon

### ISSUE THREAD

**Issue by williamw** [beardedspice/beardedspice#58]
I made this icon to use for myself. Thought I'd share... :) Image is copy-righted by "artistically" manipulated enough, plus obviously a satire, that it should be safe to include as the default app icon if desired.
![beardedspiceicon](https://cloud.githubusercontent.com/assets/492867/3572305/77e03f7a-0b66-11e4-8d7f-402895ef6b27.png)

**Comment by Duros** [comment]
Haha, I like the black n white one.

**Comment by foozee** [comment]
Thanks @williamw much appreciate ur work there, we now have an icon though :) any UI feedback on the app is still very welcome though.

**Comment by austin-guevara** [comment]
Hey folks, just shared a new concept in #1 – would love to get feedback from the community. Thanks!
