### ISSUE TITLE
Pandora update breaks BeardedSpice integration

### ISSUE THREAD

**Issue by rudmer90** [beardedspice/beardedspice#582]
Pandora recently completely revamped their UX, and that has broken BeardedSpice.  The play/pause/skip media keys no longer have any effect.

![screenshot 2017-02-10 13 07 00](https://cloud.githubusercontent.com/assets/2313791/22844206/d8a58a88-ef91-11e6-8d0b-4ec65108ac6e.png)

**Comment by 1ps0** [comment]
Have you tried running compatibility updates? We had an update recently also it for the new UI.

**Comment by rudmer90** [comment]
Ah, I didn't know there were two types of updates.  That solved my issue.  Thank, @1ps0.

**Comment by koppieesq** [comment]
If anyone else shows up here because Pandora stopped working on Chrome again, the solution is here: https://github.com/beardedspice/beardedspice/wiki/Won't-work-issue-after-Chrome-Update-(68.0.3440.75-and-later)
