### ISSUE TITLE
[2.2.0] New Release issues.

### ISSUE THREAD

**Issue by 1ps0** [beardedspice/beardedspice#584]
Please put any issues related to the recent 2.2.0 release here. Thanks.

**Comment by tmska** [comment]
Hi, I noticed some issues with the remote. I put a post few sec. ago. Thanks

**Comment by nerdpad** [comment]
Can't get track info anymore, opened an old issue https://github.com/beardedspice/beardedspice/issues/516

**Comment by drobati** [comment]
My media keys (sans volume) are no longer working with iTunes. I opened spotify, and there doesn't seem to be a problem.

BeardedSpice 2.2.0
iTunes 12.5.5.5
Spotify 1.0.42.151.g19de0aa6

I did notice, that the preference section didn't mention the keys to be bound? 

[image](http://imgur.com/a/qTozZ)

Couldn't remember what they looked like in older releases. I'm thinking it's possible that the media keys reacting to spotify has nothing to do with BeardedSpice.

I tried rebinding them but it didn't seem to recognize the keys.

**Comment by 1ps0** [comment]
We've seen that issue a couple times, it seems to happen because of an upgrade or some conflict with the keybindings being done by another app. Glad you were able to resolve it, not sure we can do much about it right now otherwise.

**Comment by drobati** [comment]
Yes it does seem that it showed up after upgrading beardedspice.

**Comment by 1ps0** [comment]
Closing this ticket, since I think we've passed the initial phase of critical response errors. 

Thanks everyone! I'll be putting out the next patch (`2.2.1`) asap.
