### ISSUE TITLE
Doesn't work with web

### ISSUE THREAD

**Issue by Rav4uk** [beardedspice/beardedspice#588]
Hello! It work great with iTunes (Native), but it doesn't see web. Please help.
![2017-02-19 03 34 06](https://cloud.githubusercontent.com/assets/7027387/23098040/d80db0ea-f654-11e6-9cbe-b811606e9550.png)

**Comment by 1ps0** [comment]
Check the [wiki](https://github.com/beardedspice/beardedspice/wiki/Wont-Work-issue-after-Safari-Update-(9.1.1-and-later)).

**Comment by Rav4uk** [comment]
Thanks!
