### ISSUE TITLE
Not seeing the song name in menu bar icon's list for Saavn.com

### ISSUE THREAD

**Issue by mohakshah** [beardedspice/beardedspice#594]
Currently, the media strategy for Saavn.com doesn't provide song details (title, artist, etc.). So I edited "Saavn.js" file inside my app bundle to return current track's title and album. This seemed to work fine with the play/pause notifications.
![bearded spice notification](https://cloud.githubusercontent.com/assets/1791464/23342668/7d35426a-fc84-11e6-8cdf-658c282a78f7.jpg)

But when I click on the menu bar icon, in the list of services, I see the title of Saavn.com's web page instead of the track title. 
![bearded spice menu](https://cloud.githubusercontent.com/assets/1791464/23342687/cf0f7d58-fc84-11e6-9727-c427bb746ea6.jpg)

Is there any way to display track title instead of the web page title? Do I need to re-compile with the updated .js?

**Comment by 1ps0** [comment]
You shouldn't need to recompile. If you updated the `.js` file, just increase the version and `import` it using the button at the bottom of the Preferences panel.

**Comment by mohakshah** [comment]
> You shouldn't need to recompile. If you updated the .js file, just increase the version and import it using the button at the bottom of the Preferences panel.

That's strange. I did all that and I'm still getting the same results. Notifications show the song details, menu bar icon doesn't.  [Here's my updated .js for your reference](https://gist.github.com/mohakshah/be79b904c9572a1fd7c972aca4030111).

Btw, I should have mentioned earlier that I'm using version 2.2.0.

> ... and then maybe submit a Pull Request so everyone can get the updated strategy :)

Certainly 😀

**Comment by mohakshah** [comment]
O.K., my bad. Turns out the menu bar list is supposed to show the title of the tab. The reason for my confusion was the website I was testing against (soundcloud). It set its window title to the title of the current track where as Saavn did not.

**Comment by 1ps0** [comment]
We can still work around it. Your PR was a step in the right direction. I'm working on a larger refactor, I'll see what I can do along those lines in general. It seems a valuable feature for sites that dont do it by default.
