### ISSUE TITLE
[App Support] SiriusXM

### ISSUE THREAD

**Issue by jonathanlaniado** [beardedspice/beardedspice#595]
Any update on this?

See: https://github.com/beardedspice/beardedspice/issues/438

**Comment by 1ps0** [comment]
I think I have my hands full for the moment, it'd be up to you or someone else to build it for the moment. With the PR in hand though, it wouldn't take long to make it live.

Also in the future please don't open duplicate tickets. They're counterproductive (among other things, you lose the conversation in the noise of related threads). If you want to support/bump a ticket, I check through comments daily on my Dashboard, and +1-ing the ticket will increase the chance it'll get handled sooner.
