### ISSUE TITLE
Downloaded on work computer and due to IT settings i wasn't able authorize and now my media keys dont work in itunes - help!

### ISSUE THREAD

**Issue by ksmyth08** [beardedspice/beardedspice#602]
Hi,

I downloaded this app on my work computer yesterday but when i opened it i wasn't able to give it access because the security settings are locked by our IT department.  But now my play/pause, fast forward, and rewind buttons at the top of my mac keyboard don't work with itunes anymore or at all.   Do you know why or how to fix this?    

Thanks

**Comment by 1ps0** [comment]
I think i saw this issue and was able to replicate it elsewhere. Silly question, have you tried restarting the computer?

**Comment by 1ps0** [comment]
Closing this barring any further updates from @ksmyth08
