### ISSUE TITLE
Cannot record media keys as shortcut

### ISSUE THREAD

**Issue by gabrielecirulli** [beardedspice/beardedspice#606]
After noticing I'm unable to skip to the next song even when a SoundCloud tab gets recognised correctly, I checked the settings and found that the media key shortcuts are gone:

![preferences 2017-03-05 3 pm-11-46](https://cloud.githubusercontent.com/assets/886011/23587964/0ec4ee3e-01b6-11e7-9a6c-ff2ee9e6ef10.png)

Unfortunately, I'm unable to record them, because pressing the media key won't get recognised as a keypress. Only holding fn and pressing the same key works, but that records the F-key (e.g. F8) rather than the corresponding media key.

I was unable to find a way to reset these settings, either via the app or by browsing Application Support for relevant config files. Restarting the app also didn't help.

I cannot determine if this issue was introduced by in the latest version. I'm using a MacBook Pro with macOS Sierra, 10.12.3. Neither the keys in the integrated keyboard nor the ones on an external keyboard work.

**Comment by gabrielecirulli** [comment]
It works now, for some reason. The shortcuts haven't changed, but the media keys respond. Restarting either Safari or BeardedSpice might be what caused it to work.

**Comment by 1ps0** [comment]
@gabrielecirulli I'm gonna tack this onto my list of ongoing potential problems, but close the issue. If you have any more details you want to add, please do. It'll probably help me pin down the issue.

**Comment by tienthanh8490** [comment]
I faced the same issue as well on macOS Sierra 10.12.5 . Suspected that the media keys may be intercepted by my preinstalled VOX media control preference panels, I disabled it and the media keys immediately worked for BeardedSpice. Still could not record shortcut but doesn't matter much since the default media keys works anyway.

**Comment by Stillness-2** [comment]
Media keys work by defaults, and there is no way turned off them in Preferences. Player Control Shortcuts work like additional possibility to control, if you want to use other key combinations.

**Comment by gabrielecirulli** [comment]
This issue seems to be present in the latest version as well. I'm using a 15" MBP with Touch Bar (mid-2017). I followed these steps:

 - Installed BeardedSpice
 - Granted BeardedSpice Accessibility control and restarted it
 - Updated Chrome to version 62 and restarted it

At this point, I found myself trying to do the same thing I described in this issue. My Touch Bar's media keys were not having any effect even though BeardedSpice was recognizing the SoundCloud tab in Chrome. I couldn't record a shortcut to the Touch Bar media keys, so I tried a random shortcut (Cmd-E) instead and it worked.

It took restarting BeardedSpice once more to make the Touch Bar Media Keys respond. They seem to work correctly now. 

As a simple workaround, I'd suggest BeardedSpice tells the user to restart once more during the installation process so as to avoid this issue, which may be very hard for someone to troubleshoot.

**Comment by devinrhode2** [comment]
Wouldn't work with open.spotify.com/mac os 10.13.6/chrome 71.0.3578.80 (Official Build) (64-bit) (or the previous chrome version, 70.0.3538.110 (Official Build) (64-bit))

Tried restarting BeardedSpice a few times, and nothing. When BearedSpice is not open, play/pause open iTunes, when it is open, nothing happens (So BeardedSpice is intercepting the media keys, but not finding my tab in chrome, it won't even pause the music when it is playing, and being the active tab didn't help either)

**Comment by devinrhode2** [comment]
Also restarted entire machine, so don't think it's going to work
