### ISSUE TITLE
Eats keys, causes accent picker popup, when using BT keyboard

### ISSUE THREAD

**Issue by wmertens** [beardedspice/beardedspice#609]
My [BT keyboard](http://waytools.com) has been acting oddly lately, and I finally realized it was due to beardedspice.

Basically, when I type fast, some keys will not end up on-screen, and sometimes the accent picker (the one that shows up when you hold a vowel key for a while) pops up for a letter. The very odd thing about the latter is that normally that picker only shows when key repeat is triggered, which takes a while, but in my case it pops up while I'm typing a word, eating the letter that it pops up for.

Come to think of it, the picker is not available for all keys, so maybe when a key is eaten without a popup showing, it was a consonant without accents.

I have no idea why this happens, because the built-in keyboard works fine.

Is there anyone with a Bluetooth keyboard that can confirm this problem on their hardware? I type about 50-60 wpm, so not that fast.

**Comment by 1ps0** [comment]
I've noticed similar behavior when streaming audio to a speaker. Can you confirm its more than just the BT keyboard? This seems like a systemic problem, and I'd like to nail it to the wall as thoroughly as possible.

**Comment by wmertens** [comment]
This is still present in 10.12.3, although it doesn't seem to be as prevalent.

I cannot reproduce it at all on the built-in keyboard, only via my TextBlade keyboard. I also have an Apple BT keyboard and it doesn't seem to trigger the issue either. I tried uninstalling some things, now I pretty much have only Apple kernel extensions installed, and beardedspice is the only thing that triggers the issue 😢

**Comment by wmertens** [comment]
Still happening in High Sierra…

**Comment by 1ps0** [comment]
I haven't toked to High Sierra yet, but from my current working knowledge it's just a matter of finding the time to isolate the cause. I should have more within the next few weeks.

**Comment by wmertens** [comment]
…and this magically resolved itself in one of the last macOS releases. 🤷‍♂
