### ISSUE TITLE
Opera browser support

### ISSUE THREAD

**Issue by mdthompson2001** [beardedspice/beardedspice#610]
I prefer Opera over Chrome on mac so I would appreciate if you could add support for the Opera browser. Thanks! 😀

**Comment by 1ps0** [comment]
Take a look at #96. We've been looking at and keeping an eye on the other browsers, its theoretically doable normally but the normal BS way wouldn't really be applicable. And it'd be messy. 
I'm still in the process of consolidating what we have into a more extensible platform, in the meantime I'll keep the ticket updated as I find ways to make progress :)
