### ISSUE TITLE
Set Active Player Window if there is only one

### ISSUE THREAD

**Issue by tomaskavalek** [beardedspice/beardedspice#612]
There is no function to set active player window, when there is just only one, or I don't know where.

For example: I have Spotify and Youtube, when I close Youtube tab in Chrome, I await that Spotify has automatical active flag. But nothing happen and I have to activate Spotify manually.

**Comment by 1ps0** [comment]
I noticed this in my refactor build, thanks for pointing it out in live. I'll see how hard it'll be to patch and hopefully get it out with `2.2.2`.

**Comment by tomaskavalek** [comment]
Thanks.
