### ISSUE TITLE
[App Support] BBC iPlayer Radio

### ISSUE THREAD

**Issue by smilinggoat** [beardedspice/beardedspice#619]
I see "BBC Radio" is listed as supported but it doesn't seem to work with the Essential Mix at least.
e.g. http://www.bbc.co.uk/programmes/b08hlcy0
Thank you! #

**Comment by bpollman** [comment]
This has been bothering me too. it works with radio but not 'programmes' of streamable on demand content. I just got a MediaStrategy plugin working for it this afternoon. If it continues to work well over the next day or so I'll submit it to the project

**Comment by bpollman** [comment]
#649 Pull request with support

**Comment by caleuanhopkins** [comment]
Can confirm this is working, at the expense of Spotify and others:

![screen shot 2017-06-19 at 12 57 12](https://user-images.githubusercontent.com/1164525/27284018-db8e5c3a-54ee-11e7-88ba-f7d9540d4c71.png)

Maybe worth closing this one off

**Comment by 1ps0** [comment]
I think this is related to the CSP issue that keeps appearing. Marking as 'fixed' and will keep an eye on it.
