### ISSUE TITLE
How do I uninstall BeardedSpice on mac?

### ISSUE THREAD

**Issue by powder366** [beardedspice/beardedspice#627]
How do I delete all the related files and uninstall BeardedSpice on mac.
Also in System Preferences, Notifications there is and entry (where do I remove this on disk, not possible in the GUI).

**Comment by 1ps0** [comment]
Aside from the application itself, the only files I'm aware of are in `~/Library/Application Support/BeardedSpice`. And that's just for the strategies, downloaded and preloaded.

**Comment by powder366** [comment]
How about a deinstall instruction

**Comment by 1ps0** [comment]
I'll add it to the TODO list.

**Comment by powder366** [comment]
Great Thanks!
