### ISSUE TITLE
Issues with 10.12.4 and headphone controls

### ISSUE THREAD

**Issue by Paschalis** [beardedspice/beardedspice#629]
# Issue
It seems that BeardedSpice is sending correctly the toggle `Play/Pause` command to the active application, i.e. Youtube, Play Music, iTunes etc. However, another request is sent to the `iTunes` application.
So, if I am using `iTunes` (the active BeardedSpice app is `iTunes`) then it is toggled twice.
If not, then the active application is toggled once, and another `Play/Pause` command is also sent to `iTunes`. If `iTunes` wasn't running it will run, otherwise `Play/Pause` is toggled.

I guess BeardedSpice is no longer  properly `catching` the `Play/Pause` request, so the `OS` is sending another request to the `iTunes` application.

# Examples

**1. Playing a local mp3 using iTunes:**
When iTunes track is paused, and I press the `play` button on the headphones, it starts and then stops almost immediately. As if I pressed the button twice quickly.
![playing](https://cloud.githubusercontent.com/assets/1271164/24875961/9183feb2-1e32-11e7-95ff-0f927a0f5595.gif)

**2. Pausing a local mp3 using iTunes:**
When a local mp3 is playing through iTunes and I press the `play` button on the headphones, it stops and starts almost immediately. As if I pressed the button twice quickly.
![pausing](https://cloud.githubusercontent.com/assets/1271164/24875952/89338552-1e32-11e7-8b25-5a1094f50115.gif)

**3. Start/Pause a youtube video (while having open iTunes):**
When pressing the headphones `play` button, the Youtube video will toggle start/pause correctly.
However, it will also toggle iTunes.

e.g. if youtube video was playing, and itunes was paused, and BeardedSpice had first as first choice the Youtube video (assume I opened it last), then: youtube will pause, and itunes will start playing. Both will happen simultaneously.

**4. Start/Pause a youtube video (with iTunes closed):**
Youtube video will toggle correctly, but iTunes will open. After installing the [itunes-patch](https://thebitguru.com/projects/itunes-patch) this case seems to be working okay (as long as itunes isn't running, even in the background).

# NOTES:
- These problems appeared after I upgraded to `10.12.4`. Earlier everything was fine.
- When using a keyboard shortcut it works as normal. My keyboard does not have dedicated media buttons, so I mapped e.g. `F14` to `Play/Pause` actions using another great plugin (like this one) called, `BetterTouchTool`.

# Configuration
macOS version:  10.12.4
BeardedSpice version: 2.2.1 (25)

**Comment by 1ps0** [comment]
I've heard of several quirks for `10.12.4`, such as sudo not working. I haven't had a chance to test this on my up-to-date machine, but will keep an eye out for it. The details are very helpful.

**Comment by choco** [comment]
Just wanted to add that this is still an issue on 10.12.5

**Comment by 1ps0** [comment]
Just a quick followup. This hasn't been lost to the wind, just busy and lots of other higher priority issues to address :)

**Comment by fodaveg** [comment]
still on 10.12.6. anyone has tested this issue on 10.13 beta?

**Comment by MVermue** [comment]
I am having this issue on 10.13 with Spotify as well
