### ISSUE TITLE
New Spotify design is not detected

### ISSUE THREAD

**Issue by AAverin** [beardedspice/beardedspice#631]
Spotify have re-designed their web-app, and it no longer works with BeardedSpice

**Comment by rsommerard** [comment]
This issue can be closed :)

**Comment by Dachaz** [comment]
For me it has never started working on the new design, even though I've downloaded the latest compatibility updates:

<img width="1440" alt="screen shot 2017-06-23 at 11 35 37 2" src="https://user-images.githubusercontent.com/124358/27476236-3de27d5a-5808-11e7-9695-7f837539d0a2.png">

Help?

**Comment by rsommerard** [comment]
It does not work anymore for me too, but it worked a time.
It seems that the spotify tab is not anymore detected by BeardedSpice.

@1ps0 have you any clue about why the tab is not well detected?
