### ISSUE TITLE
Spotify Web Player[App Support]

### ISSUE THREAD

**Issue by drootstein** [beardedspice/beardedspice#632]
Hi,

Is there an update coming soon to fix the issues caused by the Spotify web player changes?

Thanks.

Darren

**Comment by 1ps0** [comment]
Can you provide more detail? 

Stuff like:

- OSX version
- Browser used
- BeardedSpice version
- did you double check the [Safari FAQ](https://github.com/beardedspice/beardedspice/wiki/Wont-Work-issue-after-Safari-Update-(9.1.1-and-later))?
- double check you have Accessibility enabled for BeardedSpice (and maybe toggle it)?

**Comment by 1ps0** [comment]
Actually, looks like @AAverin beat you to the punch with #631. We'll move forward from there, thanks :)
