### ISSUE TITLE
Synology strategy is causing errors in navigator

### ISSUE THREAD

**Issue by xavhan** [beardedspice/beardedspice#637]
https://github.com/beardedspice/beardedspice/blob/master/BeardedSpice/MediaStrategies/Synology.js#L12

BaseURl is not a defined global in chrome. (poke @jhuebsch)
Causing this kind of errors: 

![capture d ecran 2017-04-20 a 13 46 28](https://cloud.githubusercontent.com/assets/1308790/25229230/c9fe1224-25cf-11e7-8c30-cf061e831d42.jpg)

**Comment by jhuebsch** [comment]
That is odd, I'm unable to replicate. I'm able to fully control playback, pause, previous, next with my media keys without any errors appearing in the Chrome console. 

I've tested on my Synology Audio Station (6.0.2-3093) and the[ live demo](https://www.synology.com/en-us/dsm/live_demo) Synology Audio Station (also 6.0.2-3093) with Chrome Version 58.0.3029.81 (64-bit) MacOS.

**Comment by jhuebsch** [comment]
I see the issue. The error occurs on other sites when BeardedSpice checks their baseURL. I'll try and figure out a better check, any suggestions?

**Comment by xavhan** [comment]
I did something similar with bandcamp https://github.com/beardedspice/beardedspice/pull/546

**Comment by jhuebsch** [comment]
@xavhan could you test my pull request https://github.com/beardedspice/beardedspice/pull/638, thanks.

**Comment by 1ps0** [comment]
@xavhan @jhuebsch  I totally didnt recognize that this was more than just on the synology page. Breaking all the things. Check the fix now, its live.

**Comment by xavhan** [comment]
@1ps0 thanks, it seems to work.
