### ISSUE TITLE
Release a new version with the updated Spotify web player strategy

### ISSUE THREAD

**Issue by deboj** [beardedspice/beardedspice#640]
Since the Spotify Web Player changed, there has been a PR merged that looks to enable the new UI to work with beardedspice https://github.com/beardedspice/beardedspice/pull/636

When can we expect a proper release that includes this update?

**Comment by 1ps0** [comment]
It's live, have you run compatibility updates?

**Comment by 1ps0** [comment]
@deboj Assuming you read this and just didn't followup. Please reopen if it's different from the fix indicated.

**Comment by deboj** [comment]
i run compatibility updates and it still doesnt find my spotify tabs....

**Comment by deboj** [comment]
and i can't find any instructions in your readme or wiki on how to actually work the import functionality...

**Comment by 1ps0** [comment]
@deboj Are you running Chrome 58 and/or OSX 10.12.4? I recently put out a pre-release that fixes Chrome 58 support (https://github.com/beardedspice/beardedspice/releases/tag/v2.2.2-b1). Can you let me know if that helps?

**Comment by deboj** [comment]
mac version 10.11.6
chrome version 58.0.3029.96

but it still works on other sites like youtube, etc.
i will try this prerelease and comment

**Comment by deboj** [comment]
ok that pre-release candidate works - thank you!

**Comment by deboj** [comment]
okay it decided to update itself and it doesnt work anymore. i have tried checking for compatibility updates. please can you make whatever prerelease version that works into a real release version? i should not have to rely on a prerelease when it decides to update itself and breaks

**Comment by deboj** [comment]
i see on your releases page that you rolled back the change because it breaks other things. releasing this as a patch version breaks semantic versioning as it breaks me also, when upgrading to a patch version should be backwards compatible

**Comment by deboj** [comment]
im uninstalling this tool
