### ISSUE TITLE
Not Working with Web Apps

### ISSUE THREAD

**Issue by ksherman777** [beardedspice/beardedspice#641]
For the last few days, it is now only able to control itunes and Spotify on my mac. Won't work with anything in Safari or Chrome. Youtube, Soundcloud, etc. don't show up as available windows, and every time I hit "command + F8" to set as active window, Beardedspice shuts down. Any idea why this might be happening?

I have "allow java from apple events" enabled in Safari. I have Safari 10.1 (although had to tweak it in order to function with Safari Stand so it says "10.0.1" but it really isn't). Chrome version 58.0.3029.81

**Comment by 1ps0** [comment]
It's a Chrome 58 thing. Working on it. For now, I'm going to lump this in with #639.

**Comment by ksherman777** [comment]
Ok, it is actually working in Chrome for me (both soundcloud and youtube), but it is not working when those sites are being used in Safari. Thanks for your help!
