### ISSUE TITLE
[2.2.2] New Release Issues

### ISSUE THREAD

**Issue by 1ps0** [beardedspice/beardedspice#651]
Please put any issues related to the recent `2.2.2` release here. Thanks.

**Comment by purevertigo** [comment]
Chrome still not working for YouTube (yes I am using Beta but prior to chrome 58 working great)

**Comment by pietrodn** [comment]
I'm not able to control Deezer via web (Google Chrome 58.0.3029.110) with BeardedSpice 2.2.2.
BeardedSpice 2.2.1 works fine.
Could it be this change? https://github.com/beardedspice/beardedspice/commit/5c8ec0699c872a8749bb7b81a131074681e18d38

**Comment by MGHollander** [comment]
I experience the same problem as @pietrodn. Media keys and Player Control Shortcuts don't work. Safari does work.

**Comment by patrickrushton** [comment]
Not working with Spotify Web Player in Safari (tbh not sure if it worked in the previous version)

**Comment by minurmi** [comment]
Spotify Web Player doesn't work for me either in Safari. However, Chrome 58.0.3029.110 and Spotify Web Player work fine as does e.g. Youtube in Safari.

I'm running macOS 10.12.4, Safari Version 10.1 (12603.1.30.0.34) and BeardedSpice  2.2.2. I've also gone thought the [quick troubleshooting FAQ](https://github.com/beardedspice/beardedspice/wiki/Troubleshooting) without success.

**Comment by Stillness-2** [comment]
@1ps0 Right now I found that 
`[(SafariApplication *)self.application.sbApplication doJavaScript:javascript in:self.tab];` (https://github.com/beardedspice/beardedspice/blob/master/BeardedSpice/Tabs/SafariTabAdapter.m#L44)
can't return dictionary on Safari 10.1 (12603.1.30.0.34) :) 
This leads to that all `trackInfo` broken, as minimum.

**Comment by nVitius** [comment]
@pietrodn the Deezer strategy is fixed in #643. It just needs to be merged in. I've tested it on 2.2.2

**Comment by Stillness-2** [comment]
@pietrodn Yes, it is this commit :)

**Comment by Stillness-2** [comment]
@pietrodn Yes, It is this commit

**Comment by 1ps0** [comment]
@nVitius @pietrodn Deezer strategy has been fixed. Please run Compatibility Updates.

**Comment by pietrodn** [comment]
Thanks @1ps0, now Deezer works perfectly with Chrome and BeardedSpice 2.2.2. :)

**Comment by Stillness-2** [comment]
About `trackInfo` in Safari - fixed 76ead5a

**Comment by Stillness-2** [comment]
Commit for rollback CSP hotfix in Chrome https://github.com/beardedspice/beardedspice/commit/a4bd7e908a222baf3d2d65b0b3fda2fda9fa1209
