### ISSUE TITLE
Hype Machine broken

### ISSUE THREAD

**Issue by eexit** [beardedspice/beardedspice#657]
Hello,

It's been a while since I haven't been on [Hype Machine](http://hypem.com) but BS doesn't seem to map any command anymore.

- macOS 10.12.4
- Google Chrome 58.0
- BS 2.2.2

Thanks,

**Comment by 1ps0** [comment]
What version of BS? We recently pushed a fix for Chrome 58 that was blocking all site strategies.

**Comment by eexit** [comment]
@1ps0 Sorry, I forgot to mention that: `2.2.2`.

**Comment by Stillness-2** [comment]
@1ps0 `window.togglePlay()`- strategy uses a global object

**Comment by Stillness-2** [comment]
resolved in a4bd7e9
