### ISSUE TITLE
Amazon Prime Music Not Working

### ISSUE THREAD

**Issue by chrishough** [beardedspice/beardedspice#663]
Recently I have been unable to control amazon music in chrome.  Thoughts?

**Comment by 1ps0** [comment]
What version of BS/OSX/Chrome/safari are you using?

**Comment by chrishough** [comment]
Chrome: Version 58.0.3029.110 (64-bit)
OSX: 10.12.5

**Comment by Stillness-2** [comment]
resolved in a4bd7e9
