### ISSUE TITLE
Separate repository for MediaStrategies?

### ISSUE THREAD

**Issue by Coder-256** [beardedspice/beardedspice#670]
Would it be possible to move all of the MediaStrategies to a separate repository and include them as a submodule? That way, you could have separate pull requests and issues for the main app and the individual websites, and other projects could use the MediaStrategies easier. This is also related to a different issue I just submitted (#668).

**Comment by 1ps0** [comment]
I like this idea, but I dont' have the power to implement it.

**Comment by Coder-256** [comment]
@Stillness-2 then I'm guessing that you do? What do you think?

**Comment by 1ps0** [comment]
@Coder-256 It seems like this is slightly outside of our ability to follow through on. I'll keep an eye open but going to close the ticket barring any kind of real change.
