### ISSUE TITLE
Key binding – action keys with Fn

### ISSUE THREAD

**Issue by tomaskavalek** [beardedspice/beardedspice#672]
After update, I can't bind keys with Fn – I use special function as Fn + KEY, and without it as F1–F12.

I can only assign key without Fn, but – in this case App listen on both – with Fn, and without Fn, it's same, and this is a problem.

**Comment by Coder-256** [comment]
Did you try toggling "Use F1, F2, etc. keys as standard function keys" in Keyboard preferences?

**Comment by tomaskavalek** [comment]
Yes. I tried. But no effect.

**Comment by Coder-256** [comment]
Please give the following:

- What keyboard are you using? (ex. laptop keyboard, usb keyboard, etc.)
- What is your macOS version and BeardedSpice version?

Also, please try this:

1. Restart your computer.
2. Quit BeardedSpice.
3. Remove `~/Library/Preferences/com.beardedspice.BeardedSpice.plist`. Note that this will delete your settings, so you may want to back this file up first.
4. Reopen BeardedSpice.

**Comment by tomaskavalek** [comment]
Please give the following:

- What keyboard are you using? (ex. laptop keyboard, usb keyboard, etc.) – Both, same problem. 
- What is your macOS version and BeardedSpice version? - Sierra 10.12.5, BeardedSpice 2.2.3

Also, please try this:

1. Restart your computer.
2. Quit BeardedSpice.
3. Remove ~/Library/Preferences/com.beardedspice.BeardedSpice.plist. Note that this will delete your settings, so you may want to back this file up first.
4. Reopen BeardedSpice.

I did it, but nothing changed.

My keyboard preferences are in attached file.

<img width="605" alt="screenshot 2017-06-06 10 52 19" src="https://cloud.githubusercontent.com/assets/210119/26821335/5eac80ae-4aa6-11e7-808d-f0beb9dfeb9a.png">

I am not able to assign shortcut as Fn + F8, for example.

**Comment by tomaskavalek** [comment]
Solved with removing all Player Control Shortcuts – it seems that in this case BeardedSpice use system keys.
