### ISSUE TITLE
Intermittent failiure with Chrome & SoundCloud

### ISSUE THREAD

**Issue by felixturner** [beardedspice/beardedspice#674]
Recently BeardedSpice fails most of the time when trying to play/pause with Chrome & Soundcloud. Is this a known issue?

When I restart BS, it will work for a while, but after a while it will lose the connection. The name of the current track will show in the BS menu, but play / pause doesn't work. Sorry I don't have a better repro. I have latest OS X , Chrome, BS (2.2.3).

**Comment by 1ps0** [comment]
What version of Chrome? If it's `59` I'd suggest you downgrade BS to v2.2.2 (https://github.com/beardedspice/beardedspice/releases/tag/v2.2.2)

**Comment by 1ps0** [comment]
@felixturner Closing this unless the issue persists. Thanks.

**Comment by simonsmith** [comment]
Ran into exactly the same issue, using Chrome 61. Downgrading to `2.2.2` has indeed fixed it. If I can provide any additional debugging information please let me know

**Comment by 1ps0** [comment]
This answers and supports several questions. I dont have a lot of time currently to dev on this, but I have a plan and will apply it as soon as the time is free :)

**Comment by felixturner** [comment]
Downgraded to 2.2.2, but the problem persists. For some reason BeardedSpice not working is way more frustrating than it should be. Let me know if there is anything that I can help with!

**Comment by simonsmith** [comment]
@felixturner If you open BeardedSpice preferences does it start working again?

**Comment by felixturner** [comment]
>If you open BeardedSpice preferences does it start working again?

yes.

**Comment by simonsmith** [comment]
Yeah I get the same thing. Interesting to see it's not just me.
