### ISSUE TITLE
Pandora playback actions/track info not working

### ISSUE THREAD

**Issue by tysonkerridge** [beardedspice/beardedspice#677]
Just recently, Pandora playback (play/pause) and track information stopped working, though it appears to still find the Pandora tab (see screenshots). Happens with or without another application open, eg. iTunes is open also in the screenshot, however iTunes appears to still work when switching between via BeardedSpice.

macOS 10.12.5, BeardedSpice 2.2.3, Chrome 59.0.3071.109.

Just recently updated Chrome to above version, unsure what version I was on before that but it wasn't working on the previous version I had either.

Tried on Safari (v10.1.1), same issue (even with [fix for Safari on or after 9.1.1](https://github.com/beardedspice/beardedspice/wiki/Wont-Work-issue-after-Safari-Update-(9.1.1-and-later))) though I never used Safari before the issue.

Also tried going back to BeardedSpice 2.2.2 with same outcome. I don't remember BeardedSpice being updated recently so I'm thinking either Pandora itself was updated or Chrome changed in some way.

<img width="332" alt="screen shot 2017-06-21 at 3 33 22 pm" src="https://user-images.githubusercontent.com/3983116/27368725-7a28f31a-5697-11e7-8829-d9989d1ab2bf.png">

![screen shot 2017-06-21 at 3 36 34 pm](https://user-images.githubusercontent.com/3983116/27368729-7c630760-5697-11e7-8c64-61d40b8f952d.png)

**Comment by 1ps0** [comment]
Take a look at v2.2.2 and see if that resolves the issue. (https://github.com/beardedspice/beardedspice/releases/tag/v2.2.2)

**Comment by tysonkerridge** [comment]
Had already tried v2.2.2, but tried it again, along with v2.2.1 and v2.2.2-b1. All with the same issue unfortunately. As before, behaviour _seems_ to not be related to Chrome, as Safari doesn't appear to work either. 

Went through the [Troubleshooting](https://github.com/beardedspice/beardedspice/wiki/Troubleshooting) steps for those versions including checking for compatibility updates.

**Comment by hoisingtonp** [comment]
I'm also seeing this behavior on 2.2.3--BeardedSpice finds the Pandora tab, but I can't control using the media keys. My guess is that Pandora was updated recently.

**Comment by AmberJune** [comment]
Experiencing the same today; controls not working for Pandora. Tried running compatibility updates from the menu but it doesn't seem to do anything.

Bearded Spice 2.2.3
macOS 10.12.5
Chrome 59.0.3071.115

**Comment by tysonkerridge** [comment]
I ran @hoisingtonp's PR locally and it seems to fix the issue. Are changes to strategies considered compatibility updates or do they require a release?

**Comment by 1ps0** [comment]
Just pushed @hoisingtonp's PR. Closing the issue. Please comment with thumbs down if it doesnt fix for you.

**Comment by tysonkerridge** [comment]
Was just about to close this, thanks a lot @hoisingtonp for the fix, and @1ps0 for the merge 👍
