### ISSUE TITLE
Google Music updated? No longer works

### ISSUE THREAD

**Issue by christatedavies** [beardedspice/beardedspice#681]
I've noticed today that BeardedSpice doesn't seem to want to recognise Google Music as an "applicable tab" any more. 

I _think_ google music has been updated - only because I cannot upload music to it through the browser any more, I have to use some app instead :|

Coincidence? I doubt it...

Anyway, just thought I'd put it out there.

**Comment by rodweb** [comment]
The GoogleMusic strategy works for me right now.

**Comment by christatedavies** [comment]
You're right. It works for me now too. How queer... I'll close this issue!

**Comment by 1ps0** [comment]
Recent versions of chrome have been mucking with how the app talks to various websites, this seems to be an small instance of that cold/hot cycle.
