### ISSUE TITLE
No support for web apps like Soundcloud and Youtube in Safari browser

### ISSUE THREAD

**Issue by Arjunkalidas** [beardedspice/beardedspice#690]
Issue:
The BeardedSpice do not recognize the apps when opened in Safari web browser, where as the same when accessed in Chrome, shows up.

Steps to reproduce the bug:
1. Install the BeardedSpice and launch the same.
2. Configure the shortcut keys as per your preference.
3. Open up Safari browser and go to souncloud.com
4. Then click the BeardedSpice icon in finder bar
5. Repeat the same with Chrome browser

Actual Result:
The apps opened in Chrome shows up immediately in BeardedSpice, whereas the same opened in Safari do not.

Expected Result:
The BeardedSpice app as the dev team claims should seamlessly support any browser. The app is not browser agnostic at this point I believe.

**Comment by 1ps0** [comment]
Did you check the [Safari fix](https://github.com/beardedspice/beardedspice/wiki/Wont-Work-issue-after-Safari-Update-(9.1.1-and-later)) wasn't the cause?

**Comment by Arjunkalidas** [comment]
I will check and update you.

**Comment by 1ps0** [comment]
@Arjunkalidas I'm going to assume this was resolved. If not, please follow the [troubleshooting checklist](https://github.com/beardedspice/beardedspice/wiki/Troubleshooting) and make sure you've included as much version information as well when making a new ticket. 
Thanks!
