### ISSUE TITLE
Media keys not controlling the selected media (Youtube in Safari)

### ISSUE THREAD

**Issue by jasondamour** [beardedspice/beardedspice#691]
Description: Open Spotify, and youtube in safari (I have followed the safari wiki, and youtube works independently). The beardedspice toolbar shows a checkmark next to the youtube title, but the media keys still control Spotify. If I open the beadedspice preference pane, then the change seems to take effect and media keys will control youtube.

macOS 10.12.5
beadedspice v2.2.3

**Comment by eexit** [comment]
I think I have a similar issue. I have Chrome with startup option <q>Continue where you left off</q> picked and with the [FooTab](https://chrome.google.com/webstore/detail/footab/anbodogikfbehidmmjdokehphginagbb?hl=en-US) extension (it means when I launch my browser, only the current tab loads, to preserve memory). 

## Scenario

1. Launch Chrome
2. Go play some video on YouTube
3. Pause the video
4. Open some more tabs
5. Quit Chrome
6. Launch Chrome (opens with the last tab, which is not YouTube)
7. YouTube tab should not load and thus not play/resume
8. Open Google Music
9. Play some music
10. BS context menu shows Google Music as current player
11. Trigger BS Play/Pause keyboard shortcut
12. **YouTube video starts to play** while it's not the current active tab and is unloaded

BS 2.2.3
OSX 10.12.6
Chrome 59.0

**Comment by jasondamour** [comment]
this ticket is old so closing
