### ISSUE TITLE
BeardedSpice not working, tried to fix with no luck :(

### ISSUE THREAD

**Issue by Nathrelor** [beardedspice/beardedspice#713]
I just got BeardedSpice today and after installing it noticed it wasn't working like it was supposed to. I tested it with Pandora and Youtube but nothing worked. I looked up possible fixes and found #402 on this site and followed the instructions to "Allow Javascipt from Apple events". after setting that up I quit BeardedSpice, reopened it, and then tried again but unfortunately it still isn't working for me.
If someone knows how I can get it to work or at least know of a different app/program that will allow me to at least play/pause and skip songs (being able to give a song a thumbs up or down would be nice too but not necessary) on pandora using the keyboard buttons I would greatly appreciate it.
I'm using a MacBook Pro running Sierra (10.12.6) and Safari 10.1.2

**Comment by Nathrelor** [comment]
@Stillness-2 @1ps0 
Either of you know what I could do to fix this?

**Comment by 1ps0** [comment]
@Nathrelor take a look at the [troubleshooting checklist](https://github.com/beardedspice/beardedspice/wiki/Troubleshooting). 

Also, are you running any betas or variants of Safari or Sierra that aren't in the mainstream production path?

**Comment by Nathrelor** [comment]
@1ps0 
no betas or variants of safari or Sierra. I did steps 1, 4, & 5 on the troubleshooting checklist, I would have done 2&3 but I'm not sure where to go to check for compatibility updates and I'm not sure if step 3 is referring to safari updates, Mac updates, or something for beardedspice and where to go for whichever it's referring to. if you're referring to checking the App Store then the only thing I have to update is iMovie and I doubt that has anything to do with it.

**Comment by 1ps0** [comment]
Compatibility Updates is the second Update option in the app menu. It should run automatically when the app is launched unless explicitly disabled in Preferences. 

Not sure what else could be the issue except something else blocking our integration with the browser. I personally dont use Safari that much, but a quick test shows youtube working for me. It is possible another background app or browser plugin is interfering with our integration so it's difficult to say any further.

**Comment by Nathrelor** [comment]
@1ps0 what app menu are you referring to? I would never have disabled updates anyways, but I'm not sure what app menu you're referring to. also, I tried using it on google chrome as well and it doesn't work there either. I included a screenshot showing what I see for beardedspice if I click on it and what is shown in preferences. not sure if it would help at all, but I figure it doesn't hurt either.
![screen shot 2017-10-09 at 3 48 43 pm](https://user-images.githubusercontent.com/32076704/31355708-614ec8b0-ad09-11e7-8cbd-c0c17acfe6ff.png)
sorry for taking so long to respond, been a bit busy lately :/
I do appreciate you taking your time to help me with this, I just hope we are able to find a solution.

**Comment by 1ps0** [comment]
I... what? What version is that? It looks like it should be 0.1.0. Did you download the absolute latest binary? (https://raw.github.com/beardedspice/beardedspice/distr/publish/releases/BeardedSpice-latest.zip)

I think thats the root of your problem. Lets fix it! :D

**Comment by Nathrelor** [comment]
I thought I did but I guess not, lol
I'll use the version u just sent me and let you know if that works

**Comment by Nathrelor** [comment]
Works now!!! THANK YOU!!!!
I'm not sure how I ended up with the wrong version, lol
I just went with the most recent version I found.

**Comment by 1ps0** [comment]
Glad I could help. Easy fixes are the best. Enjoy!
