### ISSUE TITLE
[App Support] Pocket Casts Beta Player

### ISSUE THREAD

**Issue by Erikmitk** [beardedspice/beardedspice#725]
I just noticed that Pocket Casts has a new beta player on the web. I guess this will take over the current player, so an update might be necessary even if the beta player should not be supported.

https://playbeta.pocketcasts.com/web/

**Comment by Erikmitk** [comment]
Additionally, from the beta player settings you can download a Mac App. I guess it’s just a wrapper around the web version but I’d like Bearded Spice to deal with that too when it is available. :)

**Comment by maxexcloo** [comment]
+1 for the Desktop App

**Comment by rotspelikaan** [comment]
Came here looking for the same! 👍

**Comment by amphibian** [comment]
Would love to see this implemented for the desktop app.

**Comment by owenlejeune** [comment]
+1 for the desktop app

**Comment by kassim** [comment]
+1 for desktop app
