### ISSUE TITLE
[App Support] Pocket Casts Web Player 2.0 + Desktop App

### ISSUE THREAD

**Issue by austin-guevara** [beardedspice/beardedspice#729]
ShiftJelly recently released a [beta for Pocket Casts Web App and a native app for iOS](https://blog.shiftyjelly.com/2017/09/25/web-player-2-0-beta/). As this is the future of Pocket Casts, I would love to see support!

**Comment by ionan** [comment]
I believe this issue is the same as [this](https://github.com/beardedspice/beardedspice/issues/725).

**Comment by austin-guevara** [comment]
@ionan, you’re right! My bad for not doing a better check first.
