### ISSUE TITLE
uninstall doesnt remove function completely

### ISSUE THREAD

**Issue by yurigoytacaz** [beardedspice/beardedspice#746]
I'm having some problems even after running the uninstall.
the keyboard shortcuts for play/pause and prev/next dont seem to work if I dont make the itunes window active. is there anything I should have done besides running the uninstall? 
thanks in advance.

I had to reinstall the app and when the shortcuts dont work I run the app and let it running so the shortcuts work. but I dont want the app to be running. I really want to go back to the way things were before. I decided to ask here before having to format the system. Hope you guys can help me out.

**Comment by SamyBencherif** [comment]
Do you also happen to have [this patch](https://thebitguru.com/projects/itunes-patch) installed?

**Comment by yurigoytacaz** [comment]
@SamyBencherif no, I dont.
