### ISSUE TITLE
Chrome update breaking change

### ISSUE THREAD

**Issue by iliakarasin** [beardedspice/beardedspice#771]
On the latest updated of Google Chrome (v65.0.3325.181) Beardedspice no longer detects any tabs.

![screen shot 2018-03-22 at 3 10 43 pm](https://user-images.githubusercontent.com/89924/37801295-4b2e0f4a-2de3-11e8-8b7b-79a8f0300958.png)

**Comment by Stillness-2** [comment]
@iliakarasin Илья, что то нет уже желания разбираться, что там.. Предлагаю Вам попробовать пока поставить дебуг версию 3. :) 
https://github.com/beardedspice/beardedspice/milestone/19
https://github.com/beardedspice/beardedspice/tree/bs3

Надо поставить в хром расширение, можно это сделать в девелоп моде, ползунок в панели с расширениями.
![image](https://user-images.githubusercontent.com/12689/37960435-51a9b87c-31be-11e8-8e77-c263e6aa46ce.png)

Вот расширение: 
[BeardedSpice.chrome.zip](https://github.com/beardedspice/beardedspice/files/1851428/BeardedSpice.chrome.zip)
Вот дебуг версия  (сборка не подписана):
[BeardedSpice.app.zip](https://github.com/beardedspice/beardedspice/files/1851433/BeardedSpice.app.zip)

**Comment by eexit** [comment]
Reproduced with Chrome Canary 67.0.3390.0
BS 2.2.3 (29)

Youtube + Google Music not recognized.

**Comment by xorik** [comment]
New app crashes...
```
$ /Applications/BeardedSpice.app/Contents/MacOS/BeardedSpice
2018-07-25 14:20:07.260 BeardedSpice[97153:23915886] AccessibilityApiEnabled YES
2018-07-25 14:20:07.769 BeardedSpice[97153:23915886] error opening!: 14
...
// same 2 lines like 1000 times
...
2018-07-25 14:19:10.967 BeardedSpice[97148:23914877] Could not create database queue for path /Users/xorik/Library/Application Support/TIDAL/Local Storage/https_desktop.tidal.com_0.localstorage
2018-07-25 14:19:10.967 BeardedSpice[97148:23914877] error opening!: 14
Segmentation fault: 11
```

**Comment by caleuanhopkins** [comment]
@iliakarasin have you seen this: iPlayer works, if you're using Chrome you need to following these instructions: https://github.com/beardedspice/beardedspice/wiki/Won't-work-issue-after-Chrome-Update-(68.0.3440.75-and-later) ?

**Comment by iliakarasin** [comment]
@caleuanhopkins have indeed, doesn't change anything.
<img width="1440" alt="screen shot 2018-08-16 at 10 03 43 am" src="https://user-images.githubusercontent.com/89924/44223178-b1077b00-a13b-11e8-9d35-c77494b3bcaf.png">

**Comment by iliakarasin** [comment]
@caleuanhopkins and three hours later it starts working again! Closing this issue.
