### ISSUE TITLE
Previous and next track not working in Chrome 65 Mac 10.13.4

### ISSUE THREAD

**Issue by kleurbleur** [beardedspice/beardedspice#776]
Play/pause does work in Chrome with the above versions. 
Also, it doesn't work in Safari and Firefox at all when I wanted to double check. Everything is fine in iTunes.

**Comment by Codecomp** [comment]
Can confirm not working in Version 65.0.3325.181 with latest version of Beardspice.

**Comment by kleurbleur** [comment]
Chrome version 65.0.3325.181. Opening the chrome preferences and closing it again while bearded spice running, no dice. Vice versa same. Basically all combinations, not working. Only the play pause button works.

**Comment by Codecomp** [comment]
Opening and closing preferences or any combination of faffery makes it work on version 66.0.3359.181

**Comment by kleurbleur** [comment]
Updated to Chrome 66.0.3359.181 on 10.13.4. Also checked for updates in BeardedSpice, non available. Tried all of it again and still only play/pause functionality. 

What is this for black magic you're talking about, I want in!

**Comment by pchachoo** [comment]
Try it by leaving preferences open? Had that work for me once too. I have no clue whats going on either, just that there's spaghetti code somewhere.

**Comment by kleurbleur** [comment]
I saw a compatibility update coming in. Works again afterwards!
