### ISSUE TITLE
Youtube playlist issue

### ISSUE THREAD

**Issue by rafiron** [beardedspice/beardedspice#787]
Start/stop actions are working with youtube, but forward and backward playback buttons don't work.
I am using Chrome version 66.0.3359.139 with MacOs High Sierra 10.13.4

**Comment by ElRoberto538** [comment]
This: https://github.com/beardedspice/beardedspice/pull/790 fixes it for me, you can probably just download and import the modified .js file to resolve it before the fix gets merged.

**Comment by rafiron** [comment]
Tried with youtube.js v3 file you've referenced in the PR but it doesn't seem to work. I tried restarting app to get the reloaded configurations, but its doesn't seem to be working.

**Comment by ElRoberto538** [comment]
Weird, works perfectly for me without even restarting anything (I'm using it right now), I also have the same Chrome and macOS version. Could you open the javascript console and try running the next command? ```document.querySelector('#movie_player').nextVideo()```. Also could you link me a (SFW) playlist to check?

**Comment by rafiron** [comment]
If I directly run the javascript in console it's working. In console when I'm trying out with media keys, I'm getting `null` when doing `document.querySelector('yt-player-manager').player_` and then `nextVideo()` call fails.

**Comment by ElRoberto538** [comment]
Ok that sounds right - could you export and paste here the contents of youtube v3 from BeardedSpice? It sounds like it didn't import correctly.

**Comment by rafiron** [comment]
Have changed file extension to .txt to enable github to allow uploading it.

[youtube.bsstrategy](https://github.com/beardedspice/beardedspice/files/2015399/youtube_bsstrategy.txt)

**Comment by ElRoberto538** [comment]
Ok - well that's correct, sorry I probably can't help from here - might need someone more experienced with BeardedSpice to help (I have spent all of 10minutes looking at it haha).

**Comment by rafiron** [comment]
Still wondering, how is it working for you then ...
