### ISSUE TITLE
[App Support] beardedspice no longer detects applicable tabs Chrome Canary

### ISSUE THREAD

**Issue by peterschussheim** [beardedspice/beardedspice#794]
Hi,

As the title describes, Chrome Canary (68.0.3437.2 ) running on macOS does **not** detect any audio tabs.  It's actually been broken for over a week.

Thanks,
Peter

**Comment by peterschussheim** [comment]
Still broken, I would be happy to send a patch in a PR provided some guidance is provided... :)

**Comment by nelsonjchen** [comment]
See my explanations/workaround in #818 . Whatever the changes are, they've landed at stable.

**Comment by peterschussheim** [comment]
@nelsonjchen thanks for looking into this and your workaround for enabling applescripts, this was very helpful!
