### ISSUE TITLE
Spotify pauses on Google Home when Macbook lid is closed

### ISSUE THREAD

**Issue by bbbenji** [beardedspice/beardedspice#800]
I would like Spotify to continue playing on my Google Home device when I close my Macbook. The way BeardedSpice currently works, Spotify pauses on Google Home. Is there a solution?

**Comment by sauravyash** [comment]
bearded spice doesn't have any control over that. I'd recommend something like InsomniaX or similar.
http://semaja2.net/ye-ol-projects/insomniaxinfo/
