### ISSUE TITLE
[App Support] BBC iPlayer

### ISSUE THREAD

**Issue by AlexBroadbent** [beardedspice/beardedspice#815]
Could you add support for [BBC iPlayer](https://www.bbc.co.uk/iplayer)?

Thanks!

**Comment by caleuanhopkins** [comment]
iPlayer works, if you're using Chrome you need to following these instructions: https://github.com/beardedspice/beardedspice/wiki/Won't-work-issue-after-Chrome-Update-(68.0.3440.75-and-later)

**Comment by AlexBroadbent** [comment]
Ah excellent, thanks!
