### ISSUE TITLE
App stopped displaying notifications

### ISSUE THREAD

**Issue by falsefalse** [beardedspice/beardedspice#82]
Tried with mostly with Google Play Music and SoundCloud, and different hotkeys. 

Mac OS X 10.9.5

**Comment by foozee** [comment]
soundcloud now have notifications, and @clayton-grey 's PR #91 has also been merged, so closing this issue, please feel free to reopen if issue comes  back :)

**Comment by falsefalse** [comment]
Cool, thanks!
