### ISSUE TITLE
No longer working for Youtube on Chrome Latest (v68)

### ISSUE THREAD

**Issue by dialex** [beardedspice/beardedspice#821]
My chrome updated yesterday to the latest version (v68) and now BS can't detect my youtube tabs. Even when playing music. Even after restarting Chrome or BS.

<img width="1215" alt="screen shot 2018-08-01 at 15 11 42" src="https://user-images.githubusercontent.com/2140450/43526957-51649ca4-959d-11e8-820e-66c1bbd965a7.png">

Do you need any other info?

**Comment by zspoelstra** [comment]
This is #818 for me. @dialex give that a shot

https://github.com/beardedspice/beardedspice/wiki/Won't-work-issue-after-Chrome-Update-(68.0.3440.75-and-later)

**Comment by jmcouillard** [comment]
Stingray not working as well with Chrome 68. In fact, I couldn't find a single website working with Chrome 68 and BeardedSpice.

**Comment by Primajin** [comment]
thanks @zspoelstra @ottnorml works like a charm again!

**Comment by dialex** [comment]
Yup it works! Solution at https://github.com/beardedspice/beardedspice/issues/818#issuecomment-408583289

Activate this:
![image](https://user-images.githubusercontent.com/2140450/43650796-9f1c3f78-9738-11e8-8fe9-1d230cc952ea.png)
