### ISSUE TITLE
[App Support] Chrome

### ISSUE THREAD

**Issue by desmondw** [beardedspice/beardedspice#822]
BeardedSpice does not seem to be recognizing any chrome app at all after an update.
My current version is Version 68.0.3440.84 (Official Build) (64-bit)

**Comment by marcusmoore** [comment]
The fix in this issue seems to work https://github.com/beardedspice/beardedspice/issues/818#issuecomment-408583289

**Comment by desmondw** [comment]
Thanks @marcusmoore that worked!
