### ISSUE TITLE
Beardedspice does not recognise active tabs

### ISSUE THREAD

**Issue by metodribic** [beardedspice/beardedspice#825]
Beardedspice stopped working all of a sudden. The only player that works is Itunes (I've checked  youtube, mixcloud, soundcloud and itunes). I tried in Chrome, FF and Safari but the result is the same. Reinstall of Beardedspice didn't solve the issue.

Chrome version: 68.0.3440.84
Beardedspice version: 2.2.3 (latest)
macOS: High Sierra 10.13.6

Please let me know if you need any additional info.

![screenshot 2018-08-09 08 50 14 2](https://user-images.githubusercontent.com/6840850/43882852-7a5ccacc-9bb1-11e8-960e-d3f1ca97fe77.png)

**Comment by KisaW** [comment]
Hello,
I am in the same situation

This no longer works with Deezer, even after rebooting or reinstalling BeardedSpice

(chrome : Version 68.0.3440.84 (Build officiel) (64 bits))
(MacOs : Version 10.13.6)

**Comment by gabrielecirulli** [comment]
Same here, initially noticed with SoundCloud, YouTube also seems not to work.

Chrome: Version 68.0.3440.106 (Official Build) (64-bit)
macOS: 10.13.6
Beardedspice: 2.2.3 (29)

**Comment by hoisingtonp** [comment]
Seeing the same issue with YouTube, Spotify web player, etc--anything in Chrome.

Chrome: Version 68.0.3440.84 (Official Build) (64-bit)
macOS: 10.13.6 (17G65)
Beardedspice: 2.2.3

**Comment by raffcorreia** [comment]
I was experiencing the same issue, but this fixed for me: [Won't work issue after Chrome Update](https://github.com/beardedspice/beardedspice/wiki/Won't-work-issue-after-Chrome-Update-(68.0.3440.75-and-later))

1) On chrome click on View > Develop > Allow Javascript to run from Apple Events.
2) Quit and reopen Beardedspice

**Comment by gabrielecirulli** [comment]
I'd still suggest adding an information box in BeardedSpice's settings if
this is the case. It can be really hard to find that information otherwise.
