### ISSUE TITLE
[App Support] I'm not able to use the built-in keyboard FF/BW/playPause buttons to control the track

### ISSUE THREAD

**Issue by Ido-PX** [beardedspice/beardedspice#827]
Pressing these buttons has no effect. I'm also unable to define them as a shortcut, when I press them while defining a shortcut nothing happens. To make sure it's not the keyboard, when I press another key the shortcut is recorded.

**Comment by mliq** [comment]
@Ido-PX I agree this is confusing, but I believe the answer is: 
1. the default keys automatically work, you do not need to define them in preferences. The shortcut preferences are only for defining _additional_ keys. 
2. So, if these keys are doing nothing for you it is probably another issue. Perhaps [this issue?](https://github.com/beardedspice/beardedspice/wiki/Won't-work-issue-after-Chrome-Update-(68.0.3440.75-and-later))

**Comment by Ido-PX** [comment]
@mliq Thanks for your help.

The issue you linked to may be at least part of the problem, as the setting wasn't checked. Unfortunately still the keys aren't working. 
I'm using chrome Version 68.0.3440.106 (Official Build) (64-bit) on MacBook Pro (Retina, 13-inch, Mid 2014) with OSX high sierra 10.13.4 (17E199)

**Comment by Ido-PX** [comment]
Ok, I'm not sure what has changed but it works now.

Before posting the comment above I closed and reopened chrome and beardedspice and it still wasn't working. However now I randomly tried while listening to music and it appears to be working.

Unfortunately I'm not sure what interim action may have made it work, or if I just did something wrong the last time I tried.
