### ISSUE TITLE
Not able to find youtube or youtube music

### ISSUE THREAD

**Issue by hardikhhh1** [beardedspice/beardedspice#840]
I tested that it works perfectly to find spotify mac app and gaana website on chrome. But its not able to find youtube or youtube music.

Chrome version: 69.0.3497.100
Bearded spice version: 2.2.3
Mac: 10.13.6 (High Sierra)

**Comment by MarcoAltranDC** [comment]
Try this: https://github.com/beardedspice/beardedspice/wiki/Won't-work-issue-after-Chrome-Update-(68.0.3440.75-and-later)

**Comment by hardikhhh1** [comment]
I had tried this, but it didn't work. But worked after multiple chrome restarts.
