### ISSUE TITLE
[App Support] new.radioparadise.com

### ISSUE THREAD

**Issue by michaelblyons** [beardedspice/beardedspice#877]
Please consider supporting https://new.radioparadise.com/player.

**Comment by ymilin** [comment]
Hi @michaelblyons 

I have made a PR (#880) just for this 😄

You can start to use it now by downloading [RadioParadise.js](https://github.com/beardedspice/beardedspice/pull/880/files#diff-cc4604e9c09b00d3e5d9c38cec0ad6a2) and import it in Preference.

**Comment by michaelblyons** [comment]
> You can start using it now by downloading [RadioParadise.js](https://github.com/beardedspice/beardedspice/pull/880/files#diff-cc4604e9c09b00d3e5d9c38cec0ad6a2) and import it in Preference.

I sure can. You're a champ!
