### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by adamcstephens** [beardedspice/beardedspice#893]
No PRs or updates in a few months. Are there still maintainers here? Are others willing to assist?

**Comment by Primajin** [comment]
I hope so. Chrome has stopped working for me. Would be really sad if this project is dead

**Comment by fharper** [comment]
Would also love to know!

**Comment by btb** [comment]
I don't know, but I got Chrome to work by following https://github.com/beardedspice/beardedspice/wiki/Won't-work-issue-after-Chrome-Update-(68.0.3440.75-and-later) and running 'Check for Comaptibility Updates'

**Comment by Porco-Rosso** [comment]
The same setting is available in Vivaldi under "Tools" -> "Allow Javascript from Apple Events"

**Comment by fharper** [comment]
That worked for me with the @btb second steps! Thanks

**Comment by abrambailey** [comment]
Ah thank you!!! Bearded spice has never worked for me, and now I can finally control bandcamp!

**Comment by julionc** [comment]
any update ? @Stillness-2 @1ps0 @trhodeos @josefalcon

**Comment by ml4** [comment]
Chrome has stopped working in Version 78.0.3904.97 (Official Build) (64-bit)

I have View > Developer > Allow JavaScript from Apple Events on and did a check for compat updates, after reinstalling BeardedSpice and restarting Chrome.  I guess I should maybe remove the plist?

**Comment by Primajin** [comment]
I actually stopped using BeardedSpice - Chrome now works for me natively

**Comment by ml4** [comment]
@Primajin Thanks! When you say natively, that suggests there are controls somewhere to 'press play' on 'a website'.  All I can find on search are mostly defunct extensions for Chrome.  Could you be more specific about the way you achieve this please?

**Comment by Primajin** [comment]
Oh yes sure - so I mostly listen to music in YouTube. I can have chrome open in the background and let a video play. When I hit the [Rev] [Play] [FF] keys on my Mac keyboard or in the fancy touch bar the video automatically pauses and plays, aswell as forwards to the next video etc. even if the browser window is not focused.

That's suffices my use case.

**Comment by ml4** [comment]
Oh! Yes I see for bandcamp.com play/pause works but in Album view FF/Rev touch bar doesn't.  That's good enough for me - cheers!

**Comment by Stillness-2** [comment]
#899
