### ISSUE TITLE
BUG: Chrome crash on a bar icon click

### ISSUE THREAD

**Issue by saaadel** [beardedspice/beardedspice#984]
When I have a Chrome window as current active, and click on the BeardedSpice bar icon - the Chrome window crashes (closes).
Next time Chrome notifies that the previous session was crashed.

macOS Big Sur - Version 11.4
Chrome for macOS - Version 91.0.4472.77 (Official Build) (x86_64)
BeardedSpice - Version BeardedSpice 2.2.3

**Comment by saaadel** [comment]
new info: it does not require to have a Chrome window as active

**Comment by saaadel** [comment]
do you need a video shot of this issue?

**Comment by vityevato** [comment]
@saaadel you may try this https://github.com/Stillness-2/beardie

**Comment by saaadel** [comment]
thanks! Works
